/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.enhanced.dynamodb.extensions;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import java.util.function.Consumer;
import software.amazon.awssdk.annotations.SdkPublicApi;
import software.amazon.awssdk.annotations.ThreadSafe;
import software.amazon.awssdk.enhanced.dynamodb.AttributeValueType;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClientExtension;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbExtensionContext;
import software.amazon.awssdk.enhanced.dynamodb.EnhancedType;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGenerateStrategy;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTag;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableMetadata;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;
import software.amazon.awssdk.utils.Validate;


/**
 * This extension facilitates the automatic generation of a UUID value for tagged string attributes.
 * UUID values are generated using {@link java.util.UUID#randomUUID()}.
 * <p>
 * This extension is not loaded by default when you instantiate a
 * {@link software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient}. Therefore, you need to specify it in a custom
 * extension when creating the enhanced client.
 * <p>
 * Example to add AutoGeneratedUuidExtension along with default extensions is
 * {@snippet :
 * DynamoDbEnhancedClient.builder().extensions(Stream.concat(ExtensionResolver.defaultExtensions().stream(),
 * Stream.of(AutoGeneratedUuidExtension.create())).collect(Collectors.toList())).build();
 *}
 * </p>
 * <p>
 * Example to just add AutoGeneratedUuidExtension without default extensions is
 * {@snippet :
 *             DynamoDbEnhancedClient.builder().extensions(AutoGeneratedUuidExtension.create()).build();
 *}
 * </p>
 * <p>
 * To use auto-generated UUID values, create a field in your model that stores the UUID attribute.
 * This field must be of type {@link java.lang.String}, and you need to tag it as auto-generated UUID. If you are
 * using the {@link software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema}, then you should use the
 * {@link DynamoDbAutoGeneratedUuid} annotation. If you are using
 * the {@link software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema}, then you should use the
 * {@link
 * software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension.AttributeTags#autoGeneratedUuidAttribute()}
 * static attribute tag.
 * </p>
 * <p>
 * Generation behavior is controlled by {@link DynamoDbAutoGenerateStrategy}:
 * <ul>
 *     <li>{@code ALWAYS}: generate a new UUID on every write handled by this extension.</li>
 *     <li>{@code CREATE}: generate a UUID only when the current value is missing from the write item map.
 *     Missing means the value is absent, {@code NULL}, or an empty string.</li>
 * </ul>
 * <p>
 * {@link software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior} is a separate concern used while building update
 * expressions for {@code updateItem}. It does not change this extension's strategy decision.
 * </p>
 */
@SdkPublicApi
@ThreadSafe
public final class AutoGeneratedUuidExtension implements DynamoDbEnhancedClientExtension {
    private static final String CUSTOM_METADATA_KEY =
        "software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension:AutoGeneratedUuidAttribute";
    private static final AutoGeneratedUuidAttribute AUTO_GENERATED_UUID_ALWAYS_ATTRIBUTE =
        new AutoGeneratedUuidAttribute(DynamoDbAutoGenerateStrategy.ALWAYS);
    private static final AutoGeneratedUuidAttribute AUTO_GENERATED_UUID_CREATE_ATTRIBUTE =
        new AutoGeneratedUuidAttribute(DynamoDbAutoGenerateStrategy.CREATE);

    private AutoGeneratedUuidExtension() {
    }

    /**
     * @return an Instance of {@link AutoGeneratedUuidExtension}
     */
    public static AutoGeneratedUuidExtension create() {
        return new AutoGeneratedUuidExtension();
    }

    /**
     * Modifies the WriteModification UUID string with the attribute updated with the extension.
     *
     * @param context The {@link DynamoDbExtensionContext.BeforeWrite} context containing the state of the execution.
     * @return WriteModification String updated with attribute updated with Extension.
     */
    @Override
    public WriteModification beforeWrite(DynamoDbExtensionContext.BeforeWrite context) {


        Map<String, DynamoDbAutoGenerateStrategy> customMetadataObject =
            context.tableMetadata()
                   .customMetadataObject(CUSTOM_METADATA_KEY, Map.class)
                   .orElse(null);

        if (customMetadataObject == null) {
            return WriteModification.builder().build();
        }

        Map<String, AttributeValue> itemToTransform = new HashMap<>(context.items());
        customMetadataObject.forEach((key, strategy) -> insertUuidInItemToTransform(itemToTransform, key, strategy));
        return WriteModification.builder()
                                .transformedItem(Collections.unmodifiableMap(itemToTransform))
                                .build();
    }

    private void insertUuidInItemToTransform(Map<String, AttributeValue> itemToTransform,
                                             String key,
                                             DynamoDbAutoGenerateStrategy strategy) {
        if (strategy == DynamoDbAutoGenerateStrategy.CREATE && !isMissingValue(itemToTransform.get(key))) {
            return;
        }
        itemToTransform.put(key, AttributeValue.builder().s(UUID.randomUUID().toString()).build());
    }

    private boolean isMissingValue(AttributeValue currentValue) {
        return currentValue == null || Boolean.TRUE.equals(currentValue.nul()) || "".equals(currentValue.s());
    }

    public static final class AttributeTags {

        private AttributeTags() {
        }

        /**
         * Tags which indicate that the given attribute is supported with Auto Generated UUID Record Extension.
         *
         * @return Tag name for AutoGenerated UUID Records
         */
        public static StaticAttributeTag autoGeneratedUuidAttribute() {
            return AUTO_GENERATED_UUID_ALWAYS_ATTRIBUTE;
        }

        /**
         * Tags which indicate that the given attribute is supported with Auto Generated UUID Record Extension and
         * applies the provided strategy.
         *
         * @return Tag name for AutoGenerated UUID Records
         */
        public static StaticAttributeTag autoGeneratedUuidAttribute(DynamoDbAutoGenerateStrategy strategy) {
            Validate.notNull(strategy, "strategy is null");
            return strategy == DynamoDbAutoGenerateStrategy.CREATE
                   ? AUTO_GENERATED_UUID_CREATE_ATTRIBUTE
                   : AUTO_GENERATED_UUID_ALWAYS_ATTRIBUTE;
        }
    }

    private static class AutoGeneratedUuidAttribute implements StaticAttributeTag {
        private final DynamoDbAutoGenerateStrategy strategy;

        private AutoGeneratedUuidAttribute(DynamoDbAutoGenerateStrategy strategy) {
            this.strategy = strategy;
        }

        @Override
        public <R> void validateType(String attributeName, EnhancedType<R> type,
                                     AttributeValueType attributeValueType) {

            Validate.notNull(type, "type is null");
            Validate.notNull(type.rawClass(), "rawClass is null");
            Validate.notNull(attributeValueType, "attributeValueType is null");

            if (!type.rawClass().equals(String.class)) {
                throw new IllegalArgumentException(String.format(
                    "Attribute '%s' of Class type %s is not a suitable Java Class type to be used as a Auto Generated "
                    + "Uuid attribute. Only String Class type is supported.", attributeName, type.rawClass()));
            }
        }

        @Override
        public Consumer<StaticTableMetadata.Builder> modifyMetadata(String attributeName,
                                                                    AttributeValueType attributeValueType) {
            return metadata -> metadata.addCustomMetadataObject(
                                           CUSTOM_METADATA_KEY, Collections.singletonMap(attributeName, strategy))
                                       .markAttributeAsKey(attributeName, attributeValueType);
        }
    }
}