/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.enhanced.dynamodb.extensions;

import static software.amazon.awssdk.enhanced.dynamodb.internal.EnhancedClientUtils.hasMap;
import static software.amazon.awssdk.enhanced.dynamodb.internal.extensions.utility.NestedRecordUtils.getListElementSchemaCached;
import static software.amazon.awssdk.enhanced.dynamodb.internal.extensions.utility.NestedRecordUtils.getNestedSchemaCached;
import static software.amazon.awssdk.enhanced.dynamodb.internal.extensions.utility.NestedRecordUtils.reconstructCompositeKey;
import static software.amazon.awssdk.enhanced.dynamodb.internal.extensions.utility.NestedRecordUtils.resolveSchemasPerPath;

import java.time.Clock;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Consumer;
import software.amazon.awssdk.annotations.NotThreadSafe;
import software.amazon.awssdk.annotations.SdkPublicApi;
import software.amazon.awssdk.annotations.ThreadSafe;
import software.amazon.awssdk.enhanced.dynamodb.AttributeConverter;
import software.amazon.awssdk.enhanced.dynamodb.AttributeValueType;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClientExtension;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbExtensionContext;
import software.amazon.awssdk.enhanced.dynamodb.EnhancedType;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.internal.extensions.utility.NestedRecordUtils;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTag;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableMetadata;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;
import software.amazon.awssdk.utils.Validate;

/**
 * This extension enables selected attributes to be automatically updated with a current timestamp every time they are written
 * to the database.
 * <p>
 *     This extension is not loaded by default when you instantiate a
 *     {@link software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient}. Thus you need to specify it in custom extension
 *     while creating the enhanced client.
 *     <p>
 *         Example to add AutoGeneratedTimestampRecordExtension along with default extensions is
 *         <code>DynamoDbEnhancedClient.builder().extensions(Stream.concat(ExtensionResolver.defaultExtensions().stream(),
 *         Stream.of(AutoGeneratedTimestampRecordExtension.create())).collect(Collectors.toList())).build();</code>
 *     </p>
 *     <p>
 *         Example to just add AutoGeneratedTimestampRecordExtension without default extensions is
 *         <code>DynamoDbEnhancedClient.builder().extensions(AutoGeneratedTimestampRecordExtension.create())).build();</code>
 *     </p>
 * </p>
 * <p>
 *     To utilize auto generated timestamp update, first create a field in your model that will be used to store the record
 *     timestamp of modification. This class field must be an {@link Instant} Class type, and you need to tag it as the
 *     autoGeneratedTimeStampAttribute. If you are using the
 *     {@link software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema}
 *     then you should use the
 *     {@link software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute}
 *     annotation, otherwise if you are using the {@link software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema}
 *     then you should use the {@link AttributeTags#autoGeneratedTimestampAttribute()} static attribute tag.
 * <p>
 * Every time a new update of the record is successfully written to the database, the timestamp at which it was modified will
 * be automatically updated. This extension applies the conversions as defined in the attribute convertor.
 * The implementation handles both flattened nested parameters (identified by keys separated with
 * {@code "_NESTED_ATTR_UPDATE_"}) and entire nested maps or lists, ensuring consistent behavior across both representations.
 * If a nested object or list is {@code null}, no timestamp values will be generated for any of its annotated fields.
 * The same timestamp value is used for both top-level attributes and all applicable nested fields.
 */
@SdkPublicApi
@ThreadSafe
public final class AutoGeneratedTimestampRecordExtension implements DynamoDbEnhancedClientExtension {

    private static final String NESTED_OBJECT_UPDATE = "_NESTED_ATTR_UPDATE_";
    private static final String CUSTOM_METADATA_KEY = "AutoGeneratedTimestampExtension:AutoGeneratedTimestampAttribute";
    private static final AutoGeneratedTimestampAttribute AUTO_GENERATED_TIMESTAMP_ATTRIBUTE =
        new AutoGeneratedTimestampAttribute();

    private final Clock clock;

    private AutoGeneratedTimestampRecordExtension() {
        this.clock = Clock.systemUTC();
    }

    /**
     * Attribute tag to identify the meta data for {@link AutoGeneratedTimestampRecordExtension}.
     */
    public static final class AttributeTags {

        private AttributeTags() {
        }

        /**
         * Tags which indicate that the given attribute is supported wih Auto Generated Timestamp Record Extension.
         * @return Tag name for AutoGenerated Timestamp Records
         */
        public static StaticAttributeTag autoGeneratedTimestampAttribute() {
            return AUTO_GENERATED_TIMESTAMP_ATTRIBUTE;
        }
    }

    private AutoGeneratedTimestampRecordExtension(Builder builder) {
        this.clock = builder.baseClock == null ? Clock.systemUTC() : builder.baseClock;
    }

    /**
     * Create a builder that can be used to create a {@link AutoGeneratedTimestampRecordExtension}.
     * @return Builder to create AutoGeneratedTimestampRecordExtension,
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Returns a builder initialized with all existing values on the Extension object.
     */
    public Builder toBuilder() {
        return builder().baseClock(this.clock);
    }

    /**
     * @return an Instance of {@link AutoGeneratedTimestampRecordExtension}
     */
    public static AutoGeneratedTimestampRecordExtension create() {
        return new AutoGeneratedTimestampRecordExtension();
    }

    /**
     * @param context The {@link DynamoDbExtensionContext.BeforeWrite} context containing the state of the execution.
     * @return WriteModification Instance updated with attribute updated with Extension.
     * @implNote Processing order: first {@link #processDirectNestedAttributes} for structured nested maps and lists of maps,
     * then {@link #processFlattenedNestedAttributes} for flattened composite keys. This extension maintains temporary,
     * per-operation caches for schema resolution and passes them to {@link NestedRecordUtils}. The caches are keyed by
     * {@link NestedRecordUtils.SchemaLookupKey} (parent {@link TableSchema} identity and attribute name) and are used by
     * {@link NestedRecordUtils#getNestedSchemaCached} and {@link NestedRecordUtils#getListElementSchemaCached}. The same nested
     * schema cache is also passed into {@link NestedRecordUtils#resolveSchemasPerPath} to avoid recomputing intermediate nested
     * schemas when both structured nested values and flattened nested keys are processed in the same write.
     */
    @Override
    public WriteModification beforeWrite(DynamoDbExtensionContext.BeforeWrite context) {
        Map<String, AttributeValue> itemToTransform = new HashMap<>(context.items());
        Map<String, AttributeValue> updatedItems = new HashMap<>();
        Instant currentInstant = clock.instant();

        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache = new HashMap<>();
        Map<NestedRecordUtils.SchemaLookupKey, TableSchema<?>> listElementSchemaCache = new HashMap<>();

        processDirectNestedAttributes(itemToTransform,
                                      updatedItems,
                                      context.tableSchema(),
                                      currentInstant,
                                      nestedSchemaCache,
                                      listElementSchemaCache);

        processFlattenedNestedAttributes(itemToTransform,
                                         updatedItems,
                                         context.tableSchema(),
                                         currentInstant,
                                         nestedSchemaCache);

        if (updatedItems.isEmpty()) {
            return WriteModification.builder().build();
        }

        // No overlap between nested map attributes and flattened composite keys: when IgnoreNullsMode.SCALAR_ONLY is used,
        // UpdateItemOperation#transformItemToMapForUpdateExpression flattens maps into composite keys before extensions run.
        itemToTransform.putAll(updatedItems);

        return WriteModification.builder()
                                .transformedItem(Collections.unmodifiableMap(itemToTransform))
                                .build();
    }

    private void processDirectNestedAttributes(
        Map<String, AttributeValue> itemToTransform,
        Map<String, AttributeValue> updatedItems,
        TableSchema<?> tableSchema,
        Instant currentInstant,
        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache,
        Map<NestedRecordUtils.SchemaLookupKey, TableSchema<?>> listElementSchemaCache) {

        itemToTransform.forEach((key, value) -> processTopLevelAttributeForTimestamps(key,
                                                                                      value,
                                                                                      tableSchema,
                                                                                      currentInstant,
                                                                                      nestedSchemaCache,
                                                                                      listElementSchemaCache,
                                                                                      updatedItems));
    }

    private void processTopLevelAttributeForTimestamps(
        String key,
        AttributeValue value,
        TableSchema<?> tableSchema,
        Instant currentInstant,
        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache,
        Map<NestedRecordUtils.SchemaLookupKey, TableSchema<?>> listElementSchemaCache,
        Map<String, AttributeValue> updatedItems) {

        if (hasMap(value)) {
            processTopLevelMapAttribute(key,
                                        value,
                                        tableSchema,
                                        currentInstant,
                                        nestedSchemaCache,
                                        listElementSchemaCache,
                                        updatedItems);

        } else if (value.hasL() && !value.l().isEmpty()) {
            processTopLevelListOfMapsAttribute(key,
                                               value,
                                               tableSchema,
                                               currentInstant,
                                               nestedSchemaCache,
                                               listElementSchemaCache,
                                               updatedItems);
        }
    }

    private void processTopLevelMapAttribute(
        String key,
        AttributeValue value,
        TableSchema<?> tableSchema,
        Instant currentInstant,
        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache,
        Map<NestedRecordUtils.SchemaLookupKey, TableSchema<?>> listElementSchemaCache,
        Map<String, AttributeValue> updatedItems) {

        Optional<TableSchema<?>> nestedSchemaOpt = getNestedSchemaCached(nestedSchemaCache, tableSchema, key);
        if (!nestedSchemaOpt.isPresent()) {
            return;
        }

        TableSchema<?> nestedSchema = nestedSchemaOpt.get();
        Map<String, AttributeValue> processed =
            processNestedObject(value.m(), nestedSchema, currentInstant, nestedSchemaCache, listElementSchemaCache);

        if (processed != value.m()) {
            updatedItems.put(key, AttributeValue.builder().m(processed).build());
        }
    }

    /**
     * When the attribute is a non-empty list whose first non-null element is a map, and a list element schema exists, rebuilds
     * the list by applying {@link #processNestedObject} to each map element (other elements are copied unchanged). The new list
     * is always written to {@code updatedItems} in that case, even if element contents are unchanged.
     */
    private void processTopLevelListOfMapsAttribute(
        String key,
        AttributeValue value,
        TableSchema<?> tableSchema,
        Instant currentInstant,
        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache,
        Map<NestedRecordUtils.SchemaLookupKey, TableSchema<?>> listElementSchemaCache,
        Map<String, AttributeValue> updatedItems) {

        AttributeValue firstElement = firstNonNullListElement(value);
        if (!hasMap(firstElement)) {
            return;
        }

        TableSchema<?> elementListSchema =
            getListElementSchemaCached(listElementSchemaCache, tableSchema, key, nestedSchemaCache);
        if (elementListSchema == null) {
            return;
        }

        Collection<AttributeValue> updatedList = new ArrayList<>(value.l().size());
        for (AttributeValue listItem : value.l()) {
            if (hasMap(listItem)) {
                updatedList.add(AttributeValue.builder()
                                              .m(processNestedObject(listItem.m(),
                                                                     elementListSchema,
                                                                     currentInstant,
                                                                     nestedSchemaCache,
                                                                     listElementSchemaCache))
                                              .build());
            } else {
                updatedList.add(listItem);
            }
        }
        updatedItems.put(key, AttributeValue.builder().l(updatedList).build());
    }

    private void processFlattenedNestedAttributes(
        Map<String, AttributeValue> itemToTransform,
        Map<String, AttributeValue> updatedItems,
        TableSchema<?> tableSchema,
        Instant currentInstant,
        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache) {

        Map<String, TableSchema<?>> schemasPerPath =
            resolveSchemasPerPath(itemToTransform, tableSchema, nestedSchemaCache);

        for (Map.Entry<String, TableSchema<?>> pathEntry : schemasPerPath.entrySet()) {
            String path = pathEntry.getKey();
            TableSchema<?> schema = pathEntry.getValue();

            Collection<String> customMetadataObject = schema.tableMetadata()
                                                            .customMetadataObject(CUSTOM_METADATA_KEY, Collection.class)
                                                            .orElse(null);

            if (customMetadataObject == null) {
                continue;
            }

            for (String attrName : customMetadataObject) {
                AttributeConverter<?> converter = schema.converterForAttribute(attrName);
                if (converter != null) {
                    insertTimestampInItemToTransform(updatedItems,
                                                     reconstructCompositeKey(path, attrName),
                                                     converter,
                                                     currentInstant);
                }
            }
        }
    }

    private Map<String, AttributeValue> processNestedObject(
        Map<String, AttributeValue> nestedMap,
        TableSchema<?> nestedSchema,
        Instant currentInstant,
        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache,
        Map<NestedRecordUtils.SchemaLookupKey, TableSchema<?>> listElementSchemaCache) {

        Map<String, AttributeValue> updatedNestedMap =
            applyAutoGeneratedTimestampsToMap(nestedMap, nestedSchema, currentInstant);
        boolean updated = !Objects.equals(updatedNestedMap, nestedMap);

        for (Map.Entry<String, AttributeValue> entry : nestedMap.entrySet()) {
            String nestedKey = entry.getKey();
            AttributeValue nestedValue = entry.getValue();

            AttributeValue replacement = null;
            if (nestedValue.hasM()) {
                replacement = replacedNestedMapValueIfModified(nestedValue,
                                                                 nestedKey,
                                                                 nestedSchema,
                                                                 currentInstant,
                                                                 nestedSchemaCache,
                                                                 listElementSchemaCache);
            } else if (nestedValue.hasL() && !nestedValue.l().isEmpty()) {
                replacement = replacedNestedListValueIfModified(nestedValue,
                                                                  nestedKey,
                                                                  nestedSchema,
                                                                  currentInstant,
                                                                  nestedSchemaCache,
                                                                  listElementSchemaCache);
            }

            if (replacement != null) {
                if (!updated) {
                    updatedNestedMap = new HashMap<>(nestedMap);
                    updated = true;
                }
                updatedNestedMap.put(nestedKey, replacement);
            }
        }

        return updatedNestedMap;
    }

    private Map<String, AttributeValue> applyAutoGeneratedTimestampsToMap(
        Map<String, AttributeValue> nestedMap,
        TableSchema<?> nestedSchema,
        Instant currentInstant) {

        Collection<String> customMetadataObject = nestedSchema.tableMetadata()
                                                              .customMetadataObject(CUSTOM_METADATA_KEY, Collection.class)
                                                              .orElse(null);

        if (customMetadataObject == null) {
            return nestedMap;
        }

        Map<String, AttributeValue> updatedNestedMap = nestedMap;
        boolean mapCopied = false;

        for (String key : customMetadataObject) {
            AttributeConverter<?> converter = nestedSchema.converterForAttribute(key);
            if (converter != null) {
                if (!mapCopied) {
                    updatedNestedMap = new HashMap<>(nestedMap);
                    mapCopied = true;
                }
                insertTimestampInItemToTransform(updatedNestedMap, key, converter, currentInstant);
            }
        }

        return updatedNestedMap;
    }

    /**
     * @return a map {@link AttributeValue} if the nested map changed after recursion; {@code null} if unchanged or if there is
     * no nested schema for this key
     */
    private AttributeValue replacedNestedMapValueIfModified(
        AttributeValue nestedValue,
        String nestedKey,
        TableSchema<?> nestedSchema,
        Instant currentInstant,
        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache,
        Map<NestedRecordUtils.SchemaLookupKey, TableSchema<?>> listElementSchemaCache) {

        Optional<TableSchema<?>> childSchemaOpt = getNestedSchemaCached(nestedSchemaCache, nestedSchema, nestedKey);
        if (!childSchemaOpt.isPresent()) {
            return null;
        }

        Map<String, AttributeValue> processed =
            processNestedObject(nestedValue.m(),
                                childSchemaOpt.get(),
                                currentInstant,
                                nestedSchemaCache,
                                listElementSchemaCache);

        if (Objects.equals(processed, nestedValue.m())) {
            return null;
        }

        return AttributeValue.builder().m(processed).build();
    }

    /**
     * @return a list {@link AttributeValue} if at least one map element changed; {@code null} if unchanged or if this is not
     * a list of maps with a resolvable element schema
     */
    private AttributeValue replacedNestedListValueIfModified(
        AttributeValue nestedValue,
        String nestedKey,
        TableSchema<?> nestedSchema,
        Instant currentInstant,
        Map<NestedRecordUtils.SchemaLookupKey, Optional<TableSchema<?>>> nestedSchemaCache,
        Map<NestedRecordUtils.SchemaLookupKey, TableSchema<?>> listElementSchemaCache) {

        AttributeValue firstElement = firstNonNullListElement(nestedValue);
        if (!hasMap(firstElement)) {
            return null;
        }

        TableSchema<?> listElementSchema =
            getListElementSchemaCached(listElementSchemaCache, nestedSchema, nestedKey, nestedSchemaCache);
        if (listElementSchema == null) {
            return null;
        }

        Collection<AttributeValue> updatedList = new ArrayList<>(nestedValue.l().size());
        boolean listModified = false;

        for (AttributeValue listItem : nestedValue.l()) {
            if (hasMap(listItem)) {
                Map<String, AttributeValue> processedItem =
                    processNestedObject(listItem.m(),
                                        listElementSchema,
                                        currentInstant,
                                        nestedSchemaCache,
                                        listElementSchemaCache);

                AttributeValue updatedItem = AttributeValue.builder().m(processedItem).build();
                updatedList.add(updatedItem);

                if (!Objects.equals(updatedItem, listItem)) {
                    listModified = true;
                }
            } else {
                updatedList.add(listItem);
            }
        }

        if (!listModified) {
            return null;
        }

        return AttributeValue.builder().l(updatedList).build();
    }

    private static AttributeValue firstNonNullListElement(AttributeValue listAttribute) {
        return listAttribute.l().stream().filter(Objects::nonNull).findFirst().orElse(null);
    }

    private void insertTimestampInItemToTransform(Map<String, AttributeValue> itemToTransform,
                                                  String key,
                                                  AttributeConverter converter,
                                                  Instant instant) {
        itemToTransform.put(key, converter.transformFrom(instant));
    }

    /**
     *  Builder for a {@link AutoGeneratedTimestampRecordExtension}
     */
    @NotThreadSafe
    public static final class Builder {
        private Clock baseClock;

        private Builder() {
        }

        /**
         * Sets the clock instance , else Clock.systemUTC() is used by default.
         * Every time a new timestamp is generated this clock will be used to get the current point in time. If a custom clock
         * is not specified, the default system clock will be used.
         *
         * @param clock Clock instance to set the current timestamp.
         * @return This builder for method chaining.
         */
        public Builder baseClock(Clock clock) {
            this.baseClock = clock;
            return this;
        }

        /**
         * Builds an {@link AutoGeneratedTimestampRecordExtension} based on the values stored in this builder
         */
        public AutoGeneratedTimestampRecordExtension build() {
            return new AutoGeneratedTimestampRecordExtension(this);
        }
    }

    private static class AutoGeneratedTimestampAttribute implements StaticAttributeTag {

        @Override
        public <R> void validateType(String attributeName,
                                     EnhancedType<R> type,
                                     AttributeValueType attributeValueType) {
            Validate.notNull(type, "type is null");
            Validate.notNull(type.rawClass(), "rawClass is null");
            Validate.notNull(attributeValueType, "attributeValueType is null");
            validateAttributeName(attributeName);

            if (!type.rawClass().equals(Instant.class)) {
                throw new IllegalArgumentException(String.format(
                    "Attribute '%s' of Class type %s is not a suitable Java Class type to be used as a Auto Generated "
                    + "Timestamp attribute. Only java.time.Instant Class type is supported.", attributeName, type.rawClass()));
            }
        }

        @Override
        public Consumer<StaticTableMetadata.Builder> modifyMetadata(String attributeName,
                                                                    AttributeValueType attributeValueType) {
            return metadata -> metadata.addCustomMetadataObject(CUSTOM_METADATA_KEY, Collections.singleton(attributeName))
                                       .markAttributeAsKey(attributeName, attributeValueType);
        }

        private static void validateAttributeName(String attributeName) {
            if (attributeName.contains(NESTED_OBJECT_UPDATE)) {
                throw new IllegalArgumentException(
                    String.format("Attribute name '%s' contains reserved marker '%s' and is not allowed.",
                                  attributeName, NESTED_OBJECT_UPDATE));
            }
        }
    }
}
