version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    groups:
      # Group updates together that tend to update multiple packages together
      netty:
        patterns:
          - "io.netty*"
      jackson:
        patterns:
          - "com.fasterxml.jackson*"
    ignore:
      # We don't want to update from 1.x.x unless necessary because it will
      # require extra verification to ensure customers aren't broken by the
      # update.
      - dependency-name: "org.slf4j:*"
        update-types: ["version-update:semver-major"]

      # Ignore test dependencies to reduce PR noisiness. We don't need to stay
      # on top of them as much as compile/runtime dependencies
      - dependency-name: "com.amazonaws:aws-java-sdk*"
      - dependency-name: "com.amazonaws:DynamoDBLocal"
      - dependency-name: "com.github.tomakehurst:*"
      - dependency-name: "org.mockito:*"
      - dependency-name: "nl.jqno.equalsverifier:*"
      - dependency-name: "org.assertj:*"
      - dependency-name: "com.google.guava:*"
      - dependency-name: "com.google.jimfs:jimfs"
      - dependency-name: "org.junit.jupiter:*"
      - dependency-name: "junit:*"
      - dependency-name: "org.testng:*"
      - dependency-name: "org.hamcrest:*"
      - dependency-name: "com.almworks.sqlite4java:*"
      - dependency-name: "org.eclipse.jetty:*"
      - dependency-name: "javax.servlet:*"
      - dependency-name: "io.reactivex.rxjava3:rxjava"
      - dependency-name: "xmlunit:xmlunit"

      # Non runtime dependencies
      # Eclipse JDT deps used at codegen time
      - dependency-name: "org.eclipse.jdt:*"

      # Maven/build system updates don't have to track very latest. Again, to
      # reduce noisiness
      - dependency-name: "org.apache.maven.plugins:*"
      - dependency-name: "org.sonatype.plugins:*"
      - dependency-name: "org.apache.maven.plugins:maven-archetype-plugin"
      - dependency-name: "org.codehaus.mojo:build-helper-maven-plugin"
      - dependency-name: "org.codehaus.mojo:exec-maven-plugin"
      - dependency-name: "org.apache.maven.plugin-tools:maven-plugin-annotations"
      - dependency-name: "org.graalvm.buildtools:*"
      - dependency-name: "org.jacoco:jacoco-maven-plugin"
      - dependency-name: "org.apache.commons:commons-lang3"
      - dependency-name: "org.codehaus.plexus:plexus-utils"
