version: 0.2
cache:
  paths:
    - '/root/.m2/**/*'

phases:
  install:
    runtime-versions:
      java: "corretto8"

  build:
    commands:
      - java -version
reports:
  IntegTests:
    files:
      - 'codebuild-test-reports/**/*'
