version: 0.2

phases:

  build:
    commands:
    - mvn clean install -pl :archetype-app-quickstart -P quick --am -T1C
    - mvn clean install -pl :bom,:bom-internal -P quick
    - CURRENT_VERSION=$(cat pom.xml | grep "<version>" | head -1 | cut -d\> -f 2 | cut -d\< -f 1)
    - echo "Current version is $CURRENT_VERSION"
    - cd .. && mkdir tmp
    - cd tmp
    - |
      mvn archetype:generate \
        -DarchetypeGroupId=software.amazon.awssdk \
        -DarchetypeArtifactId=archetype-app-quickstart \
        -DarchetypeVersion=$CURRENT_VERSION \
        -DgroupId=com.test \
        -DnativeImage=true \
        -DartifactId=apache-project \
        -DhttpClient=apache-client \
        -Dservice=s3  \
        -DinteractiveMode=false
    - |
    - cd apache-project
    - mvn clean package -P native-image
    - target/apache-project
    - cd ..
    -
    -
    - |
      mvn archetype:generate \
        -DarchetypeGroupId=software.amazon.awssdk \
        -DarchetypeArtifactId=archetype-app-quickstart \
        -DarchetypeVersion=$CURRENT_VERSION \
        -DgroupId=com.test \
        -DnativeImage=true \
        -DhttpClient=url-connection-client \
        -DartifactId=url-connection-project \
        -Dservice=s3  \
        -DinteractiveMode=false
    - |
    - cd url-connection-project
    - mvn clean package -P native-image
    - target/url-connection-project
    - cd ..
    -
    -
    - |
      mvn archetype:generate \
        -DarchetypeGroupId=software.amazon.awssdk \
        -DarchetypeArtifactId=archetype-app-quickstart \
        -DarchetypeVersion=$CURRENT_VERSION \
        -DgroupId=com.test \
        -DhttpClient=netty-nio-client \
        -DnativeImage=true \
        -DartifactId=netty-project \
        -Dservice=dynamodb  \
        -DinteractiveMode=false
    - |
    - cd netty-project
    - mvn clean package -P native-image
    - target/netty-project