version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - mvn clean install -T1C
      - JAVA_VERSION=$(java -version 2>&1 | grep -i version | cut -d'"' -f2 | cut -d'.' -f1-1)
      - echo $JAVA_VERSION
      - |
        if [ "$JAVA_VERSION" -ge "9" ]; then
          cd test/module-path-tests
          mvn package
          mvn exec:exec -P mock-tests
        fi
      # Codebuild doesn't have good support for mixed formats within the same
      # directory tree so just excluding these for now. Only the TCK tests are
      # based on TestNG.
      - find ./ -name testng-native-results -type d -exec rm -r {} \;
      - find ./ -name testng-junit-results -type d -exec rm -r {} \;
        
reports: 
  UnitTests:
    files:
      - '**/*'
    base-directory: '**/*/target/surefire-reports' # Location of the reports 
