version: 0.2

phases:
  build:
    commands:
      - mvn clean install -Dmaven.wagon.httpconnectionManager.maxPerRoute=2
      - JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d\" -f 2)
      - echo $JAVA_VERSION
      - |
        if [ "$JAVA_VERSION" \> "9" ]; then
          cd test/module-path-tests
          mvn package
          mvn exec:exec -P mock-tests
        fi
