version: 0.2
cache:
  paths:
    - '/root/.m2/**/*'

phases:
  install:
    runtime-versions:
      java: "$JAVA_RUNTIME"

  build:
    commands:
      - |
        if [ ! -z "$INTEGRATION_TEST_ROLE_ARN" ]; then
          mkdir -p ~/.aws
          cat > ~/.aws/config << EOF
        [default]
        credential_source = EcsContainer
        role_arn = $INTEGRATION_TEST_ROLE_ARN
        EOF
          echo "Created AWS config for assuming role $INTEGRATION_TEST_ROLE_ARN with auto-refresh."
        fi
      - mvn clean install -Dskip.unit.tests -P integration-tests -Dfindbugs.skip -Dcheckstyle.skip -T1C $MAVEN_OPTIONS
      - JAVA_VERSION=$(java -version 2>&1 | grep -i version | cut -d'"' -f2 | cut -d'.' -f1-1)
      - echo $JAVA_VERSION
      - echo $MAVEN_OPTIONS
      - |
        if [ "$JAVA_VERSION" -ge "9" ]; then
          cd test/module-path-tests
          mvn package
          mvn exec:exec -P integ-tests
        fi
    finally:
      - mkdir -p codebuild-test-reports
      - find ./ -name 'TEST-*.xml' -type f -exec cp {} codebuild-test-reports/ \;
reports:
  IntegTests:
    files:
      - 'codebuild-test-reports/**/*'
