version: 0.2

phases:
  install:
    runtime-versions:
      java: "$JAVA_RUNTIME"

  build:
    commands:
      - mvn clean install -pl :v2-migration-tests -P quick -am && mvn install -pl :v2-migration-tests -P migration-tests -T1C $MAVEN_OPTIONS
    finally:
      - mkdir -p codebuild-test-reports
      - find ./ -name 'TEST-*.xml' -type f -exec cp {} codebuild-test-reports/ \;
reports:
  IntegTests:
    files:
      - 'codebuild-test-reports/**/*'
