/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.enhanced.dynamodb.extensions.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import software.amazon.awssdk.annotations.SdkPublicApi;
import software.amazon.awssdk.enhanced.dynamodb.internal.extensions.AutoGeneratedUuidTag;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.BeanTableSchemaAttributeTag;

/**
 * Marks an attribute to be automatically populated with a new UUID on every write operation.
 *
 * <p><b>Intended Usage:</b>
 * This annotation is generic and may be applied to any {@link String} attribute, not only key attributes.
 *
 * <h3>Generation Semantics:</h3>
 * On every write (put, update, batch write, or transaction write), the attribute is replaced with a new value generated using
 * {@link java.util.UUID#randomUUID()}, regardless of any existing value.
 *
 * <p><b>Difference from {@code @DynamoDbAutoGeneratedKey}:</b>
 * {@code @DynamoDbAutoGeneratedKey} is intended for key attributes and generates UUID only when the value is absent.
 * {@code @DynamoDbAutoGeneratedUuid} annotation always regenerates the UUID on each write.</p>
 *
 * <h3>Type Restriction:</h3>
 * This annotation may only be applied to attributes of type {@link String}.
 */
@SdkPublicApi
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@BeanTableSchemaAttributeTag(AutoGeneratedUuidTag.class)
public @interface DynamoDbAutoGeneratedUuid {
}