/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.services.s3.presigner.model;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Consumer;
import software.amazon.awssdk.annotations.Immutable;
import software.amazon.awssdk.annotations.NotThreadSafe;
import software.amazon.awssdk.annotations.SdkPublicApi;
import software.amazon.awssdk.annotations.ThreadSafe;
import software.amazon.awssdk.services.s3.internal.signing.PostPolicyDocument;
import software.amazon.awssdk.services.s3.presigner.model.PostPolicyConditions.PolicyCondition;
import software.amazon.awssdk.utils.Validate;
import software.amazon.awssdk.utils.builder.CopyableBuilder;
import software.amazon.awssdk.utils.builder.ToCopyableBuilder;

/**
 * A request to generate a pre-signed POST policy for browser-based uploads.
 */
@SdkPublicApi
@Immutable
@ThreadSafe
public final class PresignPostObjectRequest
        implements ToCopyableBuilder<PresignPostObjectRequest.Builder, PresignPostObjectRequest> {
    private static final String KEY_FIELD = "key";

    private final String bucket;
    private final String key;
    private final Duration signatureDuration;
    private final Instant expiration;
    private final PostPolicyConditions conditions;
    private final Map<String, String> fields;

    private PresignPostObjectRequest(Builder builder) {
        this.bucket = Validate.paramNotBlank(builder.bucket, "bucket");
        this.key = Validate.paramNotBlank(builder.key, "key");
        this.signatureDuration = builder.signatureDuration;
        this.expiration = builder.expiration;
        this.conditions = builder.conditions == null ? PostPolicyConditions.empty() : builder.conditions;
        this.fields = Collections.unmodifiableMap(copyFields(builder.fields));

        if (signatureDuration != null && expiration != null) {
            throw new IllegalArgumentException("Only one of signatureDuration or expiration may be set.");
        }
        if (signatureDuration == null && expiration == null) {
            throw new IllegalArgumentException("One of signatureDuration or expiration must be set.");
        }

        validateReservedFieldNames(fields);
        validateFieldMappings(key, fields, conditions);
    }

    public static Builder builder() {
        return new Builder();
    }

    public String bucket() {
        return bucket;
    }

    public String key() {
        return key;
    }

    /**
     * Present when the caller configured a signature duration.
     */
    public Optional<Duration> signatureDuration() {
        return Optional.ofNullable(signatureDuration);
    }

    /**
     * Present when the caller configured an absolute expiration time for the policy.
     */
    public Optional<Instant> expiration() {
        return Optional.ofNullable(expiration);
    }

    public PostPolicyConditions conditions() {
        return conditions;
    }

    /**
     * Returns additional form fields that should be included in the multipart form post (excluding fields generated by the
     * presigner such as {@code policy}).
     */
    public Map<String, String> fields() {
        return fields;
    }

    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    private static Map<String, String> copyFields(Map<String, String> source) {
        Map<String, String> copy = new LinkedHashMap<>();
        for (Map.Entry<String, String> entry : source.entrySet()) {
            copy.put(entry.getKey(), entry.getValue());
        }
        return copy;
    }

    private static void validateReservedFieldNames(Map<String, String> fields) {
        for (String name : fields.keySet()) {
            if (PostPolicyDocument.isReservedFieldName(name)) {
                throw new IllegalArgumentException("Field '" + name + "' uses a reserved name. Reserved names are "
                                                   + PostPolicyDocument.RESERVED_FIELD_NAMES + ". Use the presigner "
                                                   + "configuration instead of supplying this field directly.");
            }
        }
    }

    private static void validateFieldMappings(String objectKey,
                                             Map<String, String> fields,
                                             PostPolicyConditions conditions) {

        List<PolicyCondition> conditionList = new ArrayList<>(conditions.conditions());

        for (Map.Entry<String, String> entry : fields.entrySet()) {
            String fieldName = entry.getKey();
            String value = entry.getValue();

            if (KEY_FIELD.equalsIgnoreCase(fieldName)) {
                validateKeyField(objectKey, value, conditionList);
                continue;
            }

            if (!fieldMatchesConditions(fieldName, value, conditionList)) {
                throw new IllegalArgumentException("Form field '" + fieldName
                                                   + "' does not have a matching policy condition. Add a matching condition "
                                                   + "via conditions(...) or use addExactField(...) to add both together.");
            }
        }
    }

    private static void validateKeyField(String objectKey, String value, List<PolicyCondition> userConditions) {
        boolean userKeyCondition = userConditions.stream().anyMatch(PresignPostObjectRequest::targetsObjectKey);
        if (userKeyCondition) {
            if (!fieldMatchesConditions(KEY_FIELD, value, userConditions)) {
                throw new IllegalArgumentException(
                    "Form field 'key' value does not satisfy the configured key policy conditions.");
            }
            return;
        }

        int idx = objectKey.indexOf("${filename}");
        if (idx >= 0) {
            String prefix = objectKey.substring(0, idx);
            if (!value.startsWith(prefix)) {
                throw new IllegalArgumentException("Form field 'key' value must start with '" + prefix + "' for the "
                                                   + "configured object key template.");
            }
        } else if (!Objects.equals(value, objectKey)) {
            throw new IllegalArgumentException("Form field 'key' must match the configured object key.");
        }
    }

    private static boolean targetsObjectKey(PolicyCondition condition) {
        if (condition instanceof PostPolicyConditions.Eq) {
            PostPolicyConditions.Eq eq = (PostPolicyConditions.Eq) condition;
            return KEY_FIELD.equals(eq.field());
        }
        if (condition instanceof PostPolicyConditions.StartsWith) {
            PostPolicyConditions.StartsWith startsWith = (PostPolicyConditions.StartsWith) condition;
            return "$key".equals(startsWith.field());
        }
        return false;
    }

    private static boolean fieldMatchesConditions(String fieldName,
                                                  String value,
                                                  List<PolicyCondition> conditionList) {
        for (PolicyCondition condition : conditionList) {
            if (condition instanceof PostPolicyConditions.Eq) {
                PostPolicyConditions.Eq eq = (PostPolicyConditions.Eq) condition;
                if (eq.field().equals(fieldName) && Objects.equals(eq.value(), value)) {
                    return true;
                }
            } else if (condition instanceof PostPolicyConditions.StartsWith) {
                PostPolicyConditions.StartsWith startsWith = (PostPolicyConditions.StartsWith) condition;
                if (fieldNameMatchesStartsWith(fieldName, startsWith.field()) && value.startsWith(startsWith.prefix())) {
                    return true;
                }
            }
        }
        return false;
    }

    private static boolean fieldNameMatchesStartsWith(String fieldName, String startsWithField) {
        if (startsWithField.equals(fieldName)) {
            return true;
        }
        if (startsWithField.startsWith("$") && startsWithField.substring(1).equals(fieldName)) {
            return true;
        }
        return false;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        PresignPostObjectRequest that = (PresignPostObjectRequest) o;

        if (!bucket.equals(that.bucket)) {
            return false;
        }
        if (!key.equals(that.key)) {
            return false;
        }
        if (signatureDuration != null ? !signatureDuration.equals(that.signatureDuration)
                                       : that.signatureDuration != null) {
            return false;
        }
        if (expiration != null ? !expiration.equals(that.expiration) : that.expiration != null) {
            return false;
        }
        if (!conditions.equals(that.conditions)) {
            return false;
        }
        return fields.equals(that.fields);
    }

    @Override
    public int hashCode() {
        int result = bucket.hashCode();
        result = 31 * result + key.hashCode();
        result = 31 * result + (signatureDuration != null ? signatureDuration.hashCode() : 0);
        result = 31 * result + (expiration != null ? expiration.hashCode() : 0);
        result = 31 * result + conditions.hashCode();
        result = 31 * result + fields.hashCode();
        return result;
    }

    @SdkPublicApi
    @NotThreadSafe
    public static final class Builder implements CopyableBuilder<Builder, PresignPostObjectRequest> {
        private String bucket;
        private String key;
        private Duration signatureDuration;
        private Instant expiration;
        private PostPolicyConditions conditions;
        private final Map<String, String> fields = new LinkedHashMap<>();

        private Builder() {
        }

        private Builder(PresignPostObjectRequest request) {
            this.bucket = request.bucket;
            this.key = request.key;
            this.signatureDuration = request.signatureDuration;
            this.expiration = request.expiration;
            this.conditions = request.conditions;
            this.fields.putAll(request.fields);
        }

        public Builder bucket(String bucket) {
            this.bucket = bucket;
            return this;
        }

        public Builder key(String key) {
            this.key = key;
            return this;
        }

        public Builder signatureDuration(Duration signatureDuration) {
            this.signatureDuration = signatureDuration;
            return this;
        }

        public Builder expiration(Instant expiration) {
            this.expiration = expiration;
            return this;
        }

        public Builder conditions(PostPolicyConditions conditions) {
            this.conditions = conditions;
            return this;
        }

        public Builder conditions(Consumer<PostPolicyConditions.Builder> conditions) {
            PostPolicyConditions.Builder consumerBuilder = PostPolicyConditions.builder();
            conditions.accept(consumerBuilder);
            this.conditions = consumerBuilder.build();
            return this;
        }

        public Builder addField(String name, String value) {
            Validate.paramNotNull(name, "name");
            Validate.paramNotNull(value, "value");
            fields.put(name, value);
            return this;
        }

        public Builder addExactField(String name, String value) {
            Validate.paramNotNull(name, "name");
            Validate.paramNotNull(value, "value");
            PostPolicyConditions.Builder conditionBuilder = PostPolicyConditions.builder();
            if (conditions != null) {
                for (PolicyCondition policyCondition : conditions.conditions()) {
                    appendCondition(conditionBuilder, policyCondition);
                }
            }
            conditionBuilder.eq(name, value);
            conditions = conditionBuilder.build();
            fields.put(name, value);
            return this;
        }

        public Builder addExactFields(Map<String, String> fieldMap) {
            Validate.paramNotNull(fieldMap, "fieldMap");
            for (String name : fieldMap.keySet()) {
                if (PostPolicyDocument.isReservedFieldName(name)) {
                    throw new IllegalArgumentException("Field '" + name + "' uses a reserved name.");
                }
            }

            Map<String, String> mergedFields = new LinkedHashMap<>(this.fields);
            for (Map.Entry<String, String> entry : fieldMap.entrySet()) {
                mergedFields.put(entry.getKey(), entry.getValue());
            }

            PostPolicyConditions.Builder conditionBuilder = PostPolicyConditions.builder();
            if (conditions != null) {
                for (PolicyCondition policyCondition : conditions.conditions()) {
                    appendCondition(conditionBuilder, policyCondition);
                }
            }
            for (Map.Entry<String, String> entry : fieldMap.entrySet()) {
                conditionBuilder.eq(entry.getKey(), entry.getValue());
            }
            PostPolicyConditions mergedConditions = conditionBuilder.build();

            validateFieldMappings(key, mergedFields, mergedConditions);

            this.conditions = mergedConditions;
            for (Map.Entry<String, String> entry : fieldMap.entrySet()) {
                this.fields.put(entry.getKey(), entry.getValue());
            }
            return this;
        }

        private static void appendCondition(PostPolicyConditions.Builder builder, PolicyCondition condition) {
            if (condition instanceof PostPolicyConditions.ContentLengthRange) {
                PostPolicyConditions.ContentLengthRange range = (PostPolicyConditions.ContentLengthRange) condition;
                builder.contentLengthRange(range.min(), range.max());
            } else if (condition instanceof PostPolicyConditions.StartsWith) {
                PostPolicyConditions.StartsWith startsWith = (PostPolicyConditions.StartsWith) condition;
                builder.startsWith(startsWith.field(), startsWith.prefix());
            } else if (condition instanceof PostPolicyConditions.Eq) {
                PostPolicyConditions.Eq eq = (PostPolicyConditions.Eq) condition;
                builder.eq(eq.field(), eq.value());
            }
        }

        public PresignPostObjectRequest build() {
            return new PresignPostObjectRequest(this);
        }
    }
}
