/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.enhanced.dynamodb.functionaltests.models;

import static software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension.AttributeTags.autoGeneratedTimestampAttribute;
import static software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags.primaryPartitionKey;

import java.time.Instant;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema;

/**
 * Shared test record used by batch/transact write functional tests that exercise
 * {@link software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension}.
 */
public class TimestampedRecord {
    public static final TableSchema<TimestampedRecord> TABLE_SCHEMA =
        StaticTableSchema.builder(TimestampedRecord.class)
                         .newItemSupplier(TimestampedRecord::new)
                         .addAttribute(String.class, a -> a.name("id")
                                                           .getter(TimestampedRecord::getId)
                                                           .setter(TimestampedRecord::setId)
                                                           .tags(primaryPartitionKey()))
                         .addAttribute(Instant.class, a -> a.name("time")
                                                            .getter(TimestampedRecord::getTime)
                                                            .setter(TimestampedRecord::setTime)
                                                            .tags(autoGeneratedTimestampAttribute()))
                         .build();

    private String id;
    private Instant time;

    public String getId() {
        return id;
    }

    public TimestampedRecord setId(String id) {
        this.id = id;
        return this;
    }

    public Instant getTime() {
        return time;
    }

    public TimestampedRecord setTime(Instant time) {
        this.time = time;
        return this;
    }
}
