/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.enhanced.dynamodb.extensions;

import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedKeyExtension.AttributeTags.autoGeneratedKeyAttribute;
import static software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension.AttributeTags.autoGeneratedUuidAttribute;
import static software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags.primaryPartitionKey;

import java.util.Map;
import org.junit.jupiter.api.Test;
import software.amazon.awssdk.enhanced.dynamodb.OperationContext;
import software.amazon.awssdk.enhanced.dynamodb.TableMetadata;
import software.amazon.awssdk.enhanced.dynamodb.internal.extensions.DefaultDynamoDbExtensionContext;
import software.amazon.awssdk.enhanced.dynamodb.internal.operations.DefaultOperationContext;
import software.amazon.awssdk.enhanced.dynamodb.internal.operations.OperationName;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;

/**
 * Tests to verify that conflicting annotations (@DynamoDbAutoGeneratedKey and @DynamoDbAutoGeneratedUuid) are properly detected
 * and throw exceptions regardless of extension load order.
 */
public class ConflictingAnnotationsTest {

    private static final String RECORD_ID = "1";
    private static final String TABLE_NAME = "table-name";
    private static final OperationContext PRIMARY_CONTEXT =
        DefaultOperationContext.create(TABLE_NAME, TableMetadata.primaryIndexName());

    private final AutoGeneratedKeyExtension keyExtension = AutoGeneratedKeyExtension.builder().build();
    private final AutoGeneratedUuidExtension uuidExtension = AutoGeneratedUuidExtension.create();

    /**
     * Schema with both annotations on the same attribute to test conflict detection.
     */
    private static final StaticTableSchema<RecordWithAutogenerated> CONFLICTING_SCHEMA =
        StaticTableSchema.builder(RecordWithAutogenerated.class)
                         .newItemSupplier(RecordWithAutogenerated::new)
                         .addAttribute(String.class, a -> a.name("autogeneratedKeyField")
                                                           .getter(RecordWithAutogenerated::getAutogeneratedKeyField)
                                                           .setter(RecordWithAutogenerated::setAutogeneratedKeyField)
                                                           .addTag(primaryPartitionKey())
                                                           // Both annotations on the same attribute
                                                           .addTag(autoGeneratedKeyAttribute())
                                                           .addTag(autoGeneratedUuidAttribute()))
                         .build();

    @Test
    public void autogeneratedKeyExtensionFirst_detectsConflictWithUuidExtension() {
        RecordWithAutogenerated item = new RecordWithAutogenerated();
        item.setAutogeneratedKeyField(RECORD_ID);

        Map<String, AttributeValue> items = CONFLICTING_SCHEMA.itemToMap(item, true);

        // AutoGeneratedKeyExtension runs first and detects conflict
        assertThatExceptionOfType(IllegalArgumentException.class)
            .isThrownBy(() -> keyExtension.beforeWrite(
                DefaultDynamoDbExtensionContext.builder()
                                               .items(items)
                                               .tableMetadata(CONFLICTING_SCHEMA.tableMetadata())
                                               .operationName(OperationName.PUT_ITEM)
                                               .operationContext(PRIMARY_CONTEXT)
                                               .build())
            )
            .withMessage("Attribute 'autogeneratedKeyField' cannot have both "
                         + "@DynamoDbAutoGeneratedKey and @DynamoDbAutoGeneratedUuid annotations. "
                         + "These annotations have conflicting behaviors and cannot be used together on the same attribute.");
    }

    @Test
    public void autogeneratedUuidExtensionFirst_detectsConflictWithKeyExtension() {
        RecordWithAutogenerated item = new RecordWithAutogenerated();
        item.setAutogeneratedKeyField(RECORD_ID);

        Map<String, AttributeValue> items = CONFLICTING_SCHEMA.itemToMap(item, true);

        // AutoGeneratedUuidExtension runs first and detects conflict
        assertThatExceptionOfType(IllegalArgumentException.class)
            .isThrownBy(() -> uuidExtension.beforeWrite(
                DefaultDynamoDbExtensionContext.builder()
                                               .items(items)
                                               .tableMetadata(CONFLICTING_SCHEMA.tableMetadata())
                                               .operationName(OperationName.PUT_ITEM)
                                               .operationContext(PRIMARY_CONTEXT)
                                               .build())
            )
            .withMessage("Attribute 'autogeneratedKeyField' cannot have both "
                         + "@DynamoDbAutoGeneratedKey and @DynamoDbAutoGeneratedUuid annotations. "
                         + "These annotations have conflicting behaviors and cannot be used together on the same attribute.");
    }

    @Test
    public void autogeneratedAnnotations_onSeparateAttributes_doesNotDetectConflict() {
        // Schema with annotations on different attributes - does not detect conflict
        StaticTableSchema<RecordWithAutogenerated> separateSchema =
            StaticTableSchema.builder(RecordWithAutogenerated.class)
                             .newItemSupplier(RecordWithAutogenerated::new)
                             .addAttribute(String.class, a -> a.name("autogeneratedKeyField")
                                                               .getter(RecordWithAutogenerated::getAutogeneratedKeyField)
                                                               .setter(RecordWithAutogenerated::setAutogeneratedKeyField)
                                                               .addTag(primaryPartitionKey())
                                                               .addTag(autoGeneratedKeyAttribute()))
                             .addAttribute(String.class, a -> a.name("autogeneratedUuidField")
                                                               .getter(RecordWithAutogenerated::getAutogeneratedUuidField)
                                                               .setter(RecordWithAutogenerated::setAutogeneratedUuidField)
                                                               .addTag(autoGeneratedUuidAttribute()))
                             .build();

        RecordWithAutogenerated item = new RecordWithAutogenerated();

        Map<String, AttributeValue> items = separateSchema.itemToMap(item, true);

        // Both extensions should work without conflict when on different attributes
        keyExtension.beforeWrite(DefaultDynamoDbExtensionContext.builder()
                                                                .items(items)
                                                                .tableMetadata(separateSchema.tableMetadata())
                                                                .operationName(OperationName.PUT_ITEM)
                                                                .operationContext(PRIMARY_CONTEXT)
                                                                .build());

        uuidExtension.beforeWrite(DefaultDynamoDbExtensionContext.builder()
                                                                 .items(items)
                                                                 .tableMetadata(separateSchema.tableMetadata())
                                                                 .operationName(OperationName.PUT_ITEM)
                                                                 .operationContext(PRIMARY_CONTEXT)
                                                                 .build());
    }

    public static class RecordWithAutogenerated {
        private String autogeneratedKeyField;
        private String autogeneratedUuidField;

        public String getAutogeneratedKeyField() {
            return autogeneratedKeyField;
        }

        public void setAutogeneratedKeyField(String autogeneratedKeyField) {
            this.autogeneratedKeyField = autogeneratedKeyField;
        }

        public String getAutogeneratedUuidField() {
            return autogeneratedUuidField;
        }

        public void setAutogeneratedUuidField(String autogeneratedUuidField) {
            this.autogeneratedUuidField = autogeneratedUuidField;
        }
    }
}