/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package software.amazon.awssdk.enhanced.dynamodb.extensions;

import static org.assertj.core.api.Assertions.assertThat;
import static software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags.primaryPartitionKey;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;
import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClientExtension;
import software.amazon.awssdk.enhanced.dynamodb.TableMetadata;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.internal.extensions.DefaultDynamoDbExtensionContext;
import software.amazon.awssdk.enhanced.dynamodb.internal.operations.DefaultOperationContext;
import software.amazon.awssdk.enhanced.dynamodb.internal.operations.OperationName;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;

public class ExtensionSpiContractTest {

    private static final String TABLE_NAME = "extension-spi-contract-table";

    private static final TableSchema<NoExtensionItem> TABLE_SCHEMA = StaticTableSchema.builder(NoExtensionItem.class)
                                                                                      .newItemSupplier(NoExtensionItem::new)
                                                                                      .addAttribute(String.class,
                                                                                                     a -> a.name("id")
                                                                                                           .getter(NoExtensionItem::getId)
                                                                                                           .setter(NoExtensionItem::setId)
                                                                                                           .tags(primaryPartitionKey()))
                                                                                      .build();

    private static final TableMetadata TABLE_METADATA = TABLE_SCHEMA.tableMetadata();

    private static final List<OperationName> WRITE_OPERATIONS = Arrays.asList(
        OperationName.PUT_ITEM,
        OperationName.UPDATE_ITEM,
        OperationName.BATCH_WRITE_ITEM,
        OperationName.TRANSACT_WRITE_ITEMS
    );

    private static Stream<Arguments> extensionAndOperations() {
        List<Supplier<DynamoDbEnhancedClientExtension>> extensionSuppliers = Arrays.asList(
            AutoGeneratedTimestampRecordExtension::create,
            AutoGeneratedUuidExtension::create,
            () -> AtomicCounterExtension.builder().build(),
            () -> VersionedRecordExtension.builder().build()
        );

        return extensionSuppliers.stream()
                                 .flatMap(supplier -> WRITE_OPERATIONS.stream()
                                                                      .map(operation -> Arguments.of(supplier.get(),
                                                                                                     operation)));
    }

    @ParameterizedTest(name = "{0} with {1}")
    @MethodSource("extensionAndOperations")
    public void beforeWrite_noOptionalCapabilities_returnsNoOpAndDoesNotMutateItems(
        DynamoDbEnhancedClientExtension extension,
        OperationName operationName) {

        Map<String, AttributeValue> items = new HashMap<>();
        items.put("id", AttributeValue.builder().s("id1").build());

        Map<String, AttributeValue> originalItems = new HashMap<>(items);

        DefaultDynamoDbExtensionContext context = DefaultDynamoDbExtensionContext.builder()
                                                                                  .items(items)
                                                                                  .tableMetadata(TABLE_METADATA)
                                                                                  .tableSchema(TABLE_SCHEMA)
                                                                                  .operationName(operationName)
                                                                                  .operationContext(DefaultOperationContext.create(TABLE_NAME))
                                                                                  .build();

        WriteModification modification = extension.beforeWrite(context);

        assertThat(items).isEqualTo(originalItems);
        assertThat(modification).isEqualTo(WriteModification.builder().build());
    }

    private static final class NoExtensionItem {
        private String id;

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }
}

