package software.amazon.awssdk.enhanced.dynamodb.extensions;

import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.when;
import static software.amazon.awssdk.enhanced.dynamodb.extensions.ExtensionsValidationUtils.validateNoAnnotationConflict;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Optional;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import software.amazon.awssdk.enhanced.dynamodb.TableMetadata;

@RunWith(MockitoJUnitRunner.class)
public class ExtensionsValidationUtilsTest {

    @Mock
    private TableMetadata metadata;

    private static final String AUTOGENERATED_KEY_METADATA_KEY =
        "software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedKeyExtension:AutoGeneratedKeyAttribute";
    private static final String AUTOGENERATED_UUID_METADATA_KEY =
        "software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension:AutoGeneratedUuidAttribute";

    private static final String AUTOGENERATED_KEY_ANNOTATION = "@DynamoDbAutoGeneratedKey";
    private static final String AUTOGENERATED_UUID_ANNOTATION = "@DynamoDbAutoGeneratedUuid";

    @Test
    public void validateNoAnnotationConflict_whenAnnotationsOverlap_throwsException() {
        when(metadata.customMetadataObject(AUTOGENERATED_KEY_METADATA_KEY, Collection.class))
            .thenReturn(Optional.of(Collections.singleton("sharedAttribute")));
        when(metadata.customMetadataObject(AUTOGENERATED_UUID_METADATA_KEY, Collection.class))
            .thenReturn(Optional.of(Arrays.asList("sharedAttribute", "otherUuidAttribute")));

        assertThatThrownBy(() -> validateNoAnnotationConflict(
            metadata,
            AUTOGENERATED_KEY_METADATA_KEY,
            AUTOGENERATED_UUID_METADATA_KEY,
            AUTOGENERATED_KEY_ANNOTATION,
            AUTOGENERATED_UUID_ANNOTATION
        ))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessage(
                "Attribute 'sharedAttribute' cannot have both @DynamoDbAutoGeneratedKey and @DynamoDbAutoGeneratedUuid "
                + "annotations. These annotations have conflicting behaviors and cannot be used together on the same attribute.");
    }

    @Test
    public void validateNoAnnotationConflict_whenNoAnnotatedFields_doesNotThrowException() {
        assertThatCode(() -> validateNoAnnotationConflict(
            metadata,
            AUTOGENERATED_KEY_METADATA_KEY,
            AUTOGENERATED_UUID_METADATA_KEY,
            AUTOGENERATED_KEY_ANNOTATION,
            AUTOGENERATED_UUID_ANNOTATION
        )).doesNotThrowAnyException();
    }

    @Test
    public void validateNoAnnotationConflict_whenAnnotationsDontOverlap_doesNotThrowException() {
        when(metadata.customMetadataObject(AUTOGENERATED_KEY_METADATA_KEY, Collection.class))
            .thenReturn(Optional.of(Collections.singleton("keyAttribute")));
        when(metadata.customMetadataObject(AUTOGENERATED_UUID_METADATA_KEY, Collection.class))
            .thenReturn(Optional.of(Collections.singleton("uuidAttribute")));

        assertThatCode(() -> validateNoAnnotationConflict(
            metadata,
            AUTOGENERATED_KEY_METADATA_KEY,
            AUTOGENERATED_UUID_METADATA_KEY,
            AUTOGENERATED_KEY_ANNOTATION,
            AUTOGENERATED_UUID_ANNOTATION
        )).doesNotThrowAnyException();
    }

    @Test
    public void validateNoAnnotationConflict_whenSecondAnnotationIsNotUsed_doesNotThrow() {
        when(metadata.customMetadataObject(AUTOGENERATED_KEY_METADATA_KEY, Collection.class))
            .thenReturn(Optional.empty());

        assertThatCode(() -> validateNoAnnotationConflict(
            metadata,
            AUTOGENERATED_KEY_METADATA_KEY,
            AUTOGENERATED_UUID_METADATA_KEY,
            AUTOGENERATED_KEY_ANNOTATION,
            AUTOGENERATED_UUID_ANNOTATION
        )).doesNotThrowAnyException();
    }
}
