package com.amazonaws.services.dynamodbv2.mapper;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.LocalDynamoDBTestBase;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.model.AttributeDefinition;
import com.amazonaws.services.dynamodbv2.model.CreateTableRequest;
import com.amazonaws.services.dynamodbv2.model.GlobalSecondaryIndex;
import com.amazonaws.services.dynamodbv2.model.GlobalSecondaryIndexDescription;
import com.amazonaws.services.dynamodbv2.model.KeySchemaElement;
import com.amazonaws.services.dynamodbv2.model.KeyType;
import com.amazonaws.services.dynamodbv2.model.LocalSecondaryIndex;
import com.amazonaws.services.dynamodbv2.model.LocalSecondaryIndexDescription;
import com.amazonaws.services.dynamodbv2.model.ProvisionedThroughput;
import com.amazonaws.services.dynamodbv2.model.ScalarAttributeType;
import com.amazonaws.services.dynamodbv2.model.TableDescription;
import com.amazonaws.services.dynamodbv2.util.TableUtils;
import com.amazonaws.test.util.UnorderedCollectionComparator;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

/**
 * Tests that the CreateTableRequest generated by DynamoDBMapper.generateCreateTableRequest
 * correctly creates the expected table.
 */
public class GenerateCreateTableRequest2Test extends LocalDynamoDBTestBase {

    private static final Set<String> testedTableName = new HashSet<String>();
    private static final ProvisionedThroughput DEFAULT_CAPACITY = new ProvisionedThroughput(5L, 5L);
    private static DynamoDBMapper mapper;
    private static AmazonDynamoDB dynamo;

    @BeforeClass
    public static void setUp() throws Exception {
        dynamo = client();
        mapper = new DynamoDBMapper(dynamo);
    }

    @AfterClass
    public static void tearDown() {
        for (String tableName : testedTableName) {
            dynamo.deleteTable(tableName);
        }
    }

    @Test
    public void testParseIndexRangeKeyClass() throws Exception {
        CreateTableRequest request = mapper.generateCreateTableRequest(IndexRangeKeyClass.class);
        String createdTableName = appendCurrentTimeToTableName(request);
        testedTableName.add(createdTableName);
        setProvisionedThroughput(request, DEFAULT_CAPACITY);

        TableDescription createdTableDescription = dynamo.createTable(request).getTableDescription();

        assertEquals(createdTableName, createdTableDescription.getTableName());
        List<KeySchemaElement> expectedKeyElements = Arrays.asList(
                new KeySchemaElement("key", KeyType.HASH),
                new KeySchemaElement("rangeKey", KeyType.RANGE)
                );
        assertEquals(expectedKeyElements, createdTableDescription.getKeySchema());

        List<AttributeDefinition> expectedAttrDefinitions = Arrays.asList(
                new AttributeDefinition("key", ScalarAttributeType.N),
                new AttributeDefinition("rangeKey", ScalarAttributeType.N),
                new AttributeDefinition("indexFooRangeKey", ScalarAttributeType.N),
                new AttributeDefinition("indexBarRangeKey", ScalarAttributeType.N),
                new AttributeDefinition("multipleIndexRangeKey", ScalarAttributeType.N)
                );
        assertTrue(UnorderedCollectionComparator.equalUnorderedCollections(
                expectedAttrDefinitions,
                createdTableDescription.getAttributeDefinitions()));

        List<LocalSecondaryIndex> expectedLsi = Arrays.asList(
                new LocalSecondaryIndex()
                        .withIndexName("index_foo")
                        .withKeySchema(
                                new KeySchemaElement("key", KeyType.HASH),
                                new KeySchemaElement("indexFooRangeKey", KeyType.RANGE)),
                new LocalSecondaryIndex()
                        .withIndexName("index_bar")
                        .withKeySchema(
                                new KeySchemaElement("key", KeyType.HASH),
                                new KeySchemaElement("indexBarRangeKey", KeyType.RANGE)),
                new LocalSecondaryIndex()
                        .withIndexName("index_foo_copy")
                        .withKeySchema(
                                new KeySchemaElement("key", KeyType.HASH),
                                new KeySchemaElement("multipleIndexRangeKey", KeyType.RANGE)),
                new LocalSecondaryIndex()
                        .withIndexName("index_bar_copy")
                        .withKeySchema(
                                new KeySchemaElement("key", KeyType.HASH),
                                new KeySchemaElement("multipleIndexRangeKey", KeyType.RANGE)));
        assertTrue(equalLsi(expectedLsi, createdTableDescription.getLocalSecondaryIndexes()));

        assertNull(request.getGlobalSecondaryIndexes());
        assertEquals(DEFAULT_CAPACITY, request.getProvisionedThroughput());

        // Only one table with indexes can be created simultaneously
        TableUtils.waitUntilActive(dynamo, createdTableName);
    }

    @Test
    public void testComplexIndexedHashRangeClass() throws Exception {
        CreateTableRequest request = mapper.generateCreateTableRequest(MapperQueryExpressionTest.HashRangeClass.class);
        String createdTableName = appendCurrentTimeToTableName(request);
        testedTableName.add(createdTableName);
        setProvisionedThroughput(request, DEFAULT_CAPACITY);

        TableDescription createdTableDescription = dynamo.createTable(request).getTableDescription();

        assertEquals(createdTableName, createdTableDescription.getTableName());
        List<KeySchemaElement> expectedKeyElements = Arrays.asList(
                new KeySchemaElement("primaryHashKey", KeyType.HASH),
                new KeySchemaElement("primaryRangeKey", KeyType.RANGE)
                );
        assertEquals(expectedKeyElements, createdTableDescription.getKeySchema());

        List<AttributeDefinition> expectedAttrDefinitions = Arrays.asList(
                new AttributeDefinition("primaryHashKey", ScalarAttributeType.S),
                new AttributeDefinition("indexHashKey", ScalarAttributeType.S),
                new AttributeDefinition("primaryRangeKey", ScalarAttributeType.S),
                new AttributeDefinition("indexRangeKey", ScalarAttributeType.S),
                new AttributeDefinition("anotherIndexRangeKey", ScalarAttributeType.S)
                );
        assertTrue(UnorderedCollectionComparator.equalUnorderedCollections(
                expectedAttrDefinitions,
                createdTableDescription.getAttributeDefinitions()));

        List<LocalSecondaryIndex> expectedLsi = Arrays.asList(
                new LocalSecondaryIndex()
                        .withIndexName("LSI-primary-range")
                        .withKeySchema(
                                new KeySchemaElement("primaryHashKey", KeyType.HASH),
                                new KeySchemaElement("primaryRangeKey", KeyType.RANGE)),
                new LocalSecondaryIndex()
                        .withIndexName("LSI-index-range-1")
                        .withKeySchema(
                                new KeySchemaElement("primaryHashKey", KeyType.HASH),
                                new KeySchemaElement("indexRangeKey", KeyType.RANGE)),
                new LocalSecondaryIndex()
                        .withIndexName("LSI-index-range-2")
                        .withKeySchema(
                                new KeySchemaElement("primaryHashKey", KeyType.HASH),
                                new KeySchemaElement("indexRangeKey", KeyType.RANGE)),
                new LocalSecondaryIndex()
                        .withIndexName("LSI-index-range-3")
                        .withKeySchema(
                                new KeySchemaElement("primaryHashKey", KeyType.HASH),
                                new KeySchemaElement("anotherIndexRangeKey", KeyType.RANGE)));
        assertTrue(equalLsi(expectedLsi, createdTableDescription.getLocalSecondaryIndexes()));

        List<GlobalSecondaryIndex> expectedGsi = Arrays.asList(
                new GlobalSecondaryIndex()
                        .withIndexName("GSI-primary-hash-index-range-1")
                        .withKeySchema(
                                new KeySchemaElement("primaryHashKey", KeyType.HASH),
                                new KeySchemaElement("indexRangeKey", KeyType.RANGE)),
                new GlobalSecondaryIndex()
                        .withIndexName("GSI-primary-hash-index-range-2")
                        .withKeySchema(
                                new KeySchemaElement("primaryHashKey", KeyType.HASH),
                                new KeySchemaElement("anotherIndexRangeKey", KeyType.RANGE)),
                new GlobalSecondaryIndex()
                        .withIndexName("GSI-index-hash-primary-range")
                        .withKeySchema(
                                new KeySchemaElement("indexHashKey", KeyType.HASH),
                                new KeySchemaElement("primaryRangeKey", KeyType.RANGE)),
                new GlobalSecondaryIndex()
                        .withIndexName("GSI-index-hash-index-range-1")
                        .withKeySchema(
                                new KeySchemaElement("indexHashKey", KeyType.HASH),
                                new KeySchemaElement("indexRangeKey", KeyType.RANGE)),
                new GlobalSecondaryIndex()
                        .withIndexName("GSI-index-hash-index-range-2")
                        .withKeySchema(
                                new KeySchemaElement("indexHashKey", KeyType.HASH),
                                new KeySchemaElement("indexRangeKey", KeyType.RANGE)));
        assertTrue(equalGsi(expectedGsi, createdTableDescription.getGlobalSecondaryIndexes()));

        assertEquals(DEFAULT_CAPACITY, request.getProvisionedThroughput());

        // Only one table with indexes can be created simultaneously
        TableUtils.waitUntilActive(dynamo, createdTableName);
    }

    private static void setProvisionedThroughput(CreateTableRequest request, ProvisionedThroughput throughput) {
        request.setProvisionedThroughput(throughput);
        if (request.getGlobalSecondaryIndexes() != null) {
            for (GlobalSecondaryIndex gsi : request.getGlobalSecondaryIndexes()) {
                gsi.setProvisionedThroughput(throughput);
            }
        }
    }

    private static boolean equalLsi(Collection<LocalSecondaryIndex> a, Collection<LocalSecondaryIndexDescription> b) {
        return UnorderedCollectionComparator.equalUnorderedCollections(a, b, new LocalSecondaryIndexDefinitionComparator());
    }

    private static boolean equalGsi(Collection<GlobalSecondaryIndex> a, Collection<GlobalSecondaryIndexDescription> b) {
        return UnorderedCollectionComparator.equalUnorderedCollections(a, b, new GlobalSecondaryIndexDefinitionComparator());
    }

    private static class LocalSecondaryIndexDefinitionComparator
            implements
            UnorderedCollectionComparator.CrossTypeComparator<LocalSecondaryIndex, LocalSecondaryIndexDescription> {

        @Override
        public boolean equals(LocalSecondaryIndex a, LocalSecondaryIndexDescription b) {
            return a.getIndexName().equals(b.getIndexName())
                    && a.getKeySchema().equals(b.getKeySchema());
        }

    }

    private static class GlobalSecondaryIndexDefinitionComparator
            implements
            UnorderedCollectionComparator.CrossTypeComparator<GlobalSecondaryIndex, GlobalSecondaryIndexDescription> {

        @Override
        public boolean equals(GlobalSecondaryIndex a, GlobalSecondaryIndexDescription b) {
            return a.getIndexName().equals(b.getIndexName())
                    && a.getKeySchema().equals(b.getKeySchema());
        }
    }

    private static String appendCurrentTimeToTableName(CreateTableRequest request) {
        String appendedName = String.format("%s-%d", request.getTableName(), System.currentTimeMillis());
        request.setTableName(appendedName);
        return appendedName;
    }
}
