/*
 * Copyright 2010-2019 Amazon.com, Inc. or its affiliates. All Rights
 * Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.amazonaws.services.dynamodbv2.mapper;

import static com.amazonaws.services.dynamodbv2.TestObjectCreator.ConditionExpressionMode;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.TransactionWriteTestData;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.TransactionWriteTestRequest;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createHashKeyRangeKeyTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createMultipleObjectTestDataForTransactionWrite;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkMapperSaveConfigTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createStringHashKeyTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.deleteTestTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.extractAllObjectsFromTransactionWriteOperations;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.extractExpectedResponseObjects;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.extractObjectKeysForValidResponseSendingOperations;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.generateStringMatcherTransactWriteExpression;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getCustomBooleanClassObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getHashRangeAutoGenOtherAttributeObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getStringAttributeClass;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getStringHashAndRangeKeyObjectWithKeys;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getTestItemObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.updateTransactionWriteOperationsWithNewObject;
import static software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig.ObjectTableNameResolver;
import static software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig.TableNameOverride;
import static software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig.TableNameResolver;
import static software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig.builder;
import static software.amazon.awssdk.mapper.dynamodb.TransactionWriteRequest.TransactionWriteOperation;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import software.amazon.awssdk.mapper.dynamodb.DynamoDBMapper;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBMappingException;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTable;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTransactionWriteExpression;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTypeConverter;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTypeConverterFactory;
import software.amazon.awssdk.mapper.dynamodb.TransactionWriteRequest;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.GetItemResult;
import com.amazonaws.services.dynamodbv2.pojos.CustomBooleanClass;
import com.amazonaws.services.dynamodbv2.pojos.HashKeyAutoGenerated;
import com.amazonaws.services.dynamodbv2.pojos.HashKeyRangeKeyBothAutoGenerated;
import com.amazonaws.services.dynamodbv2.pojos.HashKeyRangeKeyClass;
import com.amazonaws.services.dynamodbv2.pojos.HashRangeAndOtherAttributeAutoGen;
import com.amazonaws.services.dynamodbv2.pojos.PrimaryKeysNotAutogenerated_OtherAttributeAutogenerated;
import com.amazonaws.services.dynamodbv2.pojos.RangeKeyClass;
import com.amazonaws.services.dynamodbv2.pojos.StringAttributeClass;
import com.amazonaws.services.dynamodbv2.pojos.TestItem;
import com.amazonaws.services.dynamodbv2.utils.AttributeAdder;
import org.junit.Test;

public class TransactionWriteMixedTest extends TransactionsTestBase {

    // Some arbitrary big integer
    private static final int ATTRIBUTE_ADDER_START = 12345678;
    private static final String ADDITIONAL_ATTRIBUTE_NAME = "extra_attribute";
    private static final String STRING_ATTRIBUTE_SUB_CLASS_TABLE_NAME = "sdk-util-a34556-1c48-5d66-9c18-6872715852v7";

    @DynamoDBTable(tableName = STRING_ATTRIBUTE_SUB_CLASS_TABLE_NAME)
    public static class StringAttributeSubClass extends StringAttributeClass {

    }

    // TODO: Refactor tableNameResolvers to re-use code between multiple such instances in transactionLoad/transactionWrite integration tests
    private static final TableNameResolver tableNameResolverForMissingKeyTests = new TableNameResolver() {
        @Override
        public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
            if (StringAttributeClass.class.equals(clazz)) {
                return sdkUtilTableName;
            }
            if (TestItem.class.equals(clazz)) {
                return mapperSaveConfigTableName;
            }
            if (RangeKeyClass.class.equals(clazz)) {
                return sdkRangeTableName;
            }
            if (HashKeyRangeKeyBothAutoGenerated.class.equals(clazz)) {
                return "sdk-string-keys-" + tableNameSuffix;
            }
            if (HashKeyRangeKeyClass.class.equals(clazz)) {
                return sdkHashRangeTestTableName;
            }
            throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
        }
    };

    @Test
    public void testWithTableNameOverride() throws InterruptedException {
        String overriddenTableName = "sdk-util-" + UUID.randomUUID().toString();
        DynamoDBMapperConfig config = builder().withTableNameOverride(TableNameOverride.withTableNameReplacement(overriddenTableName)).build();
        DynamoDBMapper mapperWithTableNameOverride = new DynamoDBMapper(dynamo, config);
        try {
            createStringHashKeyTable(dynamo, overriddenTableName);
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(false);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameOverride, transactionWriteTestRequest);
            executeAndValidateTransactionWrite(mapperWithTableNameOverride,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
        } finally {
            deleteTestTable(dynamo, overriddenTableName);
        }
    }

    // This test is needed because by default TransactionsIntegrationTestBase creates mapper with TableNameResolver
    @Test
    public void testWithoutAnyOverriddenConfig() throws InterruptedException {
        DynamoDBMapper mapperWithoutConfig = new DynamoDBMapper(dynamo);
        try {
            createStringHashKeyTable(dynamo, STRING_ATTRIBUTE_SUB_CLASS_TABLE_NAME);

            StringAttributeSubClass objectToBeUpdated = getStringAttributeSubClassObject();
            StringAttributeSubClass objectToBeConditionChecked = getStringAttributeSubClassObject();
            StringAttributeSubClass objectToBeDeleted = getStringAttributeSubClassObject();

            saveObjects(mapperWithoutConfig, objectToBeUpdated, objectToBeConditionChecked, objectToBeDeleted);

            StringAttributeSubClass objectToBePut = getStringAttributeSubClassObject();
            TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
            transactionWriteRequest.addPut(objectToBePut);
            String updatedStringAttribute = "updatedStringAttribute";
            objectToBeUpdated.setStringAttribute(updatedStringAttribute);
            transactionWriteRequest.addUpdate(objectToBeUpdated);
            DynamoDBTransactionWriteExpression conditionCheckWriteExpression =
                    generateStringMatcherTransactWriteExpression(objectToBeConditionChecked.getStringAttribute(),
                                                                 "not" + updatedStringAttribute);
            transactionWriteRequest.addConditionCheck(objectToBeConditionChecked, conditionCheckWriteExpression);
            transactionWriteRequest.addDelete(objectToBeDeleted);
            List<Object> responseObjectKeys = Arrays.<Object>asList(objectToBePut,
                                                                    objectToBeUpdated,
                                                                    objectToBeDeleted);
            List<Object> responseObjects = Arrays.<Object>asList(objectToBePut,
                                                                 objectToBeUpdated,
                                                                 null);
            executeAndValidateTransactionWrite(mapperWithoutConfig, transactionWriteRequest, responseObjectKeys, responseObjects);
        } finally {
            deleteTestTable(dynamo, STRING_ATTRIBUTE_SUB_CLASS_TABLE_NAME);
        }
    }

    @Test
    public void testWithAttributeTransformer() throws InterruptedException {
        String overriddenTableName = "sdk-util-" + UUID.randomUUID().toString();
        DynamoDBMapperConfig config = builder().withTableNameOverride(TableNameOverride.withTableNameReplacement(overriddenTableName)).build();
        DynamoDBMapper mapperWithTransformer = new DynamoDBMapper(dynamo, config,
                new AttributeAdder(ADDITIONAL_ATTRIBUTE_NAME, ATTRIBUTE_ADDER_START));
        try {
            createStringHashKeyTable(dynamo, overriddenTableName);

            StringAttributeSubClass objectToBeUpdated = getStringAttributeSubClassObject();

            saveObjects(mapperWithTransformer, objectToBeUpdated);

            Integer objectToBeUpdatedPreviousAttribute = null;

            objectToBeUpdatedPreviousAttribute = validateAdditionalAttributeAndReturnNew(overriddenTableName, objectToBeUpdated,
                    objectToBeUpdatedPreviousAttribute);

            StringAttributeSubClass objectToBePut = getStringAttributeSubClassObject();
            Integer objectToBePutAdditionalAttribute = null;
            TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
            transactionWriteRequest.addPut(objectToBePut);
            String updatedStringAttribute = "updatedStringAttribute";
            objectToBeUpdated.setStringAttribute(updatedStringAttribute);
            transactionWriteRequest.addUpdate(objectToBeUpdated);
            List<Object> responseObjectKeys = Arrays.<Object>asList(objectToBePut,
                    objectToBeUpdated);
            List<Object> responseObjects = Arrays.<Object>asList(objectToBePut,
                    objectToBeUpdated);
            executeAndValidateTransactionWrite(mapperWithTransformer, transactionWriteRequest, responseObjectKeys, responseObjects);

            validateAdditionalAttributeAndReturnNew(overriddenTableName, objectToBeUpdated, objectToBeUpdatedPreviousAttribute);
            validateAdditionalAttributeAndReturnNew(overriddenTableName, objectToBePut, objectToBePutAdditionalAttribute);

        } finally {
            deleteTestTable(dynamo, overriddenTableName);
        }
    }

    private Integer validateAdditionalAttributeAndReturnNew(final String tableName, final StringAttributeSubClass object, Integer previousAttribute) {
        Map<String, AttributeValue> key = new HashMap<String, AttributeValue>();
        key.put("key", new AttributeValue(object.getKey()));
        GetItemResult item = dynamo.getItem(tableName, key);
        assertTrue(item.getItem().containsKey(ADDITIONAL_ATTRIBUTE_NAME));
        Integer currentAttribute = Integer.parseInt(item.getItem().get(ADDITIONAL_ATTRIBUTE_NAME).getN());
        assertNotEquals(currentAttribute, previousAttribute);
        return currentAttribute;
    }

    @Test
    public void testWithObjectTableNameResolver() throws InterruptedException {
        String uuid = UUID.randomUUID().toString();
        final String overriddenSdkUtilTableName = "sdk-util-" + uuid;
        final String overriddenMapperSaveConfigTableName = "mapper-save-config-" + uuid;
        final String sdkHashRangeTestTableName = "sdk-hash-range-test" + uuid;
        DynamoDBMapperConfig config = builder().withObjectTableNameResolver(new ObjectTableNameResolver() {
            @Override
            public String getTableName(Object object, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(object.getClass())) {
                    return overriddenSdkUtilTableName;
                }
                if (TestItem.class.equals(object.getClass())) {
                    return overriddenMapperSaveConfigTableName;
                }
                if (HashKeyRangeKeyClass.class.equals(object.getClass())) {
                    return sdkHashRangeTestTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + object.getClass());
            }
        }).build();

        DynamoDBMapper mapperWithObjectTableNameResolver = new DynamoDBMapper(dynamo, config);

        try {
            createStringHashKeyTable(dynamo, overriddenSdkUtilTableName);
            createSdkMapperSaveConfigTable(dynamo, overriddenMapperSaveConfigTableName);
            createHashKeyRangeKeyTable(dynamo, sdkHashRangeTestTableName);
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithObjectTableNameResolver, transactionWriteTestRequest);
            executeAndValidateTransactionWrite(mapperWithObjectTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
        } finally {
            deleteTestTable(dynamo, overriddenSdkUtilTableName);
            deleteTestTable(dynamo, overriddenMapperSaveConfigTableName);
            deleteTestTable(dynamo, sdkHashRangeTestTableName);
        }
    }

    @Test
    public void testWithTypeConverterFactory() throws InterruptedException {
        DynamoDBTypeConverterFactory typeConverterFactory = DynamoDBTypeConverterFactory.standard().override()
                                                                .with(String.class, CustomBooleanClass.CustomBoolean.class, new DynamoDBTypeConverter<String, CustomBooleanClass.CustomBoolean>() {
                                                                          @Override
                                                                          public String convert(CustomBooleanClass.CustomBoolean bool) {
                                                                              return String.valueOf(bool.getValue());
                                                                          }

                                                                          @Override
                                                                          public CustomBooleanClass.CustomBoolean unconvert(String string) {
                                                                              return new CustomBooleanClass.CustomBoolean(Boolean.valueOf(string));
                                                                          }
                                                                      }
                                                                ).build();
        String overriddenTableName = "custom-boolean-" + UUID.randomUUID().toString();
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTypeConverterFactory(typeConverterFactory)
                                                          .withTableNameOverride(TableNameOverride.withTableNameReplacement(overriddenTableName))
                                                          .build();
        DynamoDBMapper mapperWithTypeConverterFactory = new DynamoDBMapper(dynamo, config);

        try {
            createStringHashKeyTable(dynamo, overriddenTableName);
            CustomBooleanClass objectToBeUpdated = getCustomBooleanClassObject();
            CustomBooleanClass objectToBeConditionChecked = getCustomBooleanClassObject();
            CustomBooleanClass objectToBeDeleted = getCustomBooleanClassObject();
            saveObjects(mapperWithTypeConverterFactory, objectToBeUpdated, objectToBeConditionChecked, objectToBeDeleted);

            StringAttributeClass objectToBePut = getStringAttributeClass();
            TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
            transactionWriteRequest.addPut(objectToBePut);
            objectToBeUpdated.setCustomBooleanAttribute(new CustomBooleanClass.CustomBoolean(false));
            transactionWriteRequest.addUpdate(objectToBeUpdated);
            DynamoDBTransactionWriteExpression conditionCheckWriteExpression = new DynamoDBTransactionWriteExpression();
            conditionCheckWriteExpression.withConditionExpression("attribute_exists(customBooleanAttribute)");
            transactionWriteRequest.addConditionCheck(objectToBeConditionChecked, conditionCheckWriteExpression);
            transactionWriteRequest.addDelete(objectToBeDeleted);

            List<Object> responseObjectKeys = Arrays.<Object>asList(objectToBePut,
                                                                    objectToBeUpdated,
                                                                    objectToBeDeleted);
            List<Object> responseObjects = Arrays.<Object>asList(objectToBePut,
                                                                 objectToBeUpdated,
                                                                 null);
            executeAndValidateTransactionWrite(mapperWithTypeConverterFactory, transactionWriteRequest, responseObjectKeys, responseObjects);
        } finally {
            deleteTestTable(dynamo, overriddenTableName);
        }
    }

    @Test
    public void testWithMissingHashKeyValueButValidRangeKeyValueForPut() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);
            TestItem objectToBePut = getTestItemObject();
            objectToBePut.setHashKey(null);

            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                          objectToBePut,
                                                          0);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("TestItem[hashKey]; null or empty value for primary key", ex.getMessage());
        }
    }

    @Test
    public void testWithValidHashKeyValueButMissingRangeKeyValueForPut() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);
            TestItem objectToBePut = getTestItemObject();
            objectToBePut.setRangeKey(null);

            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                          objectToBePut,
                                                          0);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("TestItem[rangeKey]; null or empty value for primary key", ex.getMessage());
        }
    }

    @Test
    public void testWithMissingHashKeyValueButValidRangeKeyValueForUpdate() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);

            TestItem objectToBeUpdated = getTestItemObject();
            objectToBeUpdated.setHashKey(null);

            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                          objectToBeUpdated,
                                                          3);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("TestItem[hashKey]; null or empty value for primary key", ex.getMessage());
        }
    }

    @Test
    public void testWithValidHashKeyValueButMissingRangeKeyValueForUpdate() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);
            TestItem objectToBeUpdated = getTestItemObject();
            objectToBeUpdated.setRangeKey(null);

            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                          objectToBeUpdated,
                                                          3);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());

            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("TestItem[rangeKey]; null or empty value for primary key", ex.getMessage());
        }
    }

    @Test
    public void testHashKeyDoesntGetAutoGeneratedForConditionCheck() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);
            HashKeyRangeKeyBothAutoGenerated objectToBeConditionChecked = getStringHashAndRangeKeyObjectWithKeys();
            objectToBeConditionChecked.setKey(null);

            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                          objectToBeConditionChecked,
                                                          4);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("HashKeyRangeKeyBothAutoGenerated[key]; no HASH key value present", ex.getMessage());
        }
    }

    @Test
    public void testRangeKeyDoesntGetAutoGeneratedForConditionCheck() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);
            HashKeyRangeKeyBothAutoGenerated objectToBeConditionChecked = getStringHashAndRangeKeyObjectWithKeys();
            objectToBeConditionChecked.setRangeKey(null);

            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                          objectToBeConditionChecked,
                                                          4);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());

            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("HashKeyRangeKeyBothAutoGenerated[rangeKey]; no RANGE key value present", ex.getMessage());
        }
    }


    @Test
    public void testHashKeyDoesntGetAutoGeneratedForDelete() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);
            HashKeyRangeKeyBothAutoGenerated objectToBeDeleted = getStringHashAndRangeKeyObjectWithKeys();
            objectToBeDeleted.setKey(null);

            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                          objectToBeDeleted,
                                                          5);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("HashKeyRangeKeyBothAutoGenerated[key]; no HASH key value present", ex.getMessage());
        }
    }

    @Test
    public void testRangeKeyDoesntGetAutoGeneratedForDelete() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);
            HashKeyRangeKeyBothAutoGenerated objectToBeDeleted = getStringHashAndRangeKeyObjectWithKeys();
            objectToBeDeleted.setRangeKey(null);

            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                          objectToBeDeleted,
                                                          5);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());

            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("HashKeyRangeKeyBothAutoGenerated[rangeKey]; no RANGE key value present", ex.getMessage());
        }
    }

    @Test
    public void testWithAutoGenHashKeyValueAndAutoGenHashAndRangeKeyValueOnTwoItems() {
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);
        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);

        HashKeyAutoGenerated objectToBePut1 = new HashKeyAutoGenerated();
        objectToBePut1.setRangeKey("RangeKeyValue");
        objectToBePut1.setOtherAttribute("NonKeyValue");
        HashKeyRangeKeyBothAutoGenerated objectToBePut2 = getStringHashAndRangeKeyObjectWithKeys();
        objectToBePut2.setKey(null);
        objectToBePut2.setRangeKey(null);

        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                      objectToBePut1,
                                                      0);
        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                      objectToBePut2,
                                                      1);

        List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
        List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
        List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);

        executeAndValidateTransactionWrite(transactionWriteTestData.getTransactionWriteRequest(),
                                           responseObjectKeys,
                                           responseObjects);
    }

    @Test
    public void testWithNonKeyAttributeAutoGeneratedForPut() {
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);
        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);

        PrimaryKeysNotAutogenerated_OtherAttributeAutogenerated objectToBePut = new PrimaryKeysNotAutogenerated_OtherAttributeAutogenerated();
        objectToBePut.setKey(UUID.randomUUID().toString());
        objectToBePut.setRangeKey(UUID.randomUUID().toString());
        objectToBePut.setOtherAttribute(null);

        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                      objectToBePut,
                                                      0);

        List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
        List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
        List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);

        executeAndValidateTransactionWrite(transactionWriteTestData.getTransactionWriteRequest(),
                                           responseObjectKeys,
                                           responseObjects);
    }

    @Test
    public void testWithNonKeyAttributeAutoGeneratedForUpdate() {
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);
        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);

        PrimaryKeysNotAutogenerated_OtherAttributeAutogenerated objectToBeUpdated = new PrimaryKeysNotAutogenerated_OtherAttributeAutogenerated();
        objectToBeUpdated.setKey(UUID.randomUUID().toString());
        objectToBeUpdated.setRangeKey(UUID.randomUUID().toString());
        objectToBeUpdated.setOtherAttribute(null);

        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                      objectToBeUpdated,
                                                      3);

        List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
        List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
        List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);

        executeAndValidateTransactionWrite(transactionWriteTestData.getTransactionWriteRequest(),
                                           responseObjectKeys,
                                           responseObjects);
    }

    @Test
    public void testWithMixedKeyAndNonKeyAttributesAutoGenerated() {
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);
        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);

        HashRangeAndOtherAttributeAutoGen objectToBePut = getHashRangeAutoGenOtherAttributeObject();
        objectToBePut.setDate(null);
        objectToBePut.setRangeKey(null);

        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                      objectToBePut,
                                                      0);

        List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
        List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
        List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);

        executeAndValidateTransactionWrite(transactionWriteTestData.getTransactionWriteRequest(),
                                           responseObjectKeys,
                                           responseObjects);
    }

    @Test
    public void testMultipleOperationsHavingNullValuedAttributes() {

        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);
        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);

        StringAttributeClass objectToBePut = getStringAttributeClass();
        StringAttributeClass objectToBeUpdated = getStringAttributeClass();
        objectToBePut.setStringAttribute(null);
        objectToBeUpdated.setStringAttribute(null);

        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                      objectToBePut,
                                                      0);

        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                      objectToBeUpdated,
                                                      3);

        List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
        List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
        List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);

        executeAndValidateTransactionWrite(transactionWriteTestData.getTransactionWriteRequest(),
                                           responseObjectKeys,
                                           responseObjects);

    }

    private static StringAttributeSubClass getStringAttributeSubClassObject() {
        StringAttributeSubClass obj = new StringAttributeSubClass();
        String uuid = UUID.randomUUID().toString();
        obj.setKey(uuid);
        obj.setRenamedAttribute(uuid + "1");
        obj.setStringAttribute(uuid + "2");
        return obj;
    }
}
