/*
 * Copyright 2010-2019 Amazon.com, Inc. or its affiliates. All Rights
 * Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.amazonaws.services.dynamodbv2.mapper;

import static software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig.TableNameOverride;
import static software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig.TableNameResolver;
import static software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig.ObjectTableNameResolver;
import static com.amazonaws.services.dynamodbv2.pojos.CustomBooleanClass.CustomBoolean;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createAllSupportedAnnotationsTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createMultipleObjectTestDataForTransactionLoad;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkMapperSaveConfigTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkRangeTestTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkStringRangeTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createStringHashKeyTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.deleteTestTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.Existence;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getAllSupportedDataTypesObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getAllSupportedAnnotationsObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getCustomBooleanClassObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getSchemaViolatingTestItemObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getStringAttributeClass;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getStringHashAndRangeKeyObjectWithKeys;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.ObjectSupplier;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.TransactionLoadTestData;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.TransactionLoadTestDataRequest;
import static org.junit.Assert.fail;
import static org.junit.Assert.assertEquals;

import software.amazon.awssdk.mapper.dynamodb.DynamoDBMapper;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBMappingException;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTable;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTypeConverter;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTypeConverterFactory;
import software.amazon.awssdk.mapper.dynamodb.TransactionLoadRequest;
import com.amazonaws.services.dynamodbv2.pojos.AllSupportedAnnotationsClass;
import com.amazonaws.services.dynamodbv2.pojos.AllSupportedDataTypesClass;
import com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException;
import com.amazonaws.services.dynamodbv2.model.TransactionCanceledException;
import com.amazonaws.services.dynamodbv2.pojos.HashKeyRangeKeyBothAutoGenerated;
import com.amazonaws.services.dynamodbv2.pojos.SchemaViolatingTestItem;
import com.amazonaws.services.dynamodbv2.pojos.StringAttributeClass;
import com.amazonaws.services.dynamodbv2.pojos.TestItem;
import com.amazonaws.services.dynamodbv2.pojos.RangeKeyClass;
import org.junit.Test;

import java.util.List;
import java.util.UUID;

public class TransactionLoadMixedTest extends TransactionsTestBase {

    private static final String stringAttributeSubClassTableName = "sdk-util-bfd571e3-2c18-4da6-9c08-487f710802c3";
    private static final String nonExistingTableName = "nonExistingTable-d60c8995-842a-423d-9b88-8c9bde03ef27";

    // TODO: Refactor tableNameResolvers to re-use code between multiple such instances in transactionLoad/transactionWrite integration tests
    private static final TableNameResolver tableNameResolverForMissingKeyTests = new TableNameResolver() {
            @Override
            public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(clazz)) {
                    return sdkUtilTableName;
                }
                if (TestItem.class.equals(clazz)) {
                    return mapperSaveConfigTableName;
                }
                if (RangeKeyClass.class.equals(clazz)) {
                    return sdkRangeTableName;
                }
                if (HashKeyRangeKeyBothAutoGenerated.class.equals(clazz)) {
                    return "sdk-string-keys-" + tableNameSuffix;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
            }
        };
    private static final TableNameResolver tableNameResolverForMissingTableTests = new TableNameResolver() {
            @Override
            public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(clazz)) {
                    return sdkUtilTableName;
                }
                if (TestItem.class.equals(clazz)) {
                    return mapperSaveConfigTableName;
                }
                if (RangeKeyClass.class.equals(clazz)) {
                    return sdkRangeTableName;
                }
                if (NoSuchTableClass.class.equals(clazz) || NonExistingTableTestClass.class.equals(clazz)) {
                    return nonExistingTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
            }
        };
    private static final TableNameResolver tableNameResolverForTransactionCanceledTests = new TableNameResolver() {
            @Override
            public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(clazz)) {
                    return sdkUtilTableName;
                }
                if (TestItem.class.equals(clazz) || SchemaViolatingTestItem.class.equals(clazz)) {
                    return mapperSaveConfigTableName;
                }
                if (RangeKeyClass.class.equals(clazz)) {
                    return sdkRangeTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
            }
        };

    @Test
    public void testWithTableNameOverride() throws InterruptedException {
        String overriddenTableName = "sdk-util-" + UUID.randomUUID().toString();
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameOverride(TableNameOverride.withTableNameReplacement(overriddenTableName))
                                                                    .build();
        DynamoDBMapper mapperWithTableNameOverride = new DynamoDBMapper(dynamo, config);

        try {
            createStringHashKeyTable(dynamo, overriddenTableName);
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(5)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(true);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameOverride, testDataRequest);

            executeAndValidateTransactionLoad(mapperWithTableNameOverride, testData.getTransactionLoadRequest(), testData.getExpectedObjects());
        } finally {
            deleteTestTable(dynamo, overriddenTableName);
        }
    }

    @DynamoDBTable(tableName = stringAttributeSubClassTableName)
    public static class StringAttributeSubClass extends StringAttributeClass {

    }

    // This test is needed because by default TransactionsIntegrationTestBase creates mapper with TableNameResolver
    @Test
    public void testWithoutAnyOverriddenConfig() throws InterruptedException {
        DynamoDBMapper mapperWithoutConfig = new DynamoDBMapper(dynamo);

        try {
            createStringHashKeyTable(dynamo, stringAttributeSubClassTableName);

            ObjectSupplier objectSupplier = new ObjectSupplier() {
                @Override
                public Object get() {
                    return getStringAttributeSubClassObject();
                }
            };
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(5)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(true)
                                                                                                 .withObjectSupplier(objectSupplier);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithoutConfig, testDataRequest);

            executeAndValidateTransactionLoad(mapperWithoutConfig, testData.getTransactionLoadRequest(), testData.getExpectedObjects());
        } finally {
            deleteTestTable(dynamo, stringAttributeSubClassTableName);
        }
    }

    @Test
    public void testWithObjectTableNameResolver() throws InterruptedException {
        String uuid = UUID.randomUUID().toString();
        final String overriddenSdkUtilTableName = "sdk-util-" + uuid;
        final String overriddenMapperSaveConfigTableName = "mapper-save-config-" + uuid;
        final String overriddenSdkRangeTableName = "sdk-range-" + uuid;
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withObjectTableNameResolver(new ObjectTableNameResolver() {
            @Override
            public String getTableName(Object object, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(object.getClass())) {
                    return overriddenSdkUtilTableName;
                }
                if (TestItem.class.equals(object.getClass())) {
                    return overriddenMapperSaveConfigTableName;
                }
                if (RangeKeyClass.class.equals(object.getClass())) {
                    return overriddenSdkRangeTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + object.getClass());
            }
        }).build();
        DynamoDBMapper mapperWithObjectTableNameResolver = new DynamoDBMapper(dynamo, config);

        try {
            createStringHashKeyTable(dynamo, overriddenSdkUtilTableName);
            createSdkMapperSaveConfigTable(dynamo, overriddenMapperSaveConfigTableName);
            createSdkRangeTestTable(dynamo, overriddenSdkRangeTableName);
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(6)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithObjectTableNameResolver, testDataRequest);

            executeAndValidateTransactionLoad(mapperWithObjectTableNameResolver, testData.getTransactionLoadRequest(), testData.getExpectedObjects());
        } finally {
            deleteTestTable(dynamo, overriddenSdkUtilTableName);
            deleteTestTable(dynamo, overriddenMapperSaveConfigTableName);
            deleteTestTable(dynamo, overriddenSdkRangeTableName);
        }
    }

    @Test
    public void testWithTypeConverterFactory() throws InterruptedException {
        DynamoDBTypeConverterFactory typeConverterFactory = DynamoDBTypeConverterFactory.standard().override()
                .with(String.class, CustomBoolean.class, new DynamoDBTypeConverter<String, CustomBoolean>() {
                        @Override
                        public String convert(CustomBoolean bool) {
                            return String.valueOf(bool.getValue());
                        }

                        @Override
                        public CustomBoolean unconvert(String string) {
                            return new CustomBoolean(Boolean.valueOf(string));
                        }
                    }
                ).build();
        String overriddenTableName = "custom-boolean-" + UUID.randomUUID().toString();
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTypeConverterFactory(typeConverterFactory)
                                                                    .withTableNameOverride(TableNameOverride.withTableNameReplacement(overriddenTableName))
                                                                    .build();
        DynamoDBMapper mapperWithTypeConverterFactory = new DynamoDBMapper(dynamo, config);

        try {
            createStringHashKeyTable(dynamo, overriddenTableName);

            ObjectSupplier objectSupplier = new ObjectSupplier() {
                @Override
                public Object get() {
                    return getCustomBooleanClassObject();
                }
            };
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(5)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(true)
                                                                                                 .withObjectSupplier(objectSupplier);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTypeConverterFactory, testDataRequest);

            executeAndValidateTransactionLoad(mapperWithTypeConverterFactory, testData.getTransactionLoadRequest(), testData.getExpectedObjects());
        } finally {
            deleteTestTable(dynamo, overriddenTableName);
        }
    }

    @Test
    public void testWithMissingHashKeyValueButValidRangeKeyValue() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                                    .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(6)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameResolver, testDataRequest);
            HashKeyRangeKeyBothAutoGenerated objWithMissingHashKey = getStringHashAndRangeKeyObjectWithKeys();
            objWithMissingHashKey.setKey(null);
            TransactionLoadRequest transactionLoadRequest = testData.getTransactionLoadRequest();
            transactionLoadRequest.addLoad(objWithMissingHashKey);

            executeAndValidateTransactionLoad(mapperWithTableNameResolver, transactionLoadRequest, testData.getExpectedObjects());
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("HashKeyRangeKeyBothAutoGenerated[key]; no HASH key value present", ex.getMessage());
        }
    }

    @Test
    public void testWithValidHashKeyValueButMissingRangeKeyValue() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingKeyTests)
                                                                    .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(6)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameResolver, testDataRequest);
            HashKeyRangeKeyBothAutoGenerated objWithMissingHashKey = getStringHashAndRangeKeyObjectWithKeys();
            objWithMissingHashKey.setRangeKey(null);
            TransactionLoadRequest transactionLoadRequest = testData.getTransactionLoadRequest();
            transactionLoadRequest.addLoad(objWithMissingHashKey);

            executeAndValidateTransactionLoad(mapperWithTableNameResolver, transactionLoadRequest, testData.getExpectedObjects());
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ex) {
            assertEquals("HashKeyRangeKeyBothAutoGenerated[rangeKey]; no RANGE key value present", ex.getMessage());
        }
    }

    @Test
    public void testWithTableMissingForOneItem() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingTableTests)
                                                                    .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(6)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameResolver, testDataRequest);
            NoSuchTableClass noSuchTableClassObj = new NoSuchTableClass();
            noSuchTableClassObj.setKey("someKey");
            TransactionLoadRequest transactionLoadRequest = testData.getTransactionLoadRequest();
            transactionLoadRequest.addLoad(noSuchTableClassObj);

            executeAndValidateTransactionLoad(mapperWithTableNameResolver, transactionLoadRequest, testData.getExpectedObjects());
            fail("Expected ResourceNotFoundException but no exception thrown");
        } catch (ResourceNotFoundException ex) {
            // No action needed, test passes
        }
    }

    @DynamoDBTable(tableName = nonExistingTableName)
    public static class NonExistingTableTestClass extends StringAttributeClass {

    }

    @Test
    public void testWithTableMissingForMultipleItems() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingTableTests)
                                                                    .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(6)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameResolver, testDataRequest);
            TransactionLoadRequest transactionLoadRequest = testData.getTransactionLoadRequest();
            NoSuchTableClass noSuchTableClassObj = new NoSuchTableClass();
            noSuchTableClassObj.setKey("someKey");
            transactionLoadRequest.addLoad(noSuchTableClassObj);
            transactionLoadRequest.addLoad(getStringAttributeClass());
            NonExistingTableTestClass nonExistingTableTestClassObj = new NonExistingTableTestClass();
            nonExistingTableTestClassObj.setKey("someOtherKey");
            transactionLoadRequest.addLoad(nonExistingTableTestClassObj);

            executeAndValidateTransactionLoad(mapperWithTableNameResolver, transactionLoadRequest, testData.getExpectedObjects());
            fail("Expected ResourceNotFoundException but no exception thrown");
        } catch (ResourceNotFoundException ex) {
            // No action needed, test passes
        }
    }

    @Test
    public void testWithOneItemCausingTransactionCancelled() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForTransactionCanceledTests)
                                                                    .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        int numObjects = 7;
        try {
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(numObjects - 1)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameResolver, testDataRequest);
            TransactionLoadRequest transactionLoadRequest = testData.getTransactionLoadRequest();
            transactionLoadRequest.addLoad(getSchemaViolatingTestItemObject());

            mapperWithTableNameResolver.transactionLoad(transactionLoadRequest);
            fail("Expected TransactionCanceledException but no exception thrown");
        } catch (TransactionCanceledException ex) {
            // Expected
        }
    }

    @Test
    public void testWithMultipleItemsCausingTransactionCancelled() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForTransactionCanceledTests)
                                                                    .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        int numObjects = 9;
        try {
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(numObjects - 3)
                    .withExistence(Existence.SOME)
                    .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameResolver, testDataRequest);
            TransactionLoadRequest transactionLoadRequest = testData.getTransactionLoadRequest();
            transactionLoadRequest.addLoad(getSchemaViolatingTestItemObject());
            transactionLoadRequest.addLoad(getStringAttributeClass());
            transactionLoadRequest.addLoad(getSchemaViolatingTestItemObject());

            mapperWithTableNameResolver.transactionLoad(transactionLoadRequest);
            fail("Expected TransactionCanceledException but no exception thrown");
        } catch (TransactionCanceledException ex) {
            // Expected
        }
    }

    @Test
    public void testWithObjectsHavingAllSupportedDataTypes() throws InterruptedException {
        final String allSupportedTypesTableName = "all-supported-types-" + tableNameSuffix;
        // TODO: Refactor tableNameResolver to re-use code between multiple such instances in transactionLoad/transactionWrite integration tests
        TableNameResolver tableNameResolver = new TableNameResolver() {
            @Override
            public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(clazz)) {
                    return sdkUtilTableName;
                }
                if (TestItem.class.equals(clazz)) {
                    return mapperSaveConfigTableName;
                }
                if (RangeKeyClass.class.equals(clazz)) {
                    return sdkRangeTableName;
                }
                if (AllSupportedDataTypesClass.class.equals(clazz)) {
                    return allSupportedTypesTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
            }
        };
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolver)
                                                                    .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            createSdkStringRangeTable(dynamo, allSupportedTypesTableName);
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(6)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameResolver, testDataRequest);
            TransactionLoadRequest transactionLoadRequest = testData.getTransactionLoadRequest();
            List<Object> expectedObjects = testData.getExpectedObjects();
            // Add an existing AllSupportedDataTypesClass object to transactionLoad
            AllSupportedDataTypesClass allSupportedDataTypesObject1 = getAllSupportedDataTypesObject();
            mapperWithTableNameResolver.save(allSupportedDataTypesObject1);
            transactionLoadRequest.addLoad(allSupportedDataTypesObject1);
            expectedObjects.add(allSupportedDataTypesObject1);
            // Add a non-existing AllSupportedDataTypesClass object to transactionLoad
            AllSupportedDataTypesClass allSupportedDataTypesObject2 = getAllSupportedDataTypesObject();
            transactionLoadRequest.addLoad(allSupportedDataTypesObject2);
            expectedObjects.add(null);

            executeAndValidateTransactionLoad(mapperWithTableNameResolver, transactionLoadRequest, testData.getExpectedObjects());
        } finally {
            deleteTestTable(dynamo, allSupportedTypesTableName);
        }
    }

    @Test
    public void testWithObjectsHavingAllSupportedAnnotations() throws InterruptedException {
        final String allSupportedAnnotationsTableName = "all-supported-annotations-" + tableNameSuffix;
        // TODO: Refactor tableNameResolver to re-use code between multiple such instances in transactionLoad/transactionWrite integration tests
        TableNameResolver tableNameResolver = new TableNameResolver() {
            @Override
            public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(clazz)) {
                    return sdkUtilTableName;
                }
                if (TestItem.class.equals(clazz)) {
                    return mapperSaveConfigTableName;
                }
                if (RangeKeyClass.class.equals(clazz)) {
                    return sdkRangeTableName;
                }
                if (AllSupportedAnnotationsClass.class.equals(clazz)) {
                    return allSupportedAnnotationsTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
            }
        };
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolver)
                                                                    .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            createAllSupportedAnnotationsTable(dynamo, allSupportedAnnotationsTableName);
            TransactionLoadTestDataRequest testDataRequest = new TransactionLoadTestDataRequest().withNumObjects(6)
                                                                                                 .withExistence(Existence.SOME)
                                                                                                 .withUseSameObjectType(false);
            TransactionLoadTestData testData = createMultipleObjectTestDataForTransactionLoad(mapperWithTableNameResolver, testDataRequest);
            TransactionLoadRequest transactionLoadRequest = testData.getTransactionLoadRequest();
            List<Object> expectedObjects = testData.getExpectedObjects();
            // Add an existing AllSupportedAnnotationsClass object to transactionLoad
            AllSupportedAnnotationsClass allSupportedAnnotationsObject1 = getAllSupportedAnnotationsObject();
            mapperWithTableNameResolver.save(allSupportedAnnotationsObject1);
            // Ignored attribute value shouldn't change
            allSupportedAnnotationsObject1.setIgnoredAttribute(AllSupportedAnnotationsClass.IGNORED_ATTRIBUTE_VALUE);
            transactionLoadRequest.addLoad(allSupportedAnnotationsObject1);
            expectedObjects.add(allSupportedAnnotationsObject1);
            // Add a non-existing AllSupportedAnnotationsClass object to transactionLoad
            AllSupportedAnnotationsClass allSupportedAnnotationsObject2 = getAllSupportedAnnotationsObject();
            transactionLoadRequest.addLoad(allSupportedAnnotationsObject2);
            expectedObjects.add(null);

            executeAndValidateTransactionLoad(mapperWithTableNameResolver, transactionLoadRequest, testData.getExpectedObjects());
        } finally {
            deleteTestTable(dynamo, allSupportedAnnotationsTableName);
        }
    }

    private StringAttributeSubClass getStringAttributeSubClassObject() {
        StringAttributeSubClass obj = new StringAttributeSubClass();
        String uuid = UUID.randomUUID().toString();
        obj.setKey(uuid);
        obj.setRenamedAttribute(uuid + "1");
        obj.setStringAttribute(uuid + "2");
        return obj;
    }
}
