/*
 * Copyright 2010-2019 Amazon.com, Inc. or its affiliates. All Rights
 * Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.amazonaws.services.dynamodbv2.mapper;

import static com.amazonaws.services.dynamodbv2.TestObjectCreator.ConditionExpressionMode;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.TransactionWriteTestData;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createAllSupportedAnnotationsTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createMultipleObjectTestDataForTransactionWrite;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkStringRangeTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.deleteTestTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.extractAllObjectsFromTransactionWriteOperations;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.extractExpectedResponseObjects;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.extractObjectKeysForValidResponseSendingOperations;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getAllSupportedAnnotationsObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getAllSupportedDataTypesObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getSlimAttributeNamesClass;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.updateTransactionWriteOperationsWithNewObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.updateTransactionWriteOperationsWithNewObjectAndExpression;
import static com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig.TableNameResolver;
import static com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig.builder;
import static com.amazonaws.services.dynamodbv2.datamodeling.TransactionWriteRequest.TransactionWriteOperation;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.TestObjectCreator;
import com.amazonaws.services.dynamodbv2.TestObjectCreator.TransactionWriteTestRequest;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBQueryExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTransactionWriteExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.PaginatedQueryList;
import com.amazonaws.services.dynamodbv2.datamodeling.TransactionWriteRequest;
import com.amazonaws.services.dynamodbv2.model.AttributeDefinition;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.CreateTableRequest;
import com.amazonaws.services.dynamodbv2.model.GlobalSecondaryIndex;
import com.amazonaws.services.dynamodbv2.model.IdempotentParameterMismatchException;
import com.amazonaws.services.dynamodbv2.model.KeySchemaElement;
import com.amazonaws.services.dynamodbv2.model.KeyType;
import com.amazonaws.services.dynamodbv2.model.Projection;
import com.amazonaws.services.dynamodbv2.model.ProjectionType;
import com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException;
import com.amazonaws.services.dynamodbv2.model.ScalarAttributeType;
import com.amazonaws.services.dynamodbv2.pojos.AllSupportedAnnotationsClass;
import com.amazonaws.services.dynamodbv2.pojos.AllSupportedDataTypesClass;
import com.amazonaws.services.dynamodbv2.pojos.HashKeyRangeKeyClass;
import com.amazonaws.services.dynamodbv2.pojos.PrimaryKeysNotAutogenerated_IndexKeysAutogenerated;
import com.amazonaws.services.dynamodbv2.pojos.SlimAttributeNamesClass;
import com.amazonaws.services.dynamodbv2.pojos.StringAttributeClass;
import com.amazonaws.services.dynamodbv2.pojos.TestItem;
import com.amazonaws.services.dynamodbv2.util.TableUtils;
import org.junit.Test;

public class TransactionWriteMiscellaneousTest extends TransactionsTestBase {
    private static final String tableNameSuffix = UUID.randomUUID().toString();
    private static final String nonExistingTableName = "nonExistingTable-" + tableNameSuffix;
    private static final String sdkStringRangeTableNameWithGsi = "sdk-string-range-" + tableNameSuffix;
    private static final String SDK_STRING_RANGE_TABLE_GSI_NAME = "gsi-with-autogenerated-keys";

    // TODO: Refactor tableNameResolvers to re-use code between multiple such instances in transactionLoad/transactionWrite integration tests
    private static final TableNameResolver tableNameResolverForMissingTableTests = new TableNameResolver() {
        @Override
        public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
            if (StringAttributeClass.class.equals(clazz)) {
                return sdkUtilTableName;
            }
            if (TestItem.class.equals(clazz)) {
                return mapperSaveConfigTableName;
            }
            if (HashKeyRangeKeyClass.class.equals(clazz)) {
                return sdkHashRangeTestTableName;
            }
            if (NoSuchTableClass.class.equals(clazz)) {
                return nonExistingTableName;
            }
            throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
        }
    };

    private static final TableNameResolver tableNameResolverForGsiTest = new TableNameResolver() {
        @Override
        public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
            if (StringAttributeClass.class.equals(clazz)) {
                return sdkUtilTableName;
            }
            if (TestItem.class.equals(clazz)) {
                return mapperSaveConfigTableName;
            }
            if (PrimaryKeysNotAutogenerated_IndexKeysAutogenerated.class.equals(clazz)) {
                return sdkStringRangeTableNameWithGsi;
            }
            if (HashKeyRangeKeyClass.class.equals(clazz)) {
                return sdkHashRangeTestTableName;
            }
            throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
        }
    };

    @Test
    public void testWithTableMissingForOneItem() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingTableTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);

        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);

        NoSuchTableClass objectToBePut = new NoSuchTableClass();
        objectToBePut.setKey("somekey");

        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations,
                                                      objectToBePut,
                                                      1);

        try {
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
            fail("Expected ResourceNotFoundException but no exception thrown");
        } catch (ResourceNotFoundException e) {
            // Pass
        }
    }

    @Test
    public void testWithTableMissingForMultipleItems() {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForMissingTableTests)
                                                          .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);

        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);

        NoSuchTableClass objectToBePut = new NoSuchTableClass();
        objectToBePut.setKey("somekey");
        NoSuchTableClass objectToBeUpdated = new NoSuchTableClass();
        objectToBeUpdated.setKey("somekey");
        objectToBeUpdated.setOtherAttribute("someAttribute");
        NoSuchTableClass objectToBeConditionChecked = new NoSuchTableClass();
        objectToBeConditionChecked.setKey("somekey");
        NoSuchTableClass objectToBeDeleted = new NoSuchTableClass();
        objectToBeDeleted.setKey("somekey");

        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();

        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBePut, 0);
        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeUpdated, 2);
        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeConditionChecked, 4);
        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeDeleted, 5);

        try {
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
            fail("Expected ResourceNotFoundException but no exception thrown");
        } catch (ResourceNotFoundException e) {
            // Pass
        }
    }

    @Test
    public void testWithSameIdempotencyToken() {
        String idempotencyToken = UUID.randomUUID().toString();

        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);
        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);
        transactionWriteTestData.getTransactionWriteRequest().withIdempotencyToken(idempotencyToken);
        for (int i = 0; i < 10; i++) {
            executeAndValidateTransactionWrite(transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
        }
    }

    @Test
    public void testWithSameIdempotencyTokenOnDifferentRequest() {
        String idempotencyToken = UUID.randomUUID().toString();
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);
        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);
        SlimAttributeNamesClass objectToBeUpdated1 = getSlimAttributeNamesClass();
        objectToBeUpdated1.setC("UpdatedString1");
        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeUpdated1, 3);
        List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
        List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
        List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);
        transactionWriteTestData.getTransactionWriteRequest().withIdempotencyToken(idempotencyToken);
        executeAndValidateTransactionWrite(transactionWriteTestData.getTransactionWriteRequest(),
                                           responseObjectKeys,
                                           responseObjects);
        objectToBeUpdated1 = getSlimAttributeNamesClass();
        objectToBeUpdated1.setC("UpdatedString11");
        transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeUpdated1, 3);
        try {
            executeAndValidateTransactionWrite(transactionWriteTestData.getTransactionWriteRequest(),
                                               responseObjectKeys,
                                               responseObjects);
            fail("Expected IdempotentParameterMismatchException but no exception thrown");
        } catch (IdempotentParameterMismatchException ipme) {
            // Pass
        }
    }

    @Test
    public void testWithDifferentIdempotencyTokenOnSameRequest() {
        String baseIdempotencyToken = UUID.randomUUID().toString();
        String idempotencyToken1 = baseIdempotencyToken.substring(0, 35) + "1";
        String idempotencyToken2 = baseIdempotencyToken.substring(0, 35) + "2";
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);
        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);
        TransactionWriteRequest transactionWriteRequest = transactionWriteTestData.getTransactionWriteRequest();
        transactionWriteTestData.getTransactionWriteRequest().withIdempotencyToken(idempotencyToken1);
        executeAndValidateTransactionWrite(transactionWriteRequest,
                                           transactionWriteTestData.getExpectedObjectKeys(),
                                           transactionWriteTestData.getExpectedObjects());
        transactionWriteTestData.getTransactionWriteRequest().withIdempotencyToken(idempotencyToken2);
        executeAndValidateTransactionWrite(transactionWriteRequest,
                                           transactionWriteTestData.getExpectedObjectKeys(),
                                           transactionWriteTestData.getExpectedObjects());

    }

    @Test
    public void testWithItemsHavingAllSupportedDataTypes() throws InterruptedException {
        final String allSupportedTypesTableName = "all-supported-types-" + tableNameSuffix;
        // TODO: Refactor tableNameResolver to re-use code between multiple such instances in transactionLoad/transactionWrite integration tests
        TableNameResolver tableNameResolver = new TableNameResolver() {
            @Override
            public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(clazz)) {
                    return sdkUtilTableName;
                }
                if (TestItem.class.equals(clazz)) {
                    return mapperSaveConfigTableName;
                }
                if (HashKeyRangeKeyClass.class.equals(clazz)) {
                    return sdkHashRangeTestTableName;
                }
                if (AllSupportedDataTypesClass.class.equals(clazz)) {
                    return allSupportedTypesTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
            }
        };
        DynamoDBMapperConfig config = builder().withTableNameResolver(tableNameResolver)
                                               .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            createSdkStringRangeTable(dynamo, allSupportedTypesTableName);

            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);

            AllSupportedDataTypesClass objectToBePut = getAllSupportedDataTypesObject();
            AllSupportedDataTypesClass objectToBeUpdated = getAllSupportedDataTypesObject();
            AllSupportedDataTypesClass objectToBeDeleted = getAllSupportedDataTypesObject();
            saveObjects(mapperWithTableNameResolver, objectToBePut, objectToBeUpdated, objectToBeDeleted);
            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBePut, 0);
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeUpdated, 2);
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeDeleted, 4);
            List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
            List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
            List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               responseObjectKeys,
                                               responseObjects);
        } finally {
            deleteTestTable(dynamo, allSupportedTypesTableName);
        }
    }

    @Test
    public void testWithItemsHavingAllSupportedAnnotations() throws InterruptedException {
        final String allSupportedAnnotationsTableName = "all-supported-annotations-" + tableNameSuffix;
        // TODO: Refactor tableNameResolver to re-use code between multiple such instances in transactionLoad/transactionWrite integration tests
        TableNameResolver tableNameResolver = new TableNameResolver() {
            @Override
            public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(clazz)) {
                    return sdkUtilTableName;
                }
                if (TestItem.class.equals(clazz)) {
                    return mapperSaveConfigTableName;
                }
                if (HashKeyRangeKeyClass.class.equals(clazz)) {
                    return sdkHashRangeTestTableName;
                }
                if (AllSupportedAnnotationsClass.class.equals(clazz)) {
                    return allSupportedAnnotationsTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
            }
        };
        DynamoDBMapperConfig config = builder().withTableNameResolver(tableNameResolver)
                                               .build();
        DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
        try {
            createAllSupportedAnnotationsTable(dynamo, allSupportedAnnotationsTableName);
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);
            AllSupportedAnnotationsClass objectToBePut = getAllSupportedAnnotationsObject();
            AllSupportedAnnotationsClass objectToBeUpdated = getAllSupportedAnnotationsObject();
            saveObjects(mapperWithTableNameResolver, objectToBePut, objectToBeUpdated);
            // Update the IgnoredAttribute value to assert against them later
            objectToBePut.setIgnoredAttribute("IgnoredPutValue");
            objectToBeUpdated.setIgnoredAttribute("IgnoredUpdateValue");
            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBePut, 0);
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeUpdated, 3);
            List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
            List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
            List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);
            // Ignored attribute value shouldn't change
            objectToBePut.setIgnoredAttribute(AllSupportedAnnotationsClass.IGNORED_ATTRIBUTE_VALUE);
            objectToBeUpdated.setIgnoredAttribute(AllSupportedAnnotationsClass.IGNORED_ATTRIBUTE_VALUE);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               responseObjectKeys,
                                               responseObjects);
        } finally {
            deleteTestTable(dynamo, allSupportedAnnotationsTableName);
        }
    }

    @Test
    public void testSanityOfGsiWhenUsingTransactions() throws InterruptedException {
        try {
            createGsiTestTable(dynamo, sdkStringRangeTableNameWithGsi);
            DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolverForGsiTest)
                                                              .build();
            DynamoDBMapper mapperWithTableNameResolver = new DynamoDBMapper(dynamo, config);
            TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                              .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                              .withIsMultiTable(true);
            TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(mapperWithTableNameResolver, transactionWriteTestRequest);
            PrimaryKeysNotAutogenerated_IndexKeysAutogenerated objectToBePut = new PrimaryKeysNotAutogenerated_IndexKeysAutogenerated();
            String baseKey = UUID.randomUUID().toString();
            String hashKey = baseKey + "hash";
            String rangeKey = baseKey + "range";
            objectToBePut.setKey(hashKey);
            objectToBePut.setRangeKey(rangeKey);
            List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
            updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBePut, 0);
            List<Object> allExistingObjects = extractAllObjectsFromTransactionWriteOperations(transactionWriteOperations);
            List<Object> responseObjectKeys = extractObjectKeysForValidResponseSendingOperations(allExistingObjects);
            List<Object> responseObjects = extractExpectedResponseObjects(allExistingObjects);
            executeAndValidateTransactionWrite(mapperWithTableNameResolver,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               responseObjectKeys,
                                               responseObjects);
            // Verify GSI based query returns the actual item written transactionally
            final DynamoDBQueryExpression<PrimaryKeysNotAutogenerated_IndexKeysAutogenerated> queryExpression =
                    new DynamoDBQueryExpression<PrimaryKeysNotAutogenerated_IndexKeysAutogenerated>();
            queryExpression.setHashKeyValues(objectToBePut);
            queryExpression.setIndexName(SDK_STRING_RANGE_TABLE_GSI_NAME);
            queryExpression.setConsistentRead(false); // GSI supports only eventually consistent reads

            // Wait for up to one minute for a GSI query to return expected item because GSI query is eventually consistent.
            long endTime = System.currentTimeMillis() + 60 * 1000;
            PaginatedQueryList<PrimaryKeysNotAutogenerated_IndexKeysAutogenerated> results = null;
            while (System.currentTimeMillis() < endTime) {
                results = mapperWithTableNameResolver.query(PrimaryKeysNotAutogenerated_IndexKeysAutogenerated.class, queryExpression);
                if (results.size() == 1) {
                    break;
                }
                Thread.sleep(1000);
            }
            assertEquals(1, results.size());
            assertEquals(objectToBePut, results.get(0));
        } finally {
            deleteTestTable(dynamo, sdkStringRangeTableNameWithGsi);
        }
    }

    @Test
    public void testUpdatesThatFailWithTokenCollision() {
        TransactionWriteTestRequest transactionWriteTestRequest = new TransactionWriteTestRequest()
                                                                          .withPutConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withUpdateConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withDeleteConditionExpressionMode(ConditionExpressionMode.NONE)
                                                                          .withIsMultiTable(true);

        TransactionWriteTestData transactionWriteTestData = createMultipleObjectTestDataForTransactionWrite(dynamoMapper, transactionWriteTestRequest);
        SlimAttributeNamesClass objectToBeUpdated1 = getSlimAttributeNamesClass();
        SlimAttributeNamesClass objectToBeUpdated2 = getSlimAttributeNamesClass();
        SlimAttributeNamesClass objectToBeUpdated3 = getSlimAttributeNamesClass();
        objectToBeUpdated1.setC("UpdatedString1");
        List<TransactionWriteOperation> transactionWriteOperations = transactionWriteTestData.getTransactionWriteRequest().getTransactionWriteOperations();
        DynamoDBTransactionWriteExpression writeExpression1 = new DynamoDBTransactionWriteExpression();
        writeExpression1.withConditionExpression("(#14b10 IN (:attr1, :attr2)) AND (#14b102850 IN (:attr1, :attr2))");
        Map<String, String> attributeNameMap = new HashMap<String, String>();
        attributeNameMap.put("#14b10", "C");
        attributeNameMap.put("#14b102850", "C");
        Map<String, AttributeValue> attributeValueMap = new HashMap<String, AttributeValue>();
        attributeValueMap.put(":attr1", new AttributeValue(objectToBeUpdated1.getC()));
        attributeValueMap.put(":attr2", new AttributeValue("randomString"));
        writeExpression1.withExpressionAttributeValues(attributeValueMap);
        writeExpression1.withExpressionAttributeNames(attributeNameMap);
        updateTransactionWriteOperationsWithNewObjectAndExpression(transactionWriteOperations, objectToBeUpdated1, writeExpression1, 3);
        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeUpdated2, 4);
        updateTransactionWriteOperationsWithNewObject(transactionWriteOperations, objectToBeUpdated3, 5);
        try {
            executeAndValidateTransactionWrite(dynamoMapper,
                                               transactionWriteTestData.getTransactionWriteRequest(),
                                               transactionWriteTestData.getExpectedObjectKeys(),
                                               transactionWriteTestData.getExpectedObjects());
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException dme) {
            assertEquals("Failed to process update operation inside transactionWrite request due to conflict with expressionAttributeName " +
                                 "or expressionAttributeValue token name: 14b102850. Please replace this token name with a different token name.",
                         dme.getMessage());
        }
    }

    private static void createGsiTestTable(AmazonDynamoDB dynamo, String tableName) throws InterruptedException {
        CreateTableRequest createTableRequest = new CreateTableRequest()
                                                        .withTableName(tableName)
                                                        .withKeySchema(new KeySchemaElement("key", KeyType.HASH),
                                                                       new KeySchemaElement("rangeKey", KeyType.RANGE))
                                                        .withGlobalSecondaryIndexes(new GlobalSecondaryIndex()
                                                                                            .withIndexName(SDK_STRING_RANGE_TABLE_GSI_NAME)
                                                                                            .withKeySchema(
                                                                                                    new KeySchemaElement("gis-hash-key", KeyType.HASH),
                                                                                                    new KeySchemaElement("gis-range-key", KeyType.RANGE))
                                                                                            .withProjection(
                                                                                                    new Projection()
                                                                                                            .withProjectionType(ProjectionType.ALL))
                                                                                            .withProvisionedThroughput(TestObjectCreator.DEFAULT_PROVISIONED_THROUGHPUT))
                                                        .withAttributeDefinitions(new AttributeDefinition("key", ScalarAttributeType.S),
                                                                                  new AttributeDefinition("rangeKey", ScalarAttributeType.S),
                                                                                  new AttributeDefinition("gis-hash-key", ScalarAttributeType.S),
                                                                                  new AttributeDefinition("gis-range-key", ScalarAttributeType.S))
                                                        .withProvisionedThroughput(TestObjectCreator.DEFAULT_PROVISIONED_THROUGHPUT);
        if (TableUtils.createTableIfNotExists(dynamo, createTableRequest)) {
            TableUtils.waitUntilActive(dynamo, tableName);
        }
    }
}
