/*
 * Copyright 2010-2019 Amazon.com, Inc. or its affiliates. All Rights
 * Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.amazonaws.services.dynamodbv2.datamodeling;

import static com.amazonaws.services.dynamodbv2.TestObjectCreator.DEFAULT_PROVISIONED_THROUGHPUT;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkDocAttributeTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkMapperSaveConfigTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkRangeTestTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createSdkStringRangeTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createStringHashKeyTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.createTestTable;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getMultiTableObjects;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getMultiVersionRangeKeyObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getStringAttributeClass;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getTestItemObject;
import static com.amazonaws.services.dynamodbv2.TestObjectCreator.getUniqueRangeKeyObject;
import static junit.framework.TestCase.fail;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import com.amazonaws.SdkClientException;
import com.amazonaws.services.dynamodbv2.mapper.NoSuchTableClass;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.GetItemResult;
import com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException;
import com.amazonaws.services.dynamodbv2.model.ReturnValuesOnConditionCheckFailure;
import com.amazonaws.services.dynamodbv2.model.ScalarAttributeType;
import com.amazonaws.services.dynamodbv2.model.TransactionCanceledException;
import com.amazonaws.services.dynamodbv2.pojos.HashKeyRangeKeyBothAutoGenerated;
import com.amazonaws.services.dynamodbv2.pojos.MultiVersionRangeKeyClass;
import com.amazonaws.services.dynamodbv2.pojos.PrimaryKeysNotAutogenerated_IndexKeysAutogenerated;
import com.amazonaws.services.dynamodbv2.pojos.RangeKeyClass;
import com.amazonaws.services.dynamodbv2.pojos.StringAttributeClass;
import com.amazonaws.services.dynamodbv2.pojos.TestDocClass;
import com.amazonaws.services.dynamodbv2.pojos.TestItem;
import com.amazonaws.services.dynamodbv2.utils.AttributeAdder;
import com.amazonaws.services.dynamodbv2.utils.NullAttributeAdder;
import org.junit.BeforeClass;
import org.junit.Test;

import static com.amazonaws.services.dynamodbv2.pojos.TestDocClass.ChildClass;
import static org.junit.Assert.assertTrue;

public class TransactionWriteUnitTest extends TransactionsUnitTestBase {

    // Some arbitrary big integer
    private static final int ATTRIBUTE_ADDER_START = 12345678;
    private static final String ADDITIONAL_ATTRIBUTE_NAME = "extra_attribute";
    private static final String VERSION_CONDITION_CONFLICT_ERROR_MESSAGE =
            "A transactional write operation may not also specify a condition " +
                    "expression if a versioned attribute is present on the " +
                    "model of the item.";

    @BeforeClass
    public static void setUpTests() throws InterruptedException {
        setUp();
        dynamoMapper = new DynamoDBMapper(dynamoDB);
        createSdkMapperSaveConfigTable(dynamoDB);
        createSdkRangeTestTable(dynamoDB);
        createStringHashKeyTable(dynamoDB);
        createSdkStringRangeTable(dynamoDB);
        createSdkDocAttributeTable(dynamoDB);
    }

    @Test
    public void testTransactionWriteEmptyRequest() {
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected SdkClientException but no exception thrown");
        } catch (SdkClientException sce) {
            // Pass
        }
    }

    @Test
    public void testTransactionWriteSingleItemTest() {
        StringAttributeClass obj = getStringAttributeClass();
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);

        // Put one object
        executeTransactWriteAndVerify(transactionWriteRequest, obj, obj);

        // Update the object
        String updatedStringAttribute = "updatedStringAttribute";
        transactionWriteRequest = new TransactionWriteRequest();
        obj.setStringAttribute(updatedStringAttribute);
        transactionWriteRequest.addUpdate(obj);
        dynamoMapper.transactionWrite(transactionWriteRequest);
        executeTransactWriteAndVerify(transactionWriteRequest, obj, obj);

        // ConditionCheck the object
        transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = generateStringMatcherTransactWriteExpression(updatedStringAttribute,
                                                                                                          "not" + updatedStringAttribute);
        transactionWriteRequest.addConditionCheck(obj, writeExpression);
        //   Succeeds
        dynamoMapper.transactionWrite(transactionWriteRequest);
        //   Fails, assert on old returned values in exception
        transactionWriteRequest = new TransactionWriteRequest();
        writeExpression = generateStringMatcherTransactWriteExpression("not1" + updatedStringAttribute,
                                                                       "not2" + updatedStringAttribute);
        Map<String, AttributeValue> expectedResponseValueMap = new HashMap<String, AttributeValue>();
        expectedResponseValueMap.put("originalName", new AttributeValue(obj.getRenamedAttribute()));
        expectedResponseValueMap.put("key", new AttributeValue(obj.getKey()));
        expectedResponseValueMap.put("stringAttribute", new AttributeValue(obj.getStringAttribute()));
        transactionWriteRequest.addConditionCheck(obj, writeExpression, ReturnValuesOnConditionCheckFailure.ALL_OLD);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected TransactionCanceledException but no exception thrown");
        } catch (TransactionCanceledException tce) {
            // Expected
        }

        // Delete
        transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addDelete(obj);
        executeTransactWriteAndVerify(transactionWriteRequest, obj, null);
    }

    @Test
    public void testTransactionWriteForOverriddenConfigWritesIntoOverriddenTable() throws InterruptedException {
        String overriddenTableName = "overriddenTableName";
        String stringInOverriddenTable = "StringAttributeOnOverriddenTable";
        createTestTable(dynamoDB, DEFAULT_PROVISIONED_THROUGHPUT,
                        overriddenTableName,
                        "key" /* hashKeyName */,
                        ScalarAttributeType.S,
                        null /* rangeKeyName */,
                        null /* rangeKeyAttributeType */);
        StringAttributeClass obj = getStringAttributeClass();
        String stringInOriginalTable = obj.getStringAttribute();

        // Saving a value with original table
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        dynamoMapper.transactionWrite(transactionWriteRequest);

        // Saving an overridden value with overridden tableName
        DynamoDBMapperConfig.TableNameOverride tableNameOverride = new DynamoDBMapperConfig.TableNameOverride(overriddenTableName);
        obj.setStringAttribute(stringInOverriddenTable);
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder()
                                                          .withTableNameOverride(tableNameOverride)
                                                          .build();
        transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        dynamoMapper.transactionWrite(transactionWriteRequest, config);

        // Query overridden table to see overridden string attribute
        TransactionLoadRequest transactionLoadRequest = new TransactionLoadRequest();
        transactionLoadRequest.addLoad(obj);
        List<Object> responseObjectList = transactionLoadObjects(transactionLoadRequest, config);
        assertEquals(1, responseObjectList.size());
        StringAttributeClass stringAttributeClassObject = (StringAttributeClass) responseObjectList.get(0);
        assertEquals(stringInOverriddenTable, stringAttributeClassObject.getStringAttribute());

        // Query original table to see original string attribute
        transactionLoadRequest = new TransactionLoadRequest();
        transactionLoadRequest.addLoad(obj);
        responseObjectList = transactionLoadObjects(transactionLoadRequest);
        assertEquals(1, responseObjectList.size());
        stringAttributeClassObject = (StringAttributeClass) responseObjectList.get(0);
        assertEquals(stringInOriginalTable, stringAttributeClassObject.getStringAttribute());
    }

    @Test
    public void testPutsViaTransactionForMultipleItemsOnMultipleTablesSucceeds() {
        final int numItems = 10;
        List<Object> objs = getMultiTableObjects(numItems);
        TransactionLoadRequest transactionLoadRequest = new TransactionLoadRequest();
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        for (Object obj : objs) {
            transactionWriteRequest.addPut(obj);
            transactionLoadRequest.addLoad(obj);
        }
        dynamoMapper.transactionWrite(transactionWriteRequest);
        List<Object> responseObjectList = transactionLoadObjects(transactionLoadRequest);

        for (int i = 0; i < numItems; i++) {
            // Ensure that request and response objects are in the same order as this is a transactionLoad request
            assertEquals(objs.get(i), responseObjectList.get(i));
        }
    }

    @Test
    public void testTransactionWriteForAutoGeneratedKeysSucceeds() {
        HashKeyRangeKeyBothAutoGenerated obj = new HashKeyRangeKeyBothAutoGenerated();
        obj.setOtherAttribute("someAttributeValue");
        assertNull(obj.getKey());
        assertNull(obj.getRangeKey());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        executeTransactWriteAndVerify(transactionWriteRequest, obj, obj);
        // Check in-memory value
        assertNotNull(obj.getKey());
        assertNotNull(obj.getRangeKey());
    }

    @Test
    public void testTransactionWriteForAutoGenerateIndexKeysSucceeds() {
        PrimaryKeysNotAutogenerated_IndexKeysAutogenerated obj = new PrimaryKeysNotAutogenerated_IndexKeysAutogenerated();

        String randomPrimaryKeyValue = UUID.randomUUID().toString();
        obj.setKey(randomPrimaryKeyValue);
        obj.setRangeKey(randomPrimaryKeyValue);

        assertNull(obj.getGsiHashKey());
        assertNull(obj.getGsiRangeKey());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        executeTransactWriteAndVerify(transactionWriteRequest, obj, obj);
        // check in-memory value
        assertNotNull(obj.getGsiHashKey());
        assertNotNull(obj.getGsiRangeKey());
    }

    @Test
    public void testTransactionWriteForAutoGenerateKeysFails() {
        PrimaryKeysNotAutogenerated_IndexKeysAutogenerated obj = new PrimaryKeysNotAutogenerated_IndexKeysAutogenerated();
        assertNull(obj.getGsiHashKey());
        assertNull(obj.getGsiRangeKey());

        // Setting rangeKey to non-null value makes this test deterministic, otherwise the exception message assert makes this test flaky because
        // hash key would get validated first is NOT guaranteed
        obj.setRangeKey("someRangeKey");

        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected DynamoDBMappingException but no exception thrown");
        } catch (DynamoDBMappingException ase) {
            assertEquals("PrimaryKeysNotAutogenerated_IndexKeysAutogenerated[key]; null or empty value for primary key", ase.getMessage());
        }
        // Ensure in-memory values are not updated on failed call
        assertNull(obj.getGsiHashKey());
        assertNull(obj.getGsiRangeKey());
    }

    @Test
    public void testTransactionWriteForVersionedAttributeWithConditionExpressionFails() {
        RangeKeyClass obj = getUniqueRangeKeyObject();
        DynamoDBMapperTableModel<RangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<RangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        writeExpression.withConditionExpression("SomeConditionExpression");
        transactionWriteRequest.addPut(obj, writeExpression);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected SdkClientException but no exception thrown");
        } catch (SdkClientException se) {
            assertEquals(se.getMessage(), VERSION_CONDITION_CONFLICT_ERROR_MESSAGE);
        }
    }

    @Test
    public void testTransactionWriteForNullVersionAttributeSucceeds() {
        RangeKeyClass obj = getUniqueRangeKeyObject();
        DynamoDBMapperTableModel<RangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<RangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        assertEquals(null, obj.getVersion());
        transactionWriteRequest.addPut(obj);
        dynamoMapper.transactionWrite(transactionWriteRequest);
        // Verify that table is updated with proper version
        assertEquals(Long.valueOf(1L), dynamoMapper.load(obj).getVersion());
        // Verify that in-memory copy is updated with proper version
        assertEquals(Long.valueOf(1L), obj.getVersion());
    }

    @Test
    public void testTransactionWriteForNonNullVersionAttributeSucceeds() {
        RangeKeyClass obj = getUniqueRangeKeyObject();
        DynamoDBMapperTableModel<RangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<RangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        assertEquals(null, obj.getVersion());
        dynamoMapper.save(obj);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        dynamoMapper.transactionWrite(transactionWriteRequest);
        // Verify that table is updated with proper version
        assertEquals(Long.valueOf(2L), dynamoMapper.load(obj).getVersion());
        // Verify that in-memory copy is updated with proper version
        assertEquals(Long.valueOf(2L), obj.getVersion());
    }

    @Test
    public void testTransactionWriteForHigherVersionAttributeFails() {
        RangeKeyClass obj = getUniqueRangeKeyObject();
        DynamoDBMapperTableModel<RangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<RangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        dynamoMapper.save(obj);
        assertEquals(Long.valueOf(1L), obj.getVersion());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        obj.setVersion(3L);
        transactionWriteRequest.addPut(obj);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected TransactionCanceledException but no exception thrown");
        } catch (TransactionCanceledException tce) {
            // Expected
        }
    }

    @Test
    public void testTransactionWriteForLowerVersionAttributeFails() {
        RangeKeyClass obj = getUniqueRangeKeyObject();
        DynamoDBMapperTableModel<RangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<RangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        dynamoMapper.save(obj);
        assertEquals(Long.valueOf(1L), obj.getVersion());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        obj.setVersion(0L);
        transactionWriteRequest.addPut(obj);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected TransactionCanceledException but no exception thrown");
        } catch (TransactionCanceledException tce) {
            // Expected
        }
    }

    @Test
    public void testTransactionWriteForNullVersionAttributeFailsIfVersionIsPresentInRecord() {
        RangeKeyClass obj = getUniqueRangeKeyObject();
        DynamoDBMapperTableModel<RangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<RangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        dynamoMapper.save(obj);
        assertEquals(Long.valueOf(1L), obj.getVersion());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        obj.setVersion(null);
        transactionWriteRequest.addPut(obj);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected TransactionCanceledException but no exception thrown");
        } catch (TransactionCanceledException tce) {
            // Expected
        }
    }

    @Test
    public void testMultiItemTransactionWriteWithVersionAttributeSucceeds() {
        RangeKeyClass putObj = getUniqueRangeKeyObject();
        RangeKeyClass updateObj = getUniqueRangeKeyObject();
        RangeKeyClass deleteObj = getUniqueRangeKeyObject();
        dynamoMapper.save(putObj);
        dynamoMapper.save(updateObj);
        dynamoMapper.save(deleteObj);
        assertEquals(Long.valueOf(1L), putObj.getVersion());
        assertEquals(Long.valueOf(1L), updateObj.getVersion());
        assertEquals(Long.valueOf(1L), deleteObj.getVersion());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(putObj);
        transactionWriteRequest.addUpdate(updateObj);
        transactionWriteRequest.addDelete(deleteObj);
        dynamoMapper.transactionWrite(transactionWriteRequest);
        // Verify that table is updated with proper version
        assertEquals(Long.valueOf(2L), dynamoMapper.load(putObj).getVersion());
        assertEquals(Long.valueOf(2L), dynamoMapper.load(updateObj).getVersion());
        assertEquals(null, dynamoMapper.load(deleteObj));
    }

    @Test
    public void testMultiItemTransactionWriteWithVersionAttributeAndConditionExpressionFails() {
        RangeKeyClass putObj = getUniqueRangeKeyObject();
        RangeKeyClass updateObj = getUniqueRangeKeyObject();
        RangeKeyClass conditionCheckObj = getUniqueRangeKeyObject();
        RangeKeyClass deleteObj = getUniqueRangeKeyObject();
        dynamoMapper.save(putObj);
        dynamoMapper.save(updateObj);
        dynamoMapper.save(conditionCheckObj);
        dynamoMapper.save(deleteObj);
        assertEquals(Long.valueOf(1L), putObj.getVersion());
        assertEquals(Long.valueOf(1L), updateObj.getVersion());
        assertEquals(Long.valueOf(1L), conditionCheckObj.getVersion());
        assertEquals(Long.valueOf(1L), deleteObj.getVersion());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        writeExpression.withConditionExpression("SomeConditionExpression");
        transactionWriteRequest.addPut(putObj, writeExpression);
        transactionWriteRequest.addUpdate(updateObj, writeExpression);
        transactionWriteRequest.addUpdate(conditionCheckObj, writeExpression);
        transactionWriteRequest.addDelete(deleteObj, writeExpression);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected SdkClientException but no exception thrown");
        } catch (SdkClientException se) {
            assertEquals(se.getMessage(), VERSION_CONDITION_CONFLICT_ERROR_MESSAGE);
        }
    }

    @Test
    public void testTransactionWriteWithNullValuedMultiVersionAttributeItemSucceeds() {
        MultiVersionRangeKeyClass obj = getMultiVersionRangeKeyObject();
        DynamoDBMapperTableModel<MultiVersionRangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<MultiVersionRangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        assertEquals(null, obj.getVersion());
        assertEquals(null, obj.getVersion2());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        dynamoMapper.transactionWrite(transactionWriteRequest);
        // Verify that table is updated with proper version
        assertEquals(Long.valueOf(1L), dynamoMapper.load(obj).getVersion());
        assertEquals(Long.valueOf(1L), dynamoMapper.load(obj).getVersion2());
        // Verify that in-memory copy is updated with proper version
        assertEquals(Long.valueOf(1L), obj.getVersion());
        assertEquals(Long.valueOf(1L), obj.getVersion2());
    }

    @Test
    public void testTransactionWriteWithLowerValuedMultiVersionAttributeItemFails() {
        MultiVersionRangeKeyClass obj = getMultiVersionRangeKeyObject();
        DynamoDBMapperTableModel<MultiVersionRangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<MultiVersionRangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        assertEquals(null, obj.getVersion());
        assertEquals(null, obj.getVersion2());
        dynamoMapper.save(obj);
        obj.setVersion2(0L);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected TransactionCanceledException but no exception thrown");
        } catch (TransactionCanceledException tce) {
            // Expected
        }
    }

    @Test
    public void testTransactionWriteWithNonNullValuedMultiVersionAttributeItemSucceeds() {
        MultiVersionRangeKeyClass obj = getMultiVersionRangeKeyObject();
        DynamoDBMapperTableModel<MultiVersionRangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<MultiVersionRangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        assertEquals(null, obj.getVersion());
        assertEquals(null, obj.getVersion2());
        dynamoMapper.save(obj);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        dynamoMapper.transactionWrite(transactionWriteRequest);
        // Verify that table is updated with proper version
        assertEquals(Long.valueOf(2L), dynamoMapper.load(obj).getVersion());
        assertEquals(Long.valueOf(2L), dynamoMapper.load(obj).getVersion2());
        // Verify that in-memory copy is updated with proper version
        assertEquals(Long.valueOf(2L), obj.getVersion());
        assertEquals(Long.valueOf(2L), obj.getVersion2());
    }

    @Test
    public void testTransactionWriteWithMultiVersionAttributeItemAndConditionExpressionFails() {
        MultiVersionRangeKeyClass obj = getMultiVersionRangeKeyObject();
        DynamoDBMapperTableModel<MultiVersionRangeKeyClass> model = getTable(obj);
        DynamoDBMapperFieldModel<MultiVersionRangeKeyClass,Object> val = model.field("version");
        assertEquals(true, val.versioned());
        assertEquals(null, obj.getVersion());
        assertEquals(null, obj.getVersion2());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        writeExpression.withConditionExpression("SomeConditionExpression");
        transactionWriteRequest.addPut(obj, writeExpression);
        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected SdkClientException but no exception thrown");
        } catch (SdkClientException se) {
            assertEquals(se.getMessage(), VERSION_CONDITION_CONFLICT_ERROR_MESSAGE);
        }
    }

    @Test
    public void testTransactionWriteWithIdempotencyTokenSucceeds() {
        StringAttributeClass obj = getStringAttributeClass();
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        transactionWriteRequest.withIdempotencyToken(UUID.randomUUID().toString());

        executeTransactWriteAndVerify(transactionWriteRequest, obj, obj);
    }

    @Test
    public void testTransactionWriteOnNonExistingTableReturnsResourceNotFoundException() {
        final int numItems = 10;
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        for ( int i = 0; i < numItems; i++ ) {
            NoSuchTableClass obj = new NoSuchTableClass();
            obj.setKey("someKey");
            transactionWriteRequest.addPut(obj);
        }

        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected ResourceNotFoundException but no exception thrown");
        } catch (ResourceNotFoundException e) {
            // Pass
        }
    }

    @Test
    public void testMixedOperationsOnSingleTableSucceeds() {

        StringAttributeClass objectToBeUpdated = getStringAttributeClass();
        StringAttributeClass objectToBeConditionChecked = getStringAttributeClass();
        StringAttributeClass objectToBeDeleted = getStringAttributeClass();

        // Save it so that we can update it inside transaction
        dynamoMapper.save(objectToBeUpdated);
        // Save it so that we can conditionCheck it inside transaction
        dynamoMapper.save(objectToBeConditionChecked);
        // Save it so that we can delete it inside transaction
        dynamoMapper.save(objectToBeDeleted);

        // Save the object
        StringAttributeClass objectToBePut = getStringAttributeClass();
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(objectToBePut);
        // Update the object
        String updatedStringAttribute = "updatedStringAttribute";
        objectToBeUpdated.setStringAttribute(updatedStringAttribute);
        transactionWriteRequest.addUpdate(objectToBeUpdated);
        // ConditionCheck the object
        DynamoDBTransactionWriteExpression conditionCheckWriteExpression =
                generateStringMatcherTransactWriteExpression(objectToBeConditionChecked.getStringAttribute(),
                                                             "not" + updatedStringAttribute);
        transactionWriteRequest.addConditionCheck(objectToBeConditionChecked, conditionCheckWriteExpression);
        // Delete the object
        StringAttributeClass objectToBeDeletedKey = new StringAttributeClass();
        objectToBeDeletedKey.setKey(objectToBeDeleted.getKey());

        transactionWriteRequest.addDelete(objectToBeDeletedKey);

        // Ensure transactWrite succeeds implying conditionCheck succeeds
        dynamoMapper.transactionWrite(transactionWriteRequest);

        // Ensure toPut object is put
        assertEquals(objectToBePut, dynamoMapper.load(objectToBePut));
        // Ensure toUpdate object is updated
        assertEquals(updatedStringAttribute, dynamoMapper.load(objectToBeUpdated).getStringAttribute());
        // Ensure toDelete object is deleted
        assertEquals(null, dynamoMapper.load(objectToBeDeleted));
    }

    @Test
    public void testPutViaTransactionWriteWithConditionExpressionSucceeds() {
        StringAttributeClass objectToBeSaved = getStringAttributeClass();
        dynamoMapper.save(objectToBeSaved);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        String oldStringValue = objectToBeSaved.getStringAttribute();
        String newStringValue = "saveStringValue";
        objectToBeSaved.setStringAttribute(newStringValue);
        // Update the object with condition on same attribute that is being updated
        DynamoDBTransactionWriteExpression saveItemExpression =
                generateStringMatcherTransactWriteExpression(oldStringValue, "not" + oldStringValue);
        transactionWriteRequest.addPut(objectToBeSaved, saveItemExpression);

        executeTransactWriteAndVerify(transactionWriteRequest, objectToBeSaved, objectToBeSaved);
    }

    @Test
    public void testDeleteViaTransactionWriteWithConditionExpressionSucceeds() {
        StringAttributeClass objectToBeDeleted = getStringAttributeClass();
        dynamoMapper.save(objectToBeDeleted);
        assertEquals(objectToBeDeleted, dynamoMapper.load(objectToBeDeleted));

        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        // Update the object with condition on same attribute that is being updated
        DynamoDBTransactionWriteExpression saveItemExpression =
                generateStringMatcherTransactWriteExpression(objectToBeDeleted.getStringAttribute(),
                                                             "not" + objectToBeDeleted.getStringAttribute());
        transactionWriteRequest.addDelete(objectToBeDeleted, saveItemExpression);

        executeTransactWriteAndVerify(transactionWriteRequest, objectToBeDeleted, null);
    }

    @Test
    public void testUpdateItemWithConditionExpressionSucceeds() {
        StringAttributeClass objectToBeUpdated = getStringAttributeClass();
        dynamoMapper.save(objectToBeUpdated);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();

        String updatedStringAttribute = "updatedStringAttribute";
        String oldUpdateStringAttribute = objectToBeUpdated.getStringAttribute();

        // Update the object with condition on same attribute that is being updated
        objectToBeUpdated.setStringAttribute(updatedStringAttribute);
        DynamoDBTransactionWriteExpression updateItemExpression =
                generateStringMatcherTransactWriteExpression(oldUpdateStringAttribute, "not" + updatedStringAttribute);
        transactionWriteRequest.addUpdate(objectToBeUpdated, updateItemExpression);

        executeTransactWriteAndVerify(transactionWriteRequest, objectToBeUpdated, objectToBeUpdated);
    }

    @Test
    public void testUpdateItemWithConditionExpressionFails() {
        StringAttributeClass objectToBeUpdated = getStringAttributeClass();
        dynamoMapper.save(objectToBeUpdated);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();

        String updatedStringAttribute = "updatedStringAttribute";
        String oldUpdateStringAttribute = objectToBeUpdated.getStringAttribute();

        // Update the object with condition on same attribute that is being updated
        objectToBeUpdated.setStringAttribute(updatedStringAttribute);
        DynamoDBTransactionWriteExpression updateItemExpression =
                generateStringMatcherTransactWriteExpression("not" + oldUpdateStringAttribute,
                                                             "notEither" + updatedStringAttribute);
        transactionWriteRequest.addUpdate(objectToBeUpdated, updateItemExpression, ReturnValuesOnConditionCheckFailure.ALL_OLD);

        try {
            dynamoMapper.transactionWrite(transactionWriteRequest);
            fail("Expected TransactionCanceledException but no exception thrown");
        } catch (TransactionCanceledException tce) {
            // Expected
        }
    }

    @Test
    public void testUpdateItemWithAllNonKeyAttributesNullSucceeds() {
        StringAttributeClass obj = getStringAttributeClass();
        dynamoMapper.save(obj);
        assertEquals(obj, dynamoMapper.load(obj));

        StringAttributeClass objToUpdate = new StringAttributeClass();
        objToUpdate.setKey(obj.getKey());
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        transactionWriteRequest.addUpdate(objToUpdate, writeExpression);
        dynamoMapper.transactionWrite(transactionWriteRequest);

        StringAttributeClass updatedObject = dynamoMapper.load(obj);
        assertEquals(null, updatedObject.getStringAttribute());
        assertEquals(null, updatedObject.getRenamedAttribute());
    }

    @Test
    public void testUpdateItemWithMixedNullAndNonNullNonKeyAttributesSucceeds() {
        StringAttributeClass obj = getStringAttributeClass();
        String updatedString = "updatedString";
        dynamoMapper.save(obj);
        assertEquals(obj, dynamoMapper.load(obj));

        StringAttributeClass objToUpdate = new StringAttributeClass();
        objToUpdate.setKey(obj.getKey());
        objToUpdate.setStringAttribute(updatedString);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        transactionWriteRequest.addUpdate(objToUpdate, writeExpression);
        executeTransactWriteAndVerify(transactionWriteRequest, objToUpdate, objToUpdate);
    }

    @Test
    public void testUpdateItemWithMultipleMixedNullAndNonNullNonKeyAttributesSucceeds() {
        TestItem obj = getTestItemObject();
        String updatedString = "updatedString";
        Set<String> updatedStringSet = new HashSet<String>();
        updatedStringSet.add("UpdatedStringSet");
        dynamoMapper.save(obj);
        assertEquals(obj, dynamoMapper.load(obj));

        TestItem objToUpdate = new TestItem();
        objToUpdate.setHashKey(obj.getHashKey());
        objToUpdate.setRangeKey(obj.getRangeKey());
        objToUpdate.setStringAttribute(updatedString);
        objToUpdate.setStringSetAttribute(updatedStringSet);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        transactionWriteRequest.addUpdate(objToUpdate, writeExpression);
        executeTransactWriteAndVerify(transactionWriteRequest, objToUpdate, objToUpdate);
    }

    @Test
    public void testUpdateItemWithTransformerSucceeds() {
        DynamoDBMapper mapperWithTransformer = new DynamoDBMapper(dynamoDB, null,
                new AttributeAdder(ADDITIONAL_ATTRIBUTE_NAME, ATTRIBUTE_ADDER_START));
        TestItem obj = getTestItemObject();
        String updatedString = "updatedString";
        Set<String> updatedStringSet = new HashSet<String>();
        updatedStringSet.add("UpdatedStringSet");
        mapperWithTransformer.save(obj);
        assertEquals(obj, mapperWithTransformer.load(obj));

        // Retrieve the item directly to verify signature field exists
        Map<String, AttributeValue> key = new HashMap<String, AttributeValue>();
        key.put("hashKey", new AttributeValue(obj.getHashKey()));
        key.put("rangeKey", new AttributeValue().withN(String.valueOf(obj.getRangeKey())));
        GetItemResult item = dynamoDB.getItem(TestItem.TABLE_NAME, key);
        assertTrue(item.getItem().containsKey(ADDITIONAL_ATTRIBUTE_NAME));
        assertEquals(ATTRIBUTE_ADDER_START, Integer.parseInt(item.getItem().get(ADDITIONAL_ATTRIBUTE_NAME).getN()));

        TestItem objToUpdate = new TestItem();
        objToUpdate.setHashKey(obj.getHashKey());
        objToUpdate.setRangeKey(obj.getRangeKey());
        objToUpdate.setStringAttribute(updatedString);
        objToUpdate.setStringSetAttribute(updatedStringSet);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        transactionWriteRequest.addUpdate(objToUpdate, writeExpression);
        mapperWithTransformer.transactionWrite(transactionWriteRequest);
        assertEquals(objToUpdate, mapperWithTransformer.load(objToUpdate));

        // Retrieve the item directly to verify signature field exists and is different from prior signature
        key.put("hashKey", new AttributeValue(objToUpdate.getHashKey()));
        key.put("rangeKey", new AttributeValue().withN(String.valueOf(objToUpdate.getRangeKey())));
        GetItemResult updatedItem = dynamoDB.getItem(TestItem.TABLE_NAME, key);
        assertTrue(updatedItem.getItem().containsKey(ADDITIONAL_ATTRIBUTE_NAME));
        assertEquals(ATTRIBUTE_ADDER_START + 1, Integer.parseInt(updatedItem.getItem().get(ADDITIONAL_ATTRIBUTE_NAME).getN()));
    }

    @Test
    public void testUpdateItemWithTransformerNullAttributesSucceeds() {
        // Create object with additional attribute
        DynamoDBMapper mapperWithTransformer = new DynamoDBMapper(dynamoDB, null,
                new AttributeAdder(ADDITIONAL_ATTRIBUTE_NAME, ATTRIBUTE_ADDER_START));
        TestItem obj = getTestItemObject();
        String updatedString = "updatedString";
        Set<String> updatedStringSet = new HashSet<String>();
        updatedStringSet.add("UpdatedStringSet");
        mapperWithTransformer.save(obj);
        assertEquals(obj, mapperWithTransformer.load(obj));

        // Retrieve the item directly to verify additional field exists
        Map<String, AttributeValue> key = new HashMap<String, AttributeValue>();
        key.put("hashKey", new AttributeValue(obj.getHashKey()));
        key.put("rangeKey", new AttributeValue().withN(String.valueOf(obj.getRangeKey())));
        GetItemResult item = dynamoDB.getItem(TestItem.TABLE_NAME, key);
        assertTrue(item.getItem().containsKey(ADDITIONAL_ATTRIBUTE_NAME));
        assertEquals(ATTRIBUTE_ADDER_START, Integer.parseInt(item.getItem().get(ADDITIONAL_ATTRIBUTE_NAME).getN()));

        // Update object with NullAttributeAdder (to verify removal of null non-modeled key)
        DynamoDBMapper mapperWithNullTransformer = new DynamoDBMapper(dynamoDB, null, new NullAttributeAdder(ADDITIONAL_ATTRIBUTE_NAME));

        TestItem objToUpdate = new TestItem();
        objToUpdate.setHashKey(obj.getHashKey());
        objToUpdate.setRangeKey(obj.getRangeKey());
        objToUpdate.setStringAttribute(updatedString);
        objToUpdate.setStringSetAttribute(updatedStringSet);
        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        transactionWriteRequest.addUpdate(objToUpdate, writeExpression);
        mapperWithNullTransformer.transactionWrite(transactionWriteRequest);
        assertEquals(objToUpdate, mapperWithNullTransformer.load(objToUpdate));

        // Retrieve the item directly to verify additional field doesn't exit
        key.put("hashKey", new AttributeValue(objToUpdate.getHashKey()));
        key.put("rangeKey", new AttributeValue().withN(String.valueOf(objToUpdate.getRangeKey())));
        GetItemResult updatedItem = dynamoDB.getItem(TestItem.TABLE_NAME, key);
        assertFalse(updatedItem.getItem().containsKey(ADDITIONAL_ATTRIBUTE_NAME));
    }

    @Test
    public void testPutItemWithTransformerSucceeds() {
        DynamoDBMapper mapperWithTransformer = new DynamoDBMapper(dynamoDB, null,
                new AttributeAdder(ADDITIONAL_ATTRIBUTE_NAME, ATTRIBUTE_ADDER_START));
        TestItem obj = getTestItemObject();

        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        mapperWithTransformer.transactionWrite(transactionWriteRequest);
        assertEquals(obj, mapperWithTransformer.load(obj));

        // Retrieve the item directly to verify signature field exists
        Map<String, AttributeValue> key = new HashMap<String, AttributeValue>();
        key.put("hashKey", new AttributeValue(obj.getHashKey()));
        key.put("rangeKey", new AttributeValue().withN(String.valueOf(obj.getRangeKey())));
        GetItemResult item = dynamoDB.getItem(TestItem.TABLE_NAME, key);
        assertTrue(item.getItem().containsKey(ADDITIONAL_ATTRIBUTE_NAME));
        assertEquals(ATTRIBUTE_ADDER_START, Integer.parseInt(item.getItem().get(ADDITIONAL_ATTRIBUTE_NAME).getN()));
    }

    @Test
    public void testPutViaTransactionWriteWithADocumentSucceeds() {
        final ChildClass child1 = new ChildClass();
        child1.setBool(true);

        final ChildClass child2 = new ChildClass();
        child2.setBool(true);

        final ChildClass parent = new ChildClass();
        parent.setFirstChild(child1);
        parent.setOtherChildren(Arrays.asList(child1, child2));
        parent.setNamedChildren(new HashMap<String, ChildClass>() {{
            put("one", child1);
            put("two", child2);
        }});

        TestDocClass obj = new TestDocClass();
        obj.setId("test");
        obj.setListOfMaps(Arrays.<Map<String, ChildClass>>asList(
                new HashMap<String, ChildClass>() {{
                    put("parent", parent);
                }},
                new HashMap<String, ChildClass>() {{
                    put("parent", parent);
                }},
                null
        ));
        obj.setMapOfLists(new HashMap<String, List<ChildClass>>() {{
            put("parent", Arrays.asList(child1, child2));
            put("child2", Collections.<ChildClass>emptyList());
            put("child1", null);
        }});

        TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
        transactionWriteRequest.addPut(obj);
        dynamoMapper.transactionWrite(transactionWriteRequest);

        TransactionLoadRequest transactionLoadRequest = new TransactionLoadRequest();
        transactionLoadRequest.addLoad(obj);
        List<Object> responseObjList = transactionLoadObjects(transactionLoadRequest);
        assertTrue(responseObjList.size() == 1);
        assertEquals(obj, responseObjList.get(0));
    }

    private void executeTransactWriteAndVerify(TransactionWriteRequest transactionWriteRequest,
                                               Object requestKey, Object responseObject) {
        dynamoMapper.transactionWrite(transactionWriteRequest);
        assertEquals(responseObject, dynamoMapper.load(requestKey));
    }

    private DynamoDBTransactionWriteExpression generateStringMatcherTransactWriteExpression(String matchingString1,
                                                                                            String matchingString2) {
        DynamoDBTransactionWriteExpression writeExpression = new DynamoDBTransactionWriteExpression();
        Map<String, String> attributeNameMap = new HashMap<String, String>();
        attributeNameMap.put("#sA", "stringAttribute");
        writeExpression.withConditionExpression("(#sA IN (:attr1, :attr2))");
        Map<String, AttributeValue> attributeValueMap = new HashMap<String, AttributeValue>();
        attributeValueMap.put(":attr1", new AttributeValue(matchingString1));
        attributeValueMap.put(":attr2", new AttributeValue(matchingString2));
        writeExpression.withExpressionAttributeValues(attributeValueMap);
        writeExpression.withExpressionAttributeNames(attributeNameMap);
        return writeExpression;
    }
}