package software.amazon.awssdk.enhanced.dynamodb.functionaltests;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Instant;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbAsyncTable;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedAsyncClient;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.functionaltests.models.RecordWithUpdateBehaviors;
import software.amazon.awssdk.enhanced.dynamodb.internal.client.ExtensionResolver;

public class AsyncUpdateBehaviorTest extends LocalDynamoDbAsyncTestBase {
    private static final Instant INSTANT_1 = Instant.parse("2020-05-03T10:00:00Z");
    private static final Instant INSTANT_2 = Instant.parse("2020-05-03T10:05:00Z");

    private static final TableSchema<RecordWithUpdateBehaviors> TABLE_SCHEMA =
        TableSchema.fromClass(RecordWithUpdateBehaviors.class);

    private final DynamoDbEnhancedAsyncClient enhancedAsyncClient = DynamoDbEnhancedAsyncClient.builder()
                                                                                                 .dynamoDbClient(getDynamoDbAsyncClient())
                                                                                                 .extensions(Stream.concat(
                                                                                                     ExtensionResolver.defaultExtensions().stream(),
                                                                                                     Stream.of(AutoGeneratedTimestampRecordExtension.create()))
                                                                                                                   .collect(Collectors.toList()))
                                                                                                 .build();

    private final DynamoDbAsyncTable<RecordWithUpdateBehaviors> mappedTable =
        enhancedAsyncClient.table(getConcreteTableName("table-name"), TABLE_SCHEMA);

    @Before
    public void createTable() {
        mappedTable.createTable(r -> r.provisionedThroughput(getDefaultProvisionedThroughput())).join();
    }

    @After
    public void deleteTable() {
        getDynamoDbAsyncClient().deleteTable(r -> r.tableName(getConcreteTableName("table-name"))).join();
    }

    @Test
    public void updateItem_withWriteIfNotExistsBehavior_shouldPreserveOnSecondUpdateAndIncrementVersion() {
        RecordWithUpdateBehaviors seed = new RecordWithUpdateBehaviors();
        seed.setId("id1");
        seed.setCreatedOn(INSTANT_1);
        seed.setLastUpdatedOn(INSTANT_1);
        mappedTable.updateItem(seed).join();

        RecordWithUpdateBehaviors update = new RecordWithUpdateBehaviors();
        update.setId("id1");
        update.setVersion(1L);
        update.setCreatedOn(INSTANT_2);
        update.setLastUpdatedOn(INSTANT_2);
        mappedTable.updateItem(update).join();

        RecordWithUpdateBehaviors persisted = mappedTable.getItem(r -> r.key(k -> k.partitionValue("id1"))).join();
        assertThat(persisted.getVersion()).isEqualTo(2L);
        assertThat(persisted.getCreatedOn()).as("WRITE_IF_NOT_EXISTS should preserve created time").isEqualTo(INSTANT_1);
        assertThat(persisted.getLastUpdatedOn()).isEqualTo(INSTANT_2);
    }
}
