/*
 * Copyright 2010-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.services.dynamodb.pojos;

import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbAutoGenerateStrategy;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbAutoGeneratedTimestamp;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbHashKey;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbIndexHashKey;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbRangeKey;
import software.amazon.awssdk.services.dynamodb.datamodeling.DynamoDbTable;

@DynamoDbTable(tableName = "Foo")
public class GsiWithAlwaysUpdateTimestamp {

    @DynamoDbHashKey
    private String hashKey;

    @DynamoDbRangeKey
    private String rangeKey;

    @DynamoDbAutoGeneratedTimestamp(strategy = DynamoDbAutoGenerateStrategy.ALWAYS)
    @DynamoDbIndexHashKey(globalSecondaryIndexName = "last-mod-date")
    private Long lastModifiedDate;

    public String getHashKey() {
        return hashKey;
    }

    public GsiWithAlwaysUpdateTimestamp setHashKey(String hashKey) {
        this.hashKey = hashKey;
        return this;
    }

    public String getRangeKey() {
        return rangeKey;
    }

    public GsiWithAlwaysUpdateTimestamp setRangeKey(String rangeKey) {
        this.rangeKey = rangeKey;
        return this;
    }

    public Long getLastModifiedDate() {
        return lastModifiedDate;
    }

    public GsiWithAlwaysUpdateTimestamp setLastModifiedDate(Long lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

}
