#!/usr/bin/env python

from scripts.generate_upgrade_sdk_dependencies_recipe import generate_upgrade_sdk_dependencies_recipe

def generate_recipes():
    generate_upgrade_sdk_dependencies_recipe()

if __name__ == '__main__':
    generate_recipes()
