/*
 * Copyright 2010-2019 Amazon.com, Inc. or its affiliates. All Rights
 * Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package software.amazon.awssdk.mapper.dynamodb.pojos;

import software.amazon.awssdk.mapper.dynamodb.DynamoDBAttribute;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBAutoGeneratedDefault;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBAutoGeneratedTimestamp;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBAutoGenerateStrategy;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBConvertedBool;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBDelimited;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBFlattened;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBGeneratedUuid;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBIgnore;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBIndexHashKey;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBIndexRangeKey;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBKeyed;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBNamed;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTable;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTypeConvertedJson;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBTypeConvertedEpochDate;

import com.amazonaws.services.dynamodbv2.model.KeyType;

import java.util.Date;
import java.util.UUID;

@DynamoDBTable(tableName = "aws-java-sdk-all-supported-annotations")
public class AllSupportedAnnotationsClass extends TestDocClass {

    public static final String IGNORED_ATTRIBUTE_VALUE = "ignoredAttribute";

    private String rangeKey;
    private Integer integerAttribute;
    private UUID uuid;
    private Date date;
    private Integer defaultAttribute;
    private Boolean booleanAttribute;
    private PhoneNumber phoneNumber;
    private String ignoredAttribute = IGNORED_ATTRIBUTE_VALUE;
    private String gsiHashKey;
    private String gsiRangeKey;
    private String namedAttribute;
    private Currency currencyAttribute;
    private Date epochDate;
    private DateRange dateRange;

    @DynamoDBKeyed(KeyType.RANGE)
    public String getRangeKey() {
        return rangeKey;
    }

    public void setRangeKey(String rangeKey) {
        this.rangeKey = rangeKey;
    }

    @DynamoDBAttribute(attributeName = "integerAttributeNew")
    public Integer getIntegerAttribute() {
        return integerAttribute;
    }

    public void setIntegerAttribute(Integer integerAttribute) {
        this.integerAttribute = integerAttribute;
    }

    @DynamoDBGeneratedUuid(DynamoDBAutoGenerateStrategy.ALWAYS)
    public UUID getUuid() {
        return uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    @DynamoDBAutoGeneratedTimestamp
    @DynamoDBAttribute
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @DynamoDBAutoGeneratedDefault("1")
    public Integer getDefaultAttribute() {
        return defaultAttribute;
    }

    public void setDefaultAttribute(Integer defaultAttribute) {
        this.defaultAttribute = defaultAttribute;
    }

    @DynamoDBConvertedBool(DynamoDBConvertedBool.Format.Y_N)
    public Boolean getBooleanAttribute() {
        return booleanAttribute;
    }

    public void setBooleanAttribute(Boolean booleanAttribute) {
        this.booleanAttribute = booleanAttribute;
    }

    @DynamoDBDelimited(attributeNames={"areaCode", "exchange", "subscriber"}, delimiter='-')
    public PhoneNumber getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(PhoneNumber phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @DynamoDBIgnore
    public String getIgnoredAttribute() {
        return ignoredAttribute;
    }

    public void setIgnoredAttribute(String ignoredAttribute) {
        this.ignoredAttribute = ignoredAttribute;
    }

    @DynamoDBIndexHashKey(attributeName="gsi_hashKey", globalSecondaryIndexName="gsi")
    public String getGsiHashKey() {
        return gsiHashKey;
    }

    public void setGsiHashKey(String gsiHashKey) {
        this.gsiHashKey = gsiHashKey;
    }

    @DynamoDBIndexRangeKey(attributeName="gsi_rangeKey", globalSecondaryIndexName="gsi")
    public String getGsiRangeKey() {
        return this.gsiRangeKey;
    }

    public void setGsiRangeKey(String gsiRangeKey) {
        this.gsiRangeKey = gsiRangeKey;
    }

    @DynamoDBNamed("renamedAttribute")
    public String getNamedAttribute() {
        return namedAttribute;
    }
    public void setNamedAttribute(String namedAttribute) {
        this.namedAttribute = namedAttribute;
    }

    @DynamoDBTypeConvertedJson
    public Currency getCurrencyAttribute() {
        return currencyAttribute;
    }

    public void setCurrencyAttribute(Currency currencyAttribute) {
        this.currencyAttribute = currencyAttribute;
    }

    @DynamoDBTypeConvertedEpochDate
    public Date getEpochDate() {
        return epochDate;
    }

    public void setEpochDate(Date epochDate) {
        this.epochDate = epochDate;
    }

    @DynamoDBFlattened(attributes={
            @DynamoDBAttribute(mappedBy="start", attributeName="DateRangeStart"),
            @DynamoDBAttribute(mappedBy="end", attributeName="DateRangeEnd")})
    public DateRange getDateRange() {
        return dateRange;
    }

    public void setDateRange(final DateRange dateRange) {
        this.dateRange = dateRange;
    }

    @Override
    public boolean equals(Object obj) {
        AllSupportedAnnotationsClass other = (AllSupportedAnnotationsClass) obj;

        return (eq(rangeKey, other.rangeKey)
                && eq(integerAttribute, other.integerAttribute)
                && eq(uuid, other.uuid)
                && eq(date, other.date)
                && eq(defaultAttribute, other.defaultAttribute)
                && eq(booleanAttribute, other.booleanAttribute)
                && eq(phoneNumber, other.phoneNumber)
                && eq(ignoredAttribute, other.ignoredAttribute)
                && eq(gsiHashKey, other.gsiHashKey)
                && eq(gsiRangeKey, other.gsiRangeKey)
                && eq(namedAttribute, other.namedAttribute)
                && eq(currencyAttribute, other.currencyAttribute)
                && eq(epochDate, other.epochDate)
                && eq(dateRange, other.dateRange)
                && super.equals(other)
        );
    }

    @Override
    public String toString() {
        return "{" + this.getClass().getSimpleName() + ": id=" + super.getId() + ", rangeKey=" + rangeKey + ", listOfMaps=" + super.getListOfMaps()
                + ", mapOfLists=" + super.getMapOfLists() + ", integerAttribute=" + integerAttribute + ", uuid=" + uuid + ", date=" + date
                + ", defaultAttribute=" + defaultAttribute + ", booleanAttribute=" + booleanAttribute + ", phoneNumber=" + phoneNumber
                + ", ignoredAttribute=" + ignoredAttribute + ", gsiHashKey=" + gsiHashKey + ", gsiRangeKey=" + gsiRangeKey
                + ", namedAttribute=" + namedAttribute + ", currencyAttribute=" + currencyAttribute + ", epochDate=" + epochDate +", dateRange=" + dateRange
                + "}";
    }
}
