/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.enhanced.dynamodb.functionaltests.extensions;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static software.amazon.awssdk.enhanced.dynamodb.UuidTestUtils.isValidUuid;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbTable;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.functionaltests.LocalDynamoDbSyncTestBase;
import software.amazon.awssdk.enhanced.dynamodb.internal.client.ExtensionResolver;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.model.TransactWriteItemsEnhancedRequest;
import software.amazon.awssdk.enhanced.dynamodb.model.WriteBatch;

public class AutoGeneratedUuidExtensionTest extends LocalDynamoDbSyncTestBase {

    private static final TableSchema<RecordWithAutogeneratedUuid> TABLE_SCHEMA =
        TableSchema.fromClass(RecordWithAutogeneratedUuid.class);

    private final DynamoDbEnhancedClient enhancedClient =
        DynamoDbEnhancedClient.builder()
                              .dynamoDbClient(getDynamoDbClient())
                              .extensions(Stream.concat(
                                                    ExtensionResolver.defaultExtensions().stream(),
                                                    Stream.of(AutoGeneratedUuidExtension.create()))
                                                .collect(Collectors.toList()))
                              .build();

    private final DynamoDbTable<RecordWithAutogeneratedUuid> mappedTable =
        enhancedClient.table(getConcreteTableName("autogenerated-uuid-table"), TABLE_SCHEMA);

    @Before
    public void createTable() {
        mappedTable.createTable(r -> r.provisionedThroughput(getDefaultProvisionedThroughput()));
    }

    @After
    public void deleteTable() {
        getDynamoDbClient().deleteTable(r -> r.tableName(getConcreteTableName("autogenerated-uuid-table")));
    }

    @Test
    public void putItem_whenKeysNotAlreadyPopulated_generatesNewUuids() {
        RecordWithAutogeneratedUuid record = new RecordWithAutogeneratedUuid();
        record.setId("existing-id");

        mappedTable.putItem(record);
        RecordWithAutogeneratedUuid result = mappedTable.scan().items().stream().findFirst()
                                                        .orElseThrow(() -> new AssertionError("No record found"));

        isValidUuid(result.getId());
        isValidUuid(result.getSortKey());
    }

    @Test
    public void putItem_whenKeysAlreadyPopulated_replacesExistingUuids() {
        RecordWithAutogeneratedUuid record = new RecordWithAutogeneratedUuid();
        record.setId("existing-id");
        record.setSortKey("existing-sk");

        mappedTable.putItem(record);
        RecordWithAutogeneratedUuid result = mappedTable.scan().items().stream().findFirst()
                                                        .orElseThrow(() -> new AssertionError("No record found"));

        isValidUuid(result.getId());
        isValidUuid(result.getSortKey());
        assertThat(result.getId()).isNotEqualTo("existing-id");
        assertThat(result.getSortKey()).isNotEqualTo("existing-sk");
    }

    @Test
    public void batchWrite_whenKeysNotAlreadyPopulated_generatesNewUuids() {
        RecordWithAutogeneratedUuid record1 = new RecordWithAutogeneratedUuid();
        RecordWithAutogeneratedUuid record2 = new RecordWithAutogeneratedUuid();

        enhancedClient.batchWriteItem(req -> req.addWriteBatch(
            WriteBatch.builder(RecordWithAutogeneratedUuid.class)
                      .mappedTableResource(mappedTable)
                      .addPutItem(record1)
                      .addPutItem(record2)
                      .build()));
        List<RecordWithAutogeneratedUuid> results = mappedTable.scan().items().stream().collect(Collectors.toList());

        assertThat(results.size()).isEqualTo(2);
        isValidUuid(results.get(0).getId());
        isValidUuid(results.get(1).getId());
        isValidUuid(results.get(0).getSortKey());
        isValidUuid(results.get(1).getSortKey());
    }

    @Test
    public void batchWrite_whenKeysAlreadyPopulated_generatesNewUuids() {
        RecordWithAutogeneratedUuid record1 = new RecordWithAutogeneratedUuid();
        record1.setId("existing-id-1");
        record1.setSortKey("existing-sk-1");

        RecordWithAutogeneratedUuid record2 = new RecordWithAutogeneratedUuid();
        record2.setId("existing-id-2");
        record2.setSortKey("existing-sk-2");

        enhancedClient.batchWriteItem(req -> req.addWriteBatch(
            WriteBatch.builder(RecordWithAutogeneratedUuid.class)
                      .mappedTableResource(mappedTable)
                      .addPutItem(record1)
                      .addPutItem(record2)
                      .build()));

        List<RecordWithAutogeneratedUuid> results = mappedTable.scan().items().stream().collect(Collectors.toList());

        assertThat(results.size()).isEqualTo(2);
        isValidUuid(results.get(0).getId());
        isValidUuid(results.get(1).getId());
        isValidUuid(results.get(0).getSortKey());
        isValidUuid(results.get(1).getSortKey());

        assertThat(results.get(0).getId()).isNotEqualTo("existing-id-1");
        assertThat(results.get(1).getId()).isNotEqualTo("existing-id-2");
        assertThat(results.get(0).getSortKey()).isNotEqualTo("existing-sk-1");
        assertThat(results.get(1).getSortKey()).isNotEqualTo("existing-sk-2");
    }

    @Test
    public void transactWrite_whenKeysNotAlreadyPopulated_generatesNewUuids() {
        RecordWithAutogeneratedUuid record = new RecordWithAutogeneratedUuid();

        enhancedClient.transactWriteItems(
            TransactWriteItemsEnhancedRequest.builder()
                                             .addPutItem(mappedTable, record)
                                             .build());
        RecordWithAutogeneratedUuid result = mappedTable.scan().items().stream().findFirst()
                                                        .orElseThrow(() -> new AssertionError("No record found"));

        isValidUuid(result.getId());
        isValidUuid(result.getSortKey());
    }

    @Test
    public void transactWrite_whenKeysAlreadyPopulated_generatesNewUuids() {
        RecordWithAutogeneratedUuid record = new RecordWithAutogeneratedUuid();
        record.setId("existing-id");
        record.setSortKey("existing-sk");

        enhancedClient.transactWriteItems(
            TransactWriteItemsEnhancedRequest.builder()
                                             .addPutItem(mappedTable, record)
                                             .build());
        RecordWithAutogeneratedUuid result = mappedTable.scan().items().stream().findFirst()
                                                        .orElseThrow(() -> new AssertionError("No record found"));

        isValidUuid(result.getId());
        isValidUuid(result.getSortKey());
        assertThat(result.getId()).isNotEqualTo("existing-id");
        assertThat(result.getSortKey()).isNotEqualTo("existing-sk");
    }

    @Test
    public void putItem_whenAutogeneratedUuidAnnotationIsNotPresent_doesNotRegenerateUuids() {
        String tableName = "no-autogenerated-uuid-table";
        DynamoDbTable<RecordWithoutAutogeneratedUuid> mappedTable =
            enhancedClient.table(tableName, TableSchema.fromClass(RecordWithoutAutogeneratedUuid.class));

        try {
            mappedTable.createTable(r -> r.provisionedThroughput(getDefaultProvisionedThroughput()));

            RecordWithoutAutogeneratedUuid record = new RecordWithoutAutogeneratedUuid();
            record.setId("existing-id");
            record.setSortKey("existing-sk");
            record.setGsiPk("existing-gsiPk");
            record.setGsiSk("existing-gsiSk");
            record.setData("data");

            mappedTable.putItem(record);
            RecordWithoutAutogeneratedUuid retrieved = mappedTable.getItem(
                r -> r.key(k -> k.partitionValue("existing-id").sortValue("existing-sk")));

            assertThat(retrieved.getId()).isEqualTo("existing-id");
            assertThat(retrieved.getSortKey()).isEqualTo("existing-sk");
            assertThat(retrieved.getGsiPk()).isEqualTo("existing-gsiPk");
            assertThat(retrieved.getGsiSk()).isEqualTo("existing-gsiSk");
            assertThat(retrieved.getData()).isEqualTo("data");
        } finally {
            try {
                mappedTable.deleteTable();
            } catch (Exception ignored) {
            }
        }
    }

    @Test
    public void createBean_whenAutogeneratedUuidAnnotationIsAppliedOnNonStringAttribute_throwsException() {
        assertThatThrownBy(() -> TableSchema.fromBean(AutogeneratedUuidInvalidTypeRecord.class))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("not a suitable Java Class type to be used as a Auto Generated Uuid attribute")
            .hasMessageContaining("Only String Class type is supported");
    }

    @DynamoDbBean
    public static class RecordWithAutogeneratedUuid {
        private String id;
        private String sortKey;

        @DynamoDbPartitionKey
        @DynamoDbAutoGeneratedUuid
        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        @DynamoDbSortKey
        @DynamoDbAutoGeneratedUuid
        public String getSortKey() {
            return sortKey;
        }

        public void setSortKey(String sortKey) {
            this.sortKey = sortKey;
        }
    }

    @DynamoDbBean
    public static class RecordWithoutAutogeneratedUuid {
        private String id;
        private String sortKey;
        private String gsiPk;
        private String gsiSk;
        private String data;

        @DynamoDbPartitionKey
        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        @DynamoDbSortKey
        public String getSortKey() {
            return sortKey;
        }

        public void setSortKey(String sortKey) {
            this.sortKey = sortKey;
        }

        @DynamoDbSecondaryPartitionKey(indexNames = "gsi1")
        @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_ALWAYS)
        public String getGsiPk() {
            return gsiPk;
        }

        public void setGsiPk(String gsiPk) {
            this.gsiPk = gsiPk;
        }

        @DynamoDbSecondarySortKey(indexNames = "gsi1")
        @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
        public String getGsiSk() {
            return gsiSk;
        }

        public void setGsiSk(String gsiSk) {
            this.gsiSk = gsiSk;
        }

        public String getData() {
            return data;
        }

        public void setData(String data) {
            this.data = data;
        }
    }

    @DynamoDbBean
    public static class AutogeneratedUuidInvalidTypeRecord {
        private Integer id;

        @DynamoDbPartitionKey
        @DynamoDbAutoGeneratedUuid
        public Integer getId() {
            return id;
        }

        public void setId(Integer id) {
            this.id = id;
        }
    }
}