/*
 * Copyright 2010-2019 Amazon.com, Inc. or its affiliates. All Rights
 * Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package software.amazon.awssdk.mapper.dynamodb.mapper;

import static software.amazon.awssdk.mapper.dynamodb.TestObjectCreator.createHashKeyRangeKeyTable;
import static software.amazon.awssdk.mapper.dynamodb.TestObjectCreator.createSdkMapperSaveConfigTable;
import static software.amazon.awssdk.mapper.dynamodb.TestObjectCreator.createSdkRangeTestTable;
import static software.amazon.awssdk.mapper.dynamodb.TestObjectCreator.createSdkStringRangeTable;
import static software.amazon.awssdk.mapper.dynamodb.TestObjectCreator.createStringHashKeyTable;
import static software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig.TableNameResolver;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import software.amazon.awssdk.mapper.dynamodb.LocalDynamoDBTestBase;
import java.util.List;

import software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperIntegrationTestBase;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBMapper;
import software.amazon.awssdk.mapper.dynamodb.DynamoDBMapperConfig;
import software.amazon.awssdk.mapper.dynamodb.TransactionLoadRequest;
import software.amazon.awssdk.mapper.dynamodb.TransactionWriteRequest;
import com.amazonaws.services.dynamodbv2.model.TransactionCanceledException;
import software.amazon.awssdk.mapper.dynamodb.pojos.HashKeyAutoGenerated;
import software.amazon.awssdk.mapper.dynamodb.pojos.HashKeyRangeKeyBothAutoGenerated;
import software.amazon.awssdk.mapper.dynamodb.pojos.HashKeyRangeKeyClass;
import software.amazon.awssdk.mapper.dynamodb.pojos.HashRangeAndOtherAttributeAutoGen;
import software.amazon.awssdk.mapper.dynamodb.pojos.MultiVersionRangeKeyClass;
import software.amazon.awssdk.mapper.dynamodb.pojos.PrimaryKeysNotAutogenerated_IndexKeysAutogenerated;
import software.amazon.awssdk.mapper.dynamodb.pojos.PrimaryKeysNotAutogenerated_OtherAttributeAutogenerated;
import software.amazon.awssdk.mapper.dynamodb.pojos.RangeKeyClass;
import software.amazon.awssdk.mapper.dynamodb.pojos.SlimAttributeNamesClass;
import software.amazon.awssdk.mapper.dynamodb.pojos.StringAttributeClass;
import software.amazon.awssdk.mapper.dynamodb.pojos.TestItem;
import org.junit.BeforeClass;

public class TransactionsTestBase extends LocalDynamoDBTestBase {

    protected static final String tableNameSuffix = "bff5478c-929b-4952-9c91-ab0780dba849";
    protected static final String sdkUtilTableName = "sdk-util-" + tableNameSuffix;
    protected static final String mapperSaveConfigTableName = "mapper-save-config-" + tableNameSuffix;
    protected static final String sdkRangeTableName = "sdk-range-" + tableNameSuffix;
    private static final String sdkStringRangeTableName = "sdk-string-range-" + tableNameSuffix;
    protected static final String sdkHashRangeTestTableName = "sdk-hash-range-test-" + tableNameSuffix;
    protected static final TableNameResolver tableNameResolver = new TableNameResolver() {
            @Override
            public String getTableName(Class<?> clazz, DynamoDBMapperConfig config) {
                if (StringAttributeClass.class.equals(clazz)) {
                    return sdkUtilTableName;
                }
                if (TestItem.class.equals(clazz) || SlimAttributeNamesClass.class.equals(clazz)) {
                    return mapperSaveConfigTableName;
                }
                if (RangeKeyClass.class.equals(clazz) || MultiVersionRangeKeyClass.class.equals(clazz)) {
                    return sdkRangeTableName;
                }
                if (PrimaryKeysNotAutogenerated_IndexKeysAutogenerated.class.equals(clazz)
                            || PrimaryKeysNotAutogenerated_OtherAttributeAutogenerated.class.equals(clazz)
                            || HashKeyRangeKeyBothAutoGenerated.class.equals(clazz)
                            || HashRangeAndOtherAttributeAutoGen.class.equals(clazz)
                            || HashKeyAutoGenerated.class.equals(clazz)) {
                    return sdkStringRangeTableName;
                }
                if (HashKeyRangeKeyClass.class.equals(clazz)) {
                    return sdkHashRangeTestTableName;
                }
                throw new RuntimeException("Unable to resolve table name for input object type: " + clazz);
            }
        };

    protected static DynamoDBMapper dynamoMapper;
    protected static AmazonDynamoDB dynamo;

    @BeforeClass
    public static void setUp() throws Exception {
        DynamoDBMapperConfig config = DynamoDBMapperConfig.builder().withTableNameResolver(tableNameResolver).build();

        dynamo = client();
        dynamoMapper = new DynamoDBMapper(dynamo, config);
        // TODO: Add table creation here only if the table is being used across child classes
        createSdkMapperSaveConfigTable(dynamo, mapperSaveConfigTableName);
        createSdkRangeTestTable(dynamo, sdkRangeTableName);
        createStringHashKeyTable(dynamo, sdkUtilTableName);
        createSdkStringRangeTable(dynamo, sdkStringRangeTableName);
        createHashKeyRangeKeyTable(dynamo, sdkHashRangeTestTableName);
    }

    public static void saveObjects(DynamoDBMapper mapper, Object... objs) {
        for (Object obj: objs) {
            saveObject(mapper, obj);
        }
    }

    public static void saveObject(Object obj) {
        saveObject(dynamoMapper, obj);
    }

    public static void saveObject(DynamoDBMapper mapper, Object obj) {
        mapper.save(obj);
    }

    protected void executeAndValidateTransactionLoad(TransactionLoadRequest transactionLoadRequest, List<Object> expectedObjects) {
        executeAndValidateTransactionLoad(dynamoMapper, transactionLoadRequest, expectedObjects);
    }

    protected void executeAndValidateTransactionLoad(DynamoDBMapper mapper, TransactionLoadRequest transactionLoadRequest, List<Object> expectedObjects) {
        List<Object> responseObjects = doTransactionLoad(mapper, transactionLoadRequest);
        int numItems = expectedObjects.size();
        assertEquals(numItems, responseObjects.size());
        for (int i = 0; i < numItems; i++) {
            assertEquals(expectedObjects.get(i), responseObjects.get(i));
        }
    }

    protected void executeAndValidateTransactionWrite(TransactionWriteRequest transactionWriteRequest,
                                                      List<Object> expectedResponseObjectKeys,
                                                      List<Object> expectedResponseObjects) {
        executeAndValidateTransactionWrite(dynamoMapper,
                                           transactionWriteRequest,
                                           expectedResponseObjectKeys,
                                           expectedResponseObjects);
    }

    protected void executeAndValidateTransactionWrite(DynamoDBMapper mapper,
                                                      TransactionWriteRequest transactionWriteRequest,
                                                      List<Object> expectedResponseObjectKeys,
                                                      List<Object> expectedResponseObjects) {
        mapper.transactionWrite(transactionWriteRequest);
        int numItems = expectedResponseObjectKeys.size();
        TransactionLoadRequest transactionLoadRequest = new TransactionLoadRequest();
        for (Object objKey: expectedResponseObjectKeys) {
            transactionLoadRequest.addLoad(objKey);
        }

        // transactionLoad can sometimes fail due to conflict with above transactionWrite which is not yet complete, so we re-try for some time when
        // that type of failure is encountered
        List<Object> actualResponseObjects = doTransactionLoad(mapper, transactionLoadRequest);

        assertEquals(numItems, actualResponseObjects.size());
        for (int i = 0; i < numItems; i++) {
            assertEquals(expectedResponseObjects.get(i), actualResponseObjects.get(i));
        }
    }

    private List<Object> doTransactionLoad(DynamoDBMapper mapper, TransactionLoadRequest transactionLoadRequest) {
        long endTime = System.currentTimeMillis() + 30 * 1000;
        List<Object> response = null;
        while (System.currentTimeMillis() < endTime) {
            try {
                response = mapper.transactionLoad(transactionLoadRequest);
                break;
            } catch (TransactionCanceledException tce) {
                // Sleep for some time before re-trying transactionLoad
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ie) {
                    fail("interrupted while waiting to re-try transactionLoad: " + ie);
                }
            }
        }
        if (response == null) {
            fail("Timed out while executing transactionLoad due to conflict with ongoing transactionWrite");
        }
        return response;
    }
}
