/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.enhanced.dynamodb.functionaltests.document;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.nullValue;
import static software.amazon.awssdk.enhanced.dynamodb.AttributeConverterProvider.defaultProvider;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.Test;
import software.amazon.awssdk.enhanced.dynamodb.AttributeValueType;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbTable;
import software.amazon.awssdk.enhanced.dynamodb.TableMetadata;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.document.EnhancedDocument;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.functionaltests.LocalDynamoDbSyncTestBase;
import software.amazon.awssdk.enhanced.dynamodb.model.BatchWriteItemEnhancedRequest;
import software.amazon.awssdk.enhanced.dynamodb.model.BatchWriteResult;
import software.amazon.awssdk.enhanced.dynamodb.model.TransactWriteItemsEnhancedRequest;
import software.amazon.awssdk.enhanced.dynamodb.model.TransactWriteItemsEnhancedResponse;
import software.amazon.awssdk.enhanced.dynamodb.model.WriteBatch;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;
import software.amazon.awssdk.services.dynamodb.model.ReturnConsumedCapacity;
import software.amazon.awssdk.services.dynamodb.model.ReturnItemCollectionMetrics;

/**
 * Document-schema tests that exercise {@link AutoGeneratedTimestampRecordExtension}.
 * Kept out of the parameterized {@link BasicCrudTest} because these scenarios do not use {@code testData}.
 */
public class DocumentSchemaExtensionCrudTest extends LocalDynamoDbSyncTestBase {

    private DynamoDbEnhancedClient createExtensionClient() {
        return DynamoDbEnhancedClient.builder()
                                     .dynamoDbClient(getDynamoDbClient())
                                     .extensions(AutoGeneratedTimestampRecordExtension.create())
                                     .build();
    }

    private DynamoDbTable<EnhancedDocument> createExtensionDocumentTable(DynamoDbEnhancedClient extensionClient,
                                                                          String tableNameSuffix) {
        String tableName = getConcreteTableName(tableNameSuffix);
        DynamoDbTable<EnhancedDocument> extensionTable =
            extensionClient.table(tableName,
                                  TableSchema.documentSchemaBuilder()
                                             .addIndexPartitionKey(TableMetadata.primaryIndexName(), "id", AttributeValueType.S)
                                             .attributeConverterProviders(defaultProvider())
                                             .build());
        extensionTable.createTable(r -> r.provisionedThroughput(getDefaultProvisionedThroughput()));
        return extensionTable;
    }

    private void deleteExtensionTable(String tableName) {
        getDynamoDbClient().deleteTable(r -> r.tableName(tableName));
    }

    @Test
    public void documentSchema_withExtension_putAndUpdate_shouldSucceed() {
        DynamoDbEnhancedClient extensionClient = createExtensionClient();
        DynamoDbTable<EnhancedDocument> extensionTable = createExtensionDocumentTable(extensionClient, "doc-extension-table");
        String extensionTableName = extensionTable.tableName();

        EnhancedDocument document = EnhancedDocument.builder()
                                                    .attributeConverterProviders(defaultProvider())
                                                    .putString("id", "doc-1")
                                                    .putString("payload", "value")
                                                    .build();
        extensionTable.putItem(document);
        extensionTable.updateItem(document);

        EnhancedDocument persisted = extensionTable.getItem(r -> r.key(k -> k.partitionValue("doc-1")));
        assertThat(persisted, is(notNullValue()));
        deleteExtensionTable(extensionTableName);
    }

    @Test
    public void documentSchema_withExtension_shouldPreserveNonTimestampValues() {
        DynamoDbEnhancedClient extensionClient = createExtensionClient();
        DynamoDbTable<EnhancedDocument> extensionTable =
            createExtensionDocumentTable(extensionClient, "doc-extension-integrity-table");
        String extensionTableName = extensionTable.tableName();

        Map<String, AttributeValue> nested = new LinkedHashMap<>();
        nested.put("time", AttributeValue.fromS("nested-original"));
        nested.put("flag", AttributeValue.fromS("x"));

        Map<String, AttributeValue> itemMap = new LinkedHashMap<>();
        itemMap.put("id", AttributeValue.fromS("doc-1"));
        itemMap.put("time", AttributeValue.fromS("root-original"));
        itemMap.put("payload", AttributeValue.fromM(nested));
        itemMap.put("records", AttributeValue.fromL(Collections.singletonList(AttributeValue.fromM(nested))));

        EnhancedDocument document = EnhancedDocument.fromAttributeValueMap(itemMap).toBuilder()
                                                    .attributeConverterProviders(defaultProvider())
                                                    .build();

        extensionTable.putItem(document);
        extensionTable.updateItem(document);

        EnhancedDocument persisted = extensionTable.getItem(r -> r.key(k -> k.partitionValue("doc-1")));
        assertThat(persisted.toMap().get("time").s(), is("root-original"));
        assertThat(persisted.toMap().get("payload").m().get("time").s(), is("nested-original"));
        assertThat(persisted.toMap().get("records").l().get(0).m().get("time").s(), is("nested-original"));

        deleteExtensionTable(extensionTableName);
    }

    @Test
    public void documentSchema_withExtension_deleteItem_shouldSucceed() {
        DynamoDbEnhancedClient extensionClient = createExtensionClient();
        DynamoDbTable<EnhancedDocument> extensionTable =
            createExtensionDocumentTable(extensionClient, "doc-extension-delete-table");
        String extensionTableName = extensionTable.tableName();

        EnhancedDocument document = EnhancedDocument.builder()
                                                    .attributeConverterProviders(defaultProvider())
                                                    .putString("id", "doc-1")
                                                    .putString("payload", "value")
                                                    .build();
        extensionTable.putItem(document);
        extensionTable.deleteItem(r -> r.key(k -> k.partitionValue("doc-1")));
        assertThat(extensionTable.getItem(r -> r.key(k -> k.partitionValue("doc-1"))), is(nullValue()));

        deleteExtensionTable(extensionTableName);
    }

    @Test
    public void documentSchemaBatchWrite_withExtension_shouldPreserveValuesAndReturnMetrics() {
        DynamoDbEnhancedClient extensionClient = createExtensionClient();
        DynamoDbTable<EnhancedDocument> extensionTable =
            createExtensionDocumentTable(extensionClient, "doc-extension-batch-table");
        String extensionTableName = extensionTable.tableName();

        EnhancedDocument first = EnhancedDocument.builder()
                                                 .attributeConverterProviders(defaultProvider())
                                                 .putString("id", "doc-1")
                                                 .putString("time", "value-one")
                                                 .build();
        EnhancedDocument second = EnhancedDocument.builder()
                                                  .attributeConverterProviders(defaultProvider())
                                                  .putString("id", "doc-2")
                                                  .putString("time", "value-two")
                                                  .build();

        BatchWriteResult result = extensionClient.batchWriteItem(BatchWriteItemEnhancedRequest.builder()
                                                                                               .writeBatches(
                                                                                                   WriteBatch.builder(EnhancedDocument.class)
                                                                                                             .mappedTableResource(extensionTable)
                                                                                                             .addPutItem(r -> r.item(first))
                                                                                                             .addPutItem(r -> r.item(second))
                                                                                                             .build())
                                                                                               .returnConsumedCapacity(ReturnConsumedCapacity.TOTAL)
                                                                                               .returnItemCollectionMetrics(ReturnItemCollectionMetrics.SIZE)
                                                                                               .build());

        assertThat(result.consumedCapacity(), is(notNullValue()));
        assertThat(result.itemCollectionMetrics(), is(notNullValue()));
        assertThat(extensionTable.getItem(r -> r.key(k -> k.partitionValue("doc-1"))).toMap().get("time").s(), is("value-one"));
        assertThat(extensionTable.getItem(r -> r.key(k -> k.partitionValue("doc-2"))).toMap().get("time").s(), is("value-two"));

        deleteExtensionTable(extensionTableName);
    }

    @Test
    public void documentSchemaTransactWrite_withExtension_shouldPreserveValuesAndReturnMetrics() {
        DynamoDbEnhancedClient extensionClient = createExtensionClient();
        DynamoDbTable<EnhancedDocument> extensionTable =
            createExtensionDocumentTable(extensionClient, "doc-extension-transact-table");
        String extensionTableName = extensionTable.tableName();

        EnhancedDocument first = EnhancedDocument.builder()
                                                 .attributeConverterProviders(defaultProvider())
                                                 .putString("id", "doc-1")
                                                 .putString("time", "value-one")
                                                 .build();
        EnhancedDocument second = EnhancedDocument.builder()
                                                  .attributeConverterProviders(defaultProvider())
                                                  .putString("id", "doc-2")
                                                  .putString("time", "value-two")
                                                  .build();

        TransactWriteItemsEnhancedResponse response =
            extensionClient.transactWriteItemsWithResponse(TransactWriteItemsEnhancedRequest.builder()
                                                                                             .returnConsumedCapacity(ReturnConsumedCapacity.TOTAL)
                                                                                             .returnItemCollectionMetrics(ReturnItemCollectionMetrics.SIZE)
                                                                                             .addPutItem(extensionTable, first)
                                                                                             .addPutItem(extensionTable, second)
                                                                                             .build());

        assertThat(response.consumedCapacity(), is(notNullValue()));
        assertThat(response.itemCollectionMetrics(), is(notNullValue()));
        assertThat(extensionTable.getItem(r -> r.key(k -> k.partitionValue("doc-1"))).toMap().get("time").s(), is("value-one"));
        assertThat(extensionTable.getItem(r -> r.key(k -> k.partitionValue("doc-2"))).toMap().get("time").s(), is("value-two"));

        deleteExtensionTable(extensionTableName);
    }
}
